// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/API/transcode/` | (string & {});
};

export type AbortStorageTranscodeJobsSchema = {
    error_message?: string;
};

export type AnalyzeSchema = {
    force?: boolean;
    force_type?: 'APPEND' | 'OVERWRITE';
    service_name?: string;
};

export type AssetLinkData = {
    readonly site_name?: string;
    readonly title?: string;
};

export type AssetLinkUrlSchema = {
    url: string;
};

export type BulkActionSchema = {
    object_ids: Array<string>;
    object_type: 'assets' | 'collections' | 'saved_searches';
};

export type BulkAnalyzeSchema = {
    force?: boolean;
    force_type?: 'APPEND' | 'OVERWRITE';
    object_ids: Array<string>;
    object_type: 'assets' | 'collections' | 'saved_searches';
    profile_id?: string;
};

export type BulkMetadataFillingSchema = {
    field_names: Array<string>;
    object_ids: Array<string>;
    object_type: 'assets' | 'collections' | 'saved_searches';
    view_id: string;
};

export type BulkTranscribeSchema = {
    engine?: string | null;
    force?: boolean;
    language?: string | null;
    object_ids: Array<string>;
    object_type: 'assets' | 'collections' | 'saved_searches';
    profile_id?: string;
    speakers?: number | null;
    summary?: boolean | null;
    topics_extraction?: boolean;
    translate_languages?: Array<string> | null;
};

export type EdgeThumbnailJobFieldSchema = {
    height?: number;
    id?: string;
    max_number?: number;
    min_interval?: number;
    time_end_milliseconds?: number | null;
    time_start_milliseconds?: number | null;
    timestamp?: number;
    width?: number;
};

export type EdgeTranscodeEndpointSchema = {
    data?: {
        [key: string]: unknown;
    };
    method?: string;
    storage_method?: string;
    type?: string;
    url: string;
};

export type EdgeTranscodeInputSchema = {
    asset_id?: string;
    closed_captions?: boolean;
    directory_path?: string;
    endpoint: EdgeTranscodeEndpointSchema;
    file_id?: string;
    file_set_id?: string | null;
    format_id?: string | null;
    language?: string;
    original_asset_id?: string | null;
    original_name?: string;
    proxy_id?: string | null;
    storage_id?: string;
};

export type EdgeTranscodeJobFieldSchema = {
    height?: number;
    id?: string;
    width?: number;
};

export type EdgeTranscodeJobSchema = {
    asset_id?: string;
    collection_id?: string;
    input: EdgeTranscodeInputSchema;
    job_id?: string;
    job_steps?: Array<JobStep>;
    media_info?: string | null;
    thumbnail?: Array<EdgeThumbnailJobFieldSchema>;
    transcode?: Array<EdgeTranscodeJobFieldSchema>;
};

export type EdgeTranscodeJobsSchema = {
    objects?: Array<EdgeTranscodeJobSchema>;
};

export type EdgeTranscodeWorkerSchema = {
    readonly id?: string;
    readonly last_update_date?: string;
    status: 'ACTIVE' | 'INACTIVE';
    storage_id: string;
};

export type EdgeTranscodeWorkersSchema = {
    objects?: Array<EdgeTranscodeWorkerSchema>;
};

export type EndpointSchema = {
    data?: {
        [key: string]: unknown;
    };
    headers?: {
        [key: string]: unknown;
    };
    method?: string;
    storage_method?: string;
    type?: string;
    url: string;
};

export type FacetBucketSchema = {
    doc_count?: number;
    key?: string;
};

export type FacetSchema = {
    buckets?: Array<FacetBucketSchema>;
    doc_count_error_upper_bound?: number;
    sum_other_doc_count?: number;
};

export type GenerateCollectionKeyframeSchema = {
    deleted_asset_id?: string;
    force?: boolean;
    specified_asset_ids?: Array<string>;
    specified_keyframes?: Array<SpecifiedKeyframes>;
};

export type InputSchema = {
    asset_id?: string | null;
    closed_captions?: boolean;
    collection_id?: string | null;
    directory_path?: string | null;
    endpoint: EndpointSchema;
    engine?: string;
    file_id?: string | null;
    file_set_id?: string | null;
    format_id?: string | null;
    language?: string;
    original_asset_id?: string | null;
    original_name?: string;
    proxy_id?: string | null;
    storage_id?: string;
    update_proxy_mediainfo?: boolean | null;
    version_id?: string | null;
};

export type JobBaseSchema = {
    asset_id?: string;
    collection_id?: string;
    input?: InputSchema;
    job_id?: string;
    job_steps?: Array<JobStep>;
    media_info?: string | null;
    thumbnail?: Array<ThumbnailJob>;
    transcode?: Array<TranscodeJob>;
};

export type JobSchema = {
    amazon_rekognition?: boolean;
    analysis_data?: {
        [key: string]: unknown;
    };
    analysis_query_default_service_account?: boolean;
    analyzed_before?: boolean;
    asset_id?: string;
    asset_link?: string;
    collection_id?: string;
    create_transcription?: boolean;
    delete_old_transcriptions?: boolean;
    force_transcoder?: string;
    google_cloud_video_intelligence?: boolean;
    input?: InputSchema;
    job_id?: string;
    job_steps?: Array<JobStep>;
    language?: string | null;
    media_info?: string | null;
    overwrite?: boolean;
    priority?: number;
    speakers?: number | null;
    thumbnail?: Array<ThumbnailJob>;
    transcode?: Array<TranscodeJob>;
    valid_transcoders?: Array<Transcoders>;
    version_id?: string;
};

export type JobStep = {
    date_created?: string;
    date_updated?: string;
    id?: string;
    label?: string;
    message?: string;
    status?: string;
};

export type JobStepSchema = {
    date_created?: string;
    date_updated?: string;
    id?: string;
    label?: string;
    message?: string;
    status?: string;
};

export type JobsPrioritySchema = {
    job_ids: Array<string>;
    priority: number;
};

export type JobsStateSchema = {
    action: 'ABORT' | 'RESTART';
    job_ids: Array<string>;
};

export type LlmMetadataJobSchema = {
    amazon_rekognition?: boolean;
    analysis_data?: {
        [key: string]: unknown;
    };
    analysis_query_default_service_account?: boolean;
    analyzed_before?: boolean;
    asset_id?: string;
    asset_link?: string;
    collection_id?: string;
    create_transcription?: boolean;
    delete_old_transcriptions?: boolean;
    field_names: Array<string>;
    force_transcoder?: string;
    google_cloud_video_intelligence?: boolean;
    input?: InputSchema;
    job_id?: string;
    job_steps?: Array<JobStepSchema>;
    language?: string | null;
    media_info?: string | null;
    overwrite?: boolean;
    parent_job_id?: string | null;
    priority?: number;
    speakers?: number | null;
    thumbnail?: Array<ThumbnailJob>;
    transcode?: Array<TranscodeJob>;
    valid_transcoders?: Array<Transcoders>;
    version_id?: string;
    view_id: string;
};

export type ListObjectsSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type LocalStorageFileTranscodeJobSchema = {
    asset_id: string;
    checksum?: string | null;
    collection_id?: string | null;
    component_ids?: Array<string>;
    directory_path: string;
    file_id: string;
    file_set_id: string;
    filename: string;
    format_id: string;
    id?: string;
    job_id: string;
    metadata_update_only?: boolean | null;
    priority?: number;
    size: number;
    version_id: string;
};

export type LocalStorageFileTranscodeJobsSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<LocalStorageFileTranscodeJobSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type LocalTranscodeInputSchema = {
    asset_id: string;
    checksum?: string | null;
    closed_captions?: boolean;
    collection_id?: string | null;
    component_ids?: Array<string>;
    directory_path: string;
    endpoint: EndpointSchema;
    engine?: string;
    file_id: string;
    file_set_id: string;
    filename: string;
    format_id: string;
    language?: string;
    original_asset_id?: string | null;
    original_name?: string;
    proxy_id?: string | null;
    size: number;
    storage_id: string;
    update_proxy_mediainfo?: boolean | null;
    version_id: string;
};

export type LocalTranscodeJobSchema = {
    amazon_rekognition?: boolean;
    analysis_data?: {
        [key: string]: unknown;
    };
    analysis_query_default_service_account?: boolean;
    analyzed_before?: boolean;
    asset_id?: string;
    asset_link?: string;
    collection_id?: string;
    create_transcription?: boolean;
    delete_old_transcriptions?: boolean;
    force_transcoder?: string;
    google_cloud_video_intelligence?: boolean;
    input: LocalTranscodeInputSchema;
    job_id?: string;
    job_steps?: Array<JobStepSchema>;
    language?: string | null;
    media_info?: string | null;
    overwrite?: boolean;
    priority?: number;
    speakers?: number | null;
    thumbnail?: Array<ThumbnailJob>;
    transcode?: Array<TranscodeJob>;
    valid_transcoders?: Array<Transcoders>;
    version_id?: string;
};

export type MetadataFillingProposalByAssetQueryParamsSchema = {
    version_id?: string | null;
};

export type MetadataFillingProposalSchema = {
    asset_id?: string;
    date_created?: string;
    errors?: Array<string>;
    field_names?: Array<string>;
    field_values?: unknown;
    job_id?: string;
    parent_job_id?: string | null;
    review_status?: 'ACCEPTED' | 'PENDING_USER' | 'REJECTED';
    user_id?: string;
    version_id?: string | null;
    view_id?: string | null;
    warnings?: Array<string>;
};

export type MetadataFillingResponseSchema = {
    errors?: Array<string>;
    /**
     * Map of field names to generated values. Values can be a string, a list of strings, or an object with 'value' and optional 'label' keys.
     */
    metadata_values?: {
        [key: string]: unknown;
    };
    warnings?: Array<string>;
};

export type MetadataFillingSchema = {
    field_names: Array<string>;
    view_id: string;
};

export type OutputEndpoint = {
    headers?: {
        [key: string]: unknown;
    };
    key: string;
};

export type OutputEndpointSchema = {
    headers?: {
        [key: string]: unknown;
    };
    key: string;
};

export type ReindexQueueRecordSchema = {
    sync_to_another_dc?: boolean;
};

export type SpecifiedKeyframes = {
    url: string;
};

export type SpecifiedKeyframesSchema = {
    url: string;
};

export type ThumbnailJob = {
    height?: number;
    id?: string;
    max_number?: number;
    min_interval?: number;
    output_endpoint: OutputEndpoint;
    set_as_custom_keyframe?: boolean;
    time_end_milliseconds?: number | null;
    time_start_milliseconds?: number | null;
    timestamp?: number;
    width?: number;
};

export type ThumbnailJobSchema = {
    height?: number;
    id?: string;
    max_number?: number;
    min_interval?: number;
    output_endpoint: OutputEndpointSchema;
    set_as_custom_keyframe?: boolean;
    time_end_milliseconds?: number | null;
    time_start_milliseconds?: number | null;
    timestamp?: number;
    width?: number;
};

export type TranscodeEsQueueRecordsSchema = {
    readonly objects?: Array<TranscodeElasticQueueRecord>;
};

export type TranscodeElasticQueueRecord = {
    readonly date_created?: string;
    readonly date_updated?: string;
    readonly id?: string;
    readonly job_id?: string;
    readonly object_id?: string;
    readonly object_type?: string;
    readonly priority?: string;
    readonly queue?: string;
    readonly retry_count?: string;
    readonly status?: string;
    readonly storage_id?: string;
    readonly system_domain_id?: string;
    readonly system_domain_timestamp?: string;
    readonly system_name?: string;
    readonly type?: string;
    readonly user_id?: string;
    readonly version_id?: string;
};

export type TranscodeElasticQueueRecordSchema = {
    readonly date_created?: string;
    readonly date_updated?: string;
    readonly id?: string;
    readonly job_id?: string;
    readonly object_id?: string;
    readonly object_type?: string;
    readonly priority?: string;
    readonly queue?: string;
    readonly retry_count?: string;
    readonly status?: string;
    readonly storage_id?: string;
    readonly system_domain_id?: string;
    readonly system_domain_timestamp?: string;
    readonly system_name?: string;
    readonly type?: string;
    readonly user_id?: string;
    readonly version_id?: string;
};

export type TranscodeJob = {
    height?: number;
    id?: string;
    output_endpoint: OutputEndpoint;
    width?: number;
};

export type TranscodeJobSchema = {
    height?: number;
    id?: string;
    output_endpoint: OutputEndpointSchema;
    width?: number;
};

export type TranscodeQueueObjectSchema = {
    date_created?: string;
    date_updated?: string;
    id?: string;
    job_id?: string;
    priority?: number;
    retry_count?: number;
    status?: string;
    system_domain?: string;
    system_domain_id?: string;
    system_domain_timestamp?: number;
    system_name?: string;
    type?: string;
    user_id?: string;
};

export type TranscodeQueueRecordSchema = {
    bytes_params?: unknown;
    date_created?: string;
    date_updated?: string;
    id?: string;
    job_id?: string | null;
    media_info?: string | null;
    object_id?: string | null;
    object_type?: string | null;
    params?: string | null;
    priority?: number | null;
    retry_count?: number | null;
    spec?: string | null;
    status?: string | null;
    system_domain_id?: string | null;
    system_name?: string;
    transcoder_id?: string | null;
    type?: string | null;
    user_id?: string | null;
    version_id?: string | null;
};

export type TranscodeQueueSchema = {
    facets?: {
        [key: string]: FacetSchema;
    };
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<TranscodeQueueObjectSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type TranscodeValidateMediaInfoSchema = {
    filename?: string;
    media_info: string;
};

export type Transcoders = {
    id?: string;
    name?: string;
    settings?: {
        [key: string]: unknown;
    };
    type?: string;
};

export type TranscodersSchema = {
    id?: string;
    name?: string;
    settings?: {
        [key: string]: unknown;
    };
    type?: string;
};

export type TranscribeSchema = {
    engine?: string | null;
    force?: boolean;
    language?: string | null;
    profile_id?: string;
    speakers?: number | null;
    summary?: boolean | null;
    topics_extraction?: boolean;
    translate_languages?: Array<string> | null;
};

export type WildmokaPipelineTranscode = {
    graph: {
        [key: string]: unknown;
    };
    parameters: {
        [key: string]: unknown;
    };
};

export type WildmokaProtectTranscode = {
    asset_id: string;
    callback_headers: {
        [key: string]: unknown;
    };
    component_type: string;
    container_id: string;
    create_file_callback_payload: {
        [key: string]: unknown;
    };
    create_file_callback_url: string;
    drm: string;
    drm_asset_id: string;
    frame_count: number;
    frame_rate: number;
    has_audio: boolean;
    height: number;
    input_url: string;
    monitor_job_id: string;
    proxy_id: string;
    segment_duration: number;
    update_file_status_callback_url: string;
    watermark: string;
    watermark_id: string | null;
    width: number;
};

export type EdgeTranscodeWorkerSchemaWritable = {
    status: 'ACTIVE' | 'INACTIVE';
    storage_id: string;
};

export type EdgeTranscodeWorkersSchemaWritable = {
    objects?: Array<EdgeTranscodeWorkerSchemaWritable>;
};

export type LocalStorageFileTranscodeJobsSchemaWritable = {
    [key: string]: unknown;
};

export type TranscodeQueueSchemaWritable = {
    facets?: {
        [key: string]: FacetSchema;
    };
};

export type PostAnalyzeAssetsByAssetIdData = {
    /**
     * body
     */
    body?: AnalyzeSchema;
    path: {
        asset_id: string;
    };
    query?: never;
    url: '/v1/analyze/assets/{asset_id}/';
};

export type PostAnalyzeAssetsByAssetIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostAnalyzeAssetsByAssetIdError = PostAnalyzeAssetsByAssetIdErrors[keyof PostAnalyzeAssetsByAssetIdErrors];

export type PostAnalyzeAssetsByAssetIdResponses = {
    /**
     * Returns a definition of the started job
     */
    201: unknown;
};

export type PostAnalyzeAssetsByAssetIdProfilesDefaultData = {
    /**
     * body
     */
    body?: AnalyzeSchema;
    path: {
        asset_id: string;
    };
    query?: never;
    url: '/v1/analyze/assets/{asset_id}/profiles/default/';
};

export type PostAnalyzeAssetsByAssetIdProfilesDefaultErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostAnalyzeAssetsByAssetIdProfilesDefaultError = PostAnalyzeAssetsByAssetIdProfilesDefaultErrors[keyof PostAnalyzeAssetsByAssetIdProfilesDefaultErrors];

export type PostAnalyzeAssetsByAssetIdProfilesDefaultResponses = {
    /**
     * Returns a definition of the started job
     */
    201: unknown;
};

export type PostAnalyzeAssetsByAssetIdProfilesDefaultByMediaTypeData = {
    /**
     * body
     */
    body?: AnalyzeSchema;
    path: {
        asset_id: string;
        media_type: string;
    };
    query?: never;
    url: '/v1/analyze/assets/{asset_id}/profiles/default/{media_type}/';
};

export type PostAnalyzeAssetsByAssetIdProfilesDefaultByMediaTypeErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostAnalyzeAssetsByAssetIdProfilesDefaultByMediaTypeError = PostAnalyzeAssetsByAssetIdProfilesDefaultByMediaTypeErrors[keyof PostAnalyzeAssetsByAssetIdProfilesDefaultByMediaTypeErrors];

export type PostAnalyzeAssetsByAssetIdProfilesDefaultByMediaTypeResponses = {
    /**
     * Returns a definition of the started job
     */
    201: unknown;
};

export type PostAnalyzeAssetsByAssetIdProfilesByProfileIdData = {
    /**
     * body
     */
    body?: AnalyzeSchema;
    path: {
        asset_id: string;
        profile_id: string;
    };
    query?: never;
    url: '/v1/analyze/assets/{asset_id}/profiles/{profile_id}/';
};

export type PostAnalyzeAssetsByAssetIdProfilesByProfileIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostAnalyzeAssetsByAssetIdProfilesByProfileIdError = PostAnalyzeAssetsByAssetIdProfilesByProfileIdErrors[keyof PostAnalyzeAssetsByAssetIdProfilesByProfileIdErrors];

export type PostAnalyzeAssetsByAssetIdProfilesByProfileIdResponses = {
    /**
     * Returns a definition of the started job
     */
    201: unknown;
};

export type PostAnalyzeBulkData = {
    /**
     * body
     */
    body?: BulkAnalyzeSchema;
    path?: never;
    query?: never;
    url: '/v1/analyze/bulk/';
};

export type PostAnalyzeBulkErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Analysis account/profile was not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostAnalyzeBulkError = PostAnalyzeBulkErrors[keyof PostAnalyzeBulkErrors];

export type PostAnalyzeBulkResponses = {
    /**
     * Returns a definition of the started job
     */
    201: unknown;
};

export type PostEdgeTranscodeJobsByJobIdAcknowledgeData = {
    body?: never;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/v1/edge_transcode/jobs/{job_id}/acknowledge/';
};

export type PostEdgeTranscodeJobsByJobIdAcknowledgeErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Edge transcode job doesn't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostEdgeTranscodeJobsByJobIdAcknowledgeError = PostEdgeTranscodeJobsByJobIdAcknowledgeErrors[keyof PostEdgeTranscodeJobsByJobIdAcknowledgeErrors];

export type PostEdgeTranscodeJobsByJobIdAcknowledgeResponses = {
    /**
     * Acknowledge an edge transcode job
     */
    200: unknown;
};

export type GetEdgeTranscodeWorkersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/edge_transcode/workers/';
};

export type GetEdgeTranscodeWorkersErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetEdgeTranscodeWorkersError = GetEdgeTranscodeWorkersErrors[keyof GetEdgeTranscodeWorkersErrors];

export type GetEdgeTranscodeWorkersResponses = {
    /**
     * Returns edge transcode workers
     */
    201: EdgeTranscodeWorkersSchema;
};

export type GetEdgeTranscodeWorkersResponse = GetEdgeTranscodeWorkersResponses[keyof GetEdgeTranscodeWorkersResponses];

export type PostEdgeTranscodeWorkersData = {
    /**
     * body
     */
    body: EdgeTranscodeWorkerSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/edge_transcode/workers/';
};

export type PostEdgeTranscodeWorkersErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostEdgeTranscodeWorkersError = PostEdgeTranscodeWorkersErrors[keyof PostEdgeTranscodeWorkersErrors];

export type PostEdgeTranscodeWorkersResponses = {
    /**
     * Returns an edge transcode worker
     */
    201: EdgeTranscodeWorkerSchema;
};

export type PostEdgeTranscodeWorkersResponse = PostEdgeTranscodeWorkersResponses[keyof PostEdgeTranscodeWorkersResponses];

export type DeleteEdgeTranscodeWorkersByWorkerIdData = {
    body?: never;
    path: {
        worker_id: string;
    };
    query?: never;
    url: '/v1/edge_transcode/workers/{worker_id}/';
};

export type DeleteEdgeTranscodeWorkersByWorkerIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Edge transcode worker doesn't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteEdgeTranscodeWorkersByWorkerIdError = DeleteEdgeTranscodeWorkersByWorkerIdErrors[keyof DeleteEdgeTranscodeWorkersByWorkerIdErrors];

export type DeleteEdgeTranscodeWorkersByWorkerIdResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteEdgeTranscodeWorkersByWorkerIdResponse = DeleteEdgeTranscodeWorkersByWorkerIdResponses[keyof DeleteEdgeTranscodeWorkersByWorkerIdResponses];

export type GetEdgeTranscodeWorkersByWorkerIdData = {
    body?: never;
    path: {
        worker_id: string;
    };
    query?: never;
    url: '/v1/edge_transcode/workers/{worker_id}/';
};

export type GetEdgeTranscodeWorkersByWorkerIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Edge transcode worker doesn't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetEdgeTranscodeWorkersByWorkerIdError = GetEdgeTranscodeWorkersByWorkerIdErrors[keyof GetEdgeTranscodeWorkersByWorkerIdErrors];

export type GetEdgeTranscodeWorkersByWorkerIdResponses = {
    /**
     * Returns a edge transcode worker
     */
    201: EdgeTranscodeWorkerSchema;
};

export type GetEdgeTranscodeWorkersByWorkerIdResponse = GetEdgeTranscodeWorkersByWorkerIdResponses[keyof GetEdgeTranscodeWorkersByWorkerIdResponses];

export type PatchEdgeTranscodeWorkersByWorkerIdData = {
    /**
     * body
     */
    body: EdgeTranscodeWorkerSchemaWritable;
    path: {
        worker_id: string;
    };
    query?: never;
    url: '/v1/edge_transcode/workers/{worker_id}/';
};

export type PatchEdgeTranscodeWorkersByWorkerIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Edge transcode worker doesn't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchEdgeTranscodeWorkersByWorkerIdError = PatchEdgeTranscodeWorkersByWorkerIdErrors[keyof PatchEdgeTranscodeWorkersByWorkerIdErrors];

export type PatchEdgeTranscodeWorkersByWorkerIdResponses = {
    /**
     * Returns a edge transcode worker that was updated
     */
    201: EdgeTranscodeWorkerSchema;
};

export type PatchEdgeTranscodeWorkersByWorkerIdResponse = PatchEdgeTranscodeWorkersByWorkerIdResponses[keyof PatchEdgeTranscodeWorkersByWorkerIdResponses];

export type PutEdgeTranscodeWorkersByWorkerIdData = {
    /**
     * body
     */
    body: EdgeTranscodeWorkerSchemaWritable;
    path: {
        worker_id: string;
    };
    query?: never;
    url: '/v1/edge_transcode/workers/{worker_id}/';
};

export type PutEdgeTranscodeWorkersByWorkerIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Edge transcode worker doesn't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutEdgeTranscodeWorkersByWorkerIdError = PutEdgeTranscodeWorkersByWorkerIdErrors[keyof PutEdgeTranscodeWorkersByWorkerIdErrors];

export type PutEdgeTranscodeWorkersByWorkerIdResponses = {
    /**
     * Returns a edge transcode worker that was updated
     */
    201: EdgeTranscodeWorkerSchema;
};

export type PutEdgeTranscodeWorkersByWorkerIdResponse = PutEdgeTranscodeWorkersByWorkerIdResponses[keyof PutEdgeTranscodeWorkersByWorkerIdResponses];

export type PostKeyframesCollectionsByCollectionIdData = {
    /**
     * body
     */
    body?: GenerateCollectionKeyframeSchema;
    path: {
        collection_id: string;
    };
    query?: never;
    url: '/v1/keyframes/collections/{collection_id}/';
};

export type PostKeyframesCollectionsByCollectionIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostKeyframesCollectionsByCollectionIdError = PostKeyframesCollectionsByCollectionIdErrors[keyof PostKeyframesCollectionsByCollectionIdErrors];

export type PostKeyframesCollectionsByCollectionIdResponses = {
    /**
     * Returns a definiton of the started job
     */
    201: unknown;
};

export type PostKeyframesPlaylistsByPlaylistIdData = {
    /**
     * body
     */
    body?: GenerateCollectionKeyframeSchema;
    path: {
        playlist_id: string;
    };
    query?: never;
    url: '/v1/keyframes/playlists/{playlist_id}/';
};

export type PostKeyframesPlaylistsByPlaylistIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostKeyframesPlaylistsByPlaylistIdError = PostKeyframesPlaylistsByPlaylistIdErrors[keyof PostKeyframesPlaylistsByPlaylistIdErrors];

export type PostKeyframesPlaylistsByPlaylistIdResponses = {
    /**
     * Returns a definiton of the started job
     */
    201: unknown;
};

export type PostMetadataFillingAssetsByAssetIdVersionsByVersionIdData = {
    /**
     * body
     */
    body: MetadataFillingSchema;
    path: {
        asset_id: string;
        version_id: string;
    };
    query?: never;
    url: '/v1/metadata_filling/assets/{asset_id}/versions/{version_id}/';
};

export type PostMetadataFillingAssetsByAssetIdVersionsByVersionIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * AI metadata filling is not enabled for this domain
     */
    403: unknown;
    /**
     * A pending AI metadata review already exists for this asset version
     */
    409: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostMetadataFillingAssetsByAssetIdVersionsByVersionIdError = PostMetadataFillingAssetsByAssetIdVersionsByVersionIdErrors[keyof PostMetadataFillingAssetsByAssetIdVersionsByVersionIdErrors];

export type PostMetadataFillingAssetsByAssetIdVersionsByVersionIdResponses = {
    /**
     * Returns the job status and job ID
     */
    201: unknown;
};

export type PostMetadataFillingBulkData = {
    /**
     * body
     */
    body: BulkMetadataFillingSchema;
    path?: never;
    query?: never;
    url: '/v1/metadata_filling/bulk/';
};

export type PostMetadataFillingBulkErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * AI metadata filling is not enabled for this domain
     */
    403: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostMetadataFillingBulkError = PostMetadataFillingBulkErrors[keyof PostMetadataFillingBulkErrors];

export type PostMetadataFillingBulkResponses = {
    /**
     * Returns the job status and job ID
     */
    201: unknown;
};

export type GetMetadataFillingProposalsAssetsByAssetIdVersionsByVersionIdData = {
    body?: never;
    headers: {
        'User-ID': string;
    };
    path: {
        asset_id: string;
        version_id: string;
    };
    query?: never;
    url: '/v1/metadata_filling/proposals/assets/{asset_id}/versions/{version_id}/';
};

export type GetMetadataFillingProposalsAssetsByAssetIdVersionsByVersionIdErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * No pending proposal owned by the caller for this (asset, version)
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetMetadataFillingProposalsAssetsByAssetIdVersionsByVersionIdError = GetMetadataFillingProposalsAssetsByAssetIdVersionsByVersionIdErrors[keyof GetMetadataFillingProposalsAssetsByAssetIdVersionsByVersionIdErrors];

export type GetMetadataFillingProposalsAssetsByAssetIdVersionsByVersionIdResponses = {
    /**
     * The caller's PENDING_USER proposal for the (asset, version)
     */
    200: unknown;
};

export type GetMetadataFillingProposalsByJobIdData = {
    body?: never;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/v1/metadata_filling/proposals/{job_id}/';
};

export type GetMetadataFillingProposalsByJobIdErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Caller does not own this proposal and is not an admin
     */
    403: unknown;
    /**
     * No proposal found for this job_id
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetMetadataFillingProposalsByJobIdError = GetMetadataFillingProposalsByJobIdErrors[keyof GetMetadataFillingProposalsByJobIdErrors];

export type GetMetadataFillingProposalsByJobIdResponses = {
    /**
     * The stored proposal
     */
    200: unknown;
};

export type PostMetadataFillingProposalsByJobIdAcceptData = {
    body?: never;
    headers: {
        'User-ID': string;
    };
    path: {
        job_id: string;
    };
    query?: never;
    url: '/v1/metadata_filling/proposals/{job_id}/accept/';
};

export type PostMetadataFillingProposalsByJobIdAcceptErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Caller does not own this proposal
     */
    403: unknown;
    /**
     * Proposal not found
     */
    404: unknown;
    /**
     * Proposal is no longer pending review
     */
    409: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostMetadataFillingProposalsByJobIdAcceptError = PostMetadataFillingProposalsByJobIdAcceptErrors[keyof PostMetadataFillingProposalsByJobIdAcceptErrors];

export type PostMetadataFillingProposalsByJobIdAcceptResponses = {
    /**
     * Returns the updated proposal
     */
    200: unknown;
};

export type PostMetadataFillingProposalsByJobIdDiscardData = {
    body?: never;
    headers: {
        'User-ID': string;
    };
    path: {
        job_id: string;
    };
    query?: never;
    url: '/v1/metadata_filling/proposals/{job_id}/discard/';
};

export type PostMetadataFillingProposalsByJobIdDiscardErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Caller does not own this proposal
     */
    403: unknown;
    /**
     * Proposal not found
     */
    404: unknown;
    /**
     * Proposal is no longer pending review
     */
    409: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostMetadataFillingProposalsByJobIdDiscardError = PostMetadataFillingProposalsByJobIdDiscardErrors[keyof PostMetadataFillingProposalsByJobIdDiscardErrors];

export type PostMetadataFillingProposalsByJobIdDiscardResponses = {
    /**
     * Returns the updated proposal
     */
    200: unknown;
};

export type PostMetadataFillingProposalsByJobIdRegenerateData = {
    body?: never;
    headers: {
        'User-ID': string;
    };
    path: {
        job_id: string;
    };
    query?: never;
    url: '/v1/metadata_filling/proposals/{job_id}/regenerate/';
};

export type PostMetadataFillingProposalsByJobIdRegenerateErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Caller does not own this proposal or AI metadata filling is not enabled
     */
    403: unknown;
    /**
     * Proposal not found
     */
    404: unknown;
    /**
     * Proposal is no longer pending review, or another job is already in
     * flight for this asset version
     */
    409: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostMetadataFillingProposalsByJobIdRegenerateError = PostMetadataFillingProposalsByJobIdRegenerateErrors[keyof PostMetadataFillingProposalsByJobIdRegenerateErrors];

export type PostMetadataFillingProposalsByJobIdRegenerateResponses = {
    /**
     * Returns the fresh job_id (status WAITING)
     */
    201: unknown;
};

export type DeleteStoragesByStorageIdData = {
    /**
     * body
     */
    body?: AbortStorageTranscodeJobsSchema;
    path: {
        storage_id: string;
    };
    query?: never;
    url: '/v1/storages/{storage_id}/';
};

export type DeleteStoragesByStorageIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * User does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteStoragesByStorageIdError = DeleteStoragesByStorageIdErrors[keyof DeleteStoragesByStorageIdErrors];

export type DeleteStoragesByStorageIdResponses = {
    /**
     * Successfully scheduled operation
     */
    202: unknown;
};

export type GetStoragesByStorageIdEdgeTranscodeJobsData = {
    body?: never;
    path: {
        storage_id: string;
    };
    query?: {
        /**
         * The max number of items to fetch
         */
        limit?: number;
    };
    url: '/v1/storages/{storage_id}/edge_transcode/jobs/';
};

export type GetStoragesByStorageIdEdgeTranscodeJobsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetStoragesByStorageIdEdgeTranscodeJobsError = GetStoragesByStorageIdEdgeTranscodeJobsErrors[keyof GetStoragesByStorageIdEdgeTranscodeJobsErrors];

export type GetStoragesByStorageIdEdgeTranscodeJobsResponses = {
    /**
     * Returns all analysis service accounts
     */
    200: EdgeTranscodeJobsSchema;
};

export type GetStoragesByStorageIdEdgeTranscodeJobsResponse = GetStoragesByStorageIdEdgeTranscodeJobsResponses[keyof GetStoragesByStorageIdEdgeTranscodeJobsResponses];

export type DeleteStoragesByStorageIdFilesByFileIdTranscodeData = {
    body?: never;
    path: {
        storage_id: string;
        file_id: string;
    };
    query?: never;
    url: '/v1/storages/{storage_id}/files/{file_id}/transcode/';
};

export type DeleteStoragesByStorageIdFilesByFileIdTranscodeErrors = {
    /**
     * Transcode job does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteStoragesByStorageIdFilesByFileIdTranscodeError = DeleteStoragesByStorageIdFilesByFileIdTranscodeErrors[keyof DeleteStoragesByStorageIdFilesByFileIdTranscodeErrors];

export type DeleteStoragesByStorageIdFilesByFileIdTranscodeResponses = {
    /**
     * Transcode job was deleted
     */
    204: void;
};

export type DeleteStoragesByStorageIdFilesByFileIdTranscodeResponse = DeleteStoragesByStorageIdFilesByFileIdTranscodeResponses[keyof DeleteStoragesByStorageIdFilesByFileIdTranscodeResponses];

export type GetStoragesByStorageIdTranscodeData = {
    body?: never;
    path: {
        storage_id: string;
    };
    query?: {
        /**
         * The number of items for each page
         */
        per_page?: number;
        /**
         * ID of a last transcode job entity on previous page
         */
        last_id?: string;
    };
    url: '/v1/storages/{storage_id}/transcode/';
};

export type GetStoragesByStorageIdTranscodeErrors = {
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetStoragesByStorageIdTranscodeError = GetStoragesByStorageIdTranscodeErrors[keyof GetStoragesByStorageIdTranscodeErrors];

export type GetStoragesByStorageIdTranscodeResponses = {
    /**
     * Returns pending transcode jobs to be handled
     */
    200: LocalStorageFileTranscodeJobsSchema;
};

export type GetStoragesByStorageIdTranscodeResponse = GetStoragesByStorageIdTranscodeResponses[keyof GetStoragesByStorageIdTranscodeResponses];

export type DeleteStoragesByStorageIdTranscodeByRecordIdData = {
    body?: never;
    path: {
        storage_id: string;
        record_id: string;
    };
    query?: never;
    url: '/v1/storages/{storage_id}/transcode/{record_id}/';
};

export type DeleteStoragesByStorageIdTranscodeByRecordIdErrors = {
    /**
     * Transcode job does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteStoragesByStorageIdTranscodeByRecordIdError = DeleteStoragesByStorageIdTranscodeByRecordIdErrors[keyof DeleteStoragesByStorageIdTranscodeByRecordIdErrors];

export type DeleteStoragesByStorageIdTranscodeByRecordIdResponses = {
    /**
     * Transcode job was deleted
     */
    204: void;
};

export type DeleteStoragesByStorageIdTranscodeByRecordIdResponse = DeleteStoragesByStorageIdTranscodeByRecordIdResponses[keyof DeleteStoragesByStorageIdTranscodeByRecordIdResponses];

export type GetStoragesByStorageIdTranscodeByRecordIdData = {
    body?: never;
    path: {
        storage_id: string;
        record_id: string;
    };
    query?: never;
    url: '/v1/storages/{storage_id}/transcode/{record_id}/';
};

export type GetStoragesByStorageIdTranscodeByRecordIdErrors = {
    /**
     * Transcode job does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetStoragesByStorageIdTranscodeByRecordIdError = GetStoragesByStorageIdTranscodeByRecordIdErrors[keyof GetStoragesByStorageIdTranscodeByRecordIdErrors];

export type GetStoragesByStorageIdTranscodeByRecordIdResponses = {
    /**
     * Returns pending transcode job to be handled
     */
    200: LocalStorageFileTranscodeJobSchema;
};

export type GetStoragesByStorageIdTranscodeByRecordIdResponse = GetStoragesByStorageIdTranscodeByRecordIdResponses[keyof GetStoragesByStorageIdTranscodeByRecordIdResponses];

export type PostTranscodeData = {
    /**
     * body
     */
    body: JobSchema;
    path?: never;
    query?: never;
    url: '/v1/transcode/';
};

export type PostTranscodeErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostTranscodeError = PostTranscodeErrors[keyof PostTranscodeErrors];

export type PostTranscodeResponses = {
    /**
     * Returns a definiton of the started job
     */
    201: JobSchema;
};

export type PostTranscodeResponse = PostTranscodeResponses[keyof PostTranscodeResponses];

export type GetTranscodeQueueData = {
    body?: never;
    path?: never;
    query?: {
        per_page?: number;
        page?: number;
        /**
         * A comma separated list of fieldnames without spaces. object_type,user_id,retry_count,priority,type,status
         */
        sort?: string;
    };
    url: '/v1/transcode/queue/';
};

export type GetTranscodeQueueErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetTranscodeQueueError = GetTranscodeQueueErrors[keyof GetTranscodeQueueErrors];

export type GetTranscodeQueueResponses = {
    /**
     * Returns the status of all ongoing transcode jobs
     */
    200: TranscodeQueueSchema;
};

export type GetTranscodeQueueResponse = GetTranscodeQueueResponses[keyof GetTranscodeQueueResponses];

export type GetTranscodeQueueSystemData = {
    body?: never;
    path?: never;
    query?: {
        per_domain_id?: boolean;
        per_page?: number;
        page?: number;
        sort?: string;
    };
    url: '/v1/transcode/queue/system/';
};

export type GetTranscodeQueueSystemErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetTranscodeQueueSystemError = GetTranscodeQueueSystemErrors[keyof GetTranscodeQueueSystemErrors];

export type GetTranscodeQueueSystemResponses = {
    /**
     * Returns the status of all ongoing transcode job queues for all domains
     */
    200: TranscodeQueueSchema;
};

export type GetTranscodeQueueSystemResponse = GetTranscodeQueueSystemResponses[keyof GetTranscodeQueueSystemResponses];

export type GetTranscodeByObjectTypeByObjectIdData = {
    body?: never;
    path: {
        object_type: string;
        object_id: string;
    };
    query?: never;
    url: '/v1/transcode/{object_type}/{object_id}/';
};

export type GetTranscodeByObjectTypeByObjectIdErrors = {
    /**
     * Bad request - malformed parameters
     */
    400: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetTranscodeByObjectTypeByObjectIdError = GetTranscodeByObjectTypeByObjectIdErrors[keyof GetTranscodeByObjectTypeByObjectIdErrors];

export type GetTranscodeByObjectTypeByObjectIdResponses = {
    /**
     * Returns list of transcode queue records
     */
    200: TranscodeEsQueueRecordsSchema;
};

export type GetTranscodeByObjectTypeByObjectIdResponse = GetTranscodeByObjectTypeByObjectIdResponses[keyof GetTranscodeByObjectTypeByObjectIdResponses];

export type GetTranscodeByObjectTypeByObjectIdVersionsByVersionIdData = {
    body?: never;
    path: {
        object_type: string;
        object_id: string;
        version_id: string;
    };
    query?: never;
    url: '/v1/transcode/{object_type}/{object_id}/versions/{version_id}/';
};

export type GetTranscodeByObjectTypeByObjectIdVersionsByVersionIdErrors = {
    /**
     * Bad request - malformed parameters
     */
    400: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetTranscodeByObjectTypeByObjectIdVersionsByVersionIdError = GetTranscodeByObjectTypeByObjectIdVersionsByVersionIdErrors[keyof GetTranscodeByObjectTypeByObjectIdVersionsByVersionIdErrors];

export type GetTranscodeByObjectTypeByObjectIdVersionsByVersionIdResponses = {
    /**
     * Returns list of transcode queue records
     */
    200: TranscodeEsQueueRecordsSchema;
};

export type GetTranscodeByObjectTypeByObjectIdVersionsByVersionIdResponse = GetTranscodeByObjectTypeByObjectIdVersionsByVersionIdResponses[keyof GetTranscodeByObjectTypeByObjectIdVersionsByVersionIdResponses];

export type DeleteTranscodeByTranscodeJobIdData = {
    body?: never;
    path: {
        transcode_job_id: string;
    };
    query?: never;
    url: '/v1/transcode/{transcode_job_id}/';
};

export type DeleteTranscodeByTranscodeJobIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Transcode does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteTranscodeByTranscodeJobIdError = DeleteTranscodeByTranscodeJobIdErrors[keyof DeleteTranscodeByTranscodeJobIdErrors];

export type DeleteTranscodeByTranscodeJobIdResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteTranscodeByTranscodeJobIdResponse = DeleteTranscodeByTranscodeJobIdResponses[keyof DeleteTranscodeByTranscodeJobIdResponses];

export type GetTranscodeByTranscodeJobIdData = {
    body?: never;
    path: {
        transcode_job_id: string;
    };
    query?: never;
    url: '/v1/transcode/{transcode_job_id}/';
};

export type GetTranscodeByTranscodeJobIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetTranscodeByTranscodeJobIdError = GetTranscodeByTranscodeJobIdErrors[keyof GetTranscodeByTranscodeJobIdErrors];

export type GetTranscodeByTranscodeJobIdResponses = {
    /**
     * Returns the status of a particular transcode job
     */
    200: JobSchema;
};

export type GetTranscodeByTranscodeJobIdResponse = GetTranscodeByTranscodeJobIdResponses[keyof GetTranscodeByTranscodeJobIdResponses];

export type PostTranscodeByTranscodeJobIdPositionByPositionData = {
    body?: never;
    path: {
        transcode_job_id: string;
        /**
         * move transcode job to "top" or "bottom" position
         */
        position: string;
    };
    query?: never;
    url: '/v1/transcode/{transcode_job_id}/position/{position}/';
};

export type PostTranscodeByTranscodeJobIdPositionByPositionErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Transcode does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostTranscodeByTranscodeJobIdPositionByPositionError = PostTranscodeByTranscodeJobIdPositionByPositionErrors[keyof PostTranscodeByTranscodeJobIdPositionByPositionErrors];

export type PostTranscodeByTranscodeJobIdPositionByPositionResponses = {
    /**
     * Without body
     */
    200: unknown;
};

export type PutTranscodeByTranscodeJobIdPriorityByPriorityData = {
    body?: never;
    path: {
        transcode_job_id: string;
        priority: number;
    };
    query?: never;
    url: '/v1/transcode/{transcode_job_id}/priority/{priority}/';
};

export type PutTranscodeByTranscodeJobIdPriorityByPriorityErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Transcode does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutTranscodeByTranscodeJobIdPriorityByPriorityError = PutTranscodeByTranscodeJobIdPriorityByPriorityErrors[keyof PutTranscodeByTranscodeJobIdPriorityByPriorityErrors];

export type PutTranscodeByTranscodeJobIdPriorityByPriorityResponses = {
    /**
     * Without body
     */
    200: unknown;
};

export type PostTranscribeAssetsByAssetIdProfilesDefaultData = {
    /**
     * body
     */
    body?: TranscribeSchema;
    path: {
        asset_id: string;
    };
    query?: never;
    url: '/v1/transcribe/assets/{asset_id}/profiles/default/';
};

export type PostTranscribeAssetsByAssetIdProfilesDefaultErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostTranscribeAssetsByAssetIdProfilesDefaultError = PostTranscribeAssetsByAssetIdProfilesDefaultErrors[keyof PostTranscribeAssetsByAssetIdProfilesDefaultErrors];

export type PostTranscribeAssetsByAssetIdProfilesDefaultResponses = {
    /**
     * Returns a definition of the started job
     */
    201: unknown;
};

export type PostTranscribeBulkData = {
    /**
     * body
     */
    body: BulkTranscribeSchema;
    path?: never;
    query?: never;
    url: '/v1/transcribe/bulk/';
};

export type PostTranscribeBulkErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostTranscribeBulkError = PostTranscribeBulkErrors[keyof PostTranscribeBulkErrors];

export type PostTranscribeBulkResponses = {
    /**
     * Returns a definition of the started job
     */
    201: unknown;
};
