// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from '../_base/client/index.js';
import type { DeleteWebhooksByWebhookIdData, DeleteWebhooksByWebhookIdErrors, DeleteWebhooksByWebhookIdResponses, GetWebhooksByWebhookIdData, GetWebhooksByWebhookIdErrors, GetWebhooksByWebhookIdResponses, GetWebhooksData, GetWebhooksErrors, GetWebhooksResponses, PostWebhooksData, PostWebhooksErrors, PostWebhooksResponses, PutWebhooksByWebhookIdData, PutWebhooksByWebhookIdErrors, PutWebhooksByWebhookIdResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get all webhooks
 *
 *
 * Required roles:
 * - can_read_webhooks
 *
 */
export const getWebhooks = <ThrowOnError extends boolean = false>(options?: Options<GetWebhooksData, ThrowOnError>): RequestResult<GetWebhooksResponses, GetWebhooksErrors, ThrowOnError> => (options?.client ?? client).get<GetWebhooksResponses, GetWebhooksErrors, ThrowOnError>({
    security: [{ name: 'App-ID', type: 'apiKey' }, { name: 'Auth-Token', type: 'apiKey' }],
    url: '/v1/webhooks/',
    ...options
});

/**
 * Create a new webhook
 *
 *
 * Required roles:
 * - can_write_webhooks
 *
 */
export const postWebhooks = <ThrowOnError extends boolean = false>(options: Options<PostWebhooksData, ThrowOnError>): RequestResult<PostWebhooksResponses, PostWebhooksErrors, ThrowOnError> => (options.client ?? client).post<PostWebhooksResponses, PostWebhooksErrors, ThrowOnError>({
    security: [{ name: 'App-ID', type: 'apiKey' }, { name: 'Auth-Token', type: 'apiKey' }],
    url: '/v1/webhooks/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a webhook
 *
 *
 * Required roles:
 * - can_delete_webhooks
 *
 */
export const deleteWebhooksByWebhookId = <ThrowOnError extends boolean = false>(options: Options<DeleteWebhooksByWebhookIdData, ThrowOnError>): RequestResult<DeleteWebhooksByWebhookIdResponses, DeleteWebhooksByWebhookIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteWebhooksByWebhookIdResponses, DeleteWebhooksByWebhookIdErrors, ThrowOnError>({
    security: [{ name: 'App-ID', type: 'apiKey' }, { name: 'Auth-Token', type: 'apiKey' }],
    url: '/v1/webhooks/{webhook_id}/',
    ...options
});

/**
 * Get a webhook definition
 *
 *
 * Required roles:
 * - can_read_webhooks
 *
 */
export const getWebhooksByWebhookId = <ThrowOnError extends boolean = false>(options: Options<GetWebhooksByWebhookIdData, ThrowOnError>): RequestResult<GetWebhooksByWebhookIdResponses, GetWebhooksByWebhookIdErrors, ThrowOnError> => (options.client ?? client).get<GetWebhooksByWebhookIdResponses, GetWebhooksByWebhookIdErrors, ThrowOnError>({
    security: [{ name: 'App-ID', type: 'apiKey' }, { name: 'Auth-Token', type: 'apiKey' }],
    url: '/v1/webhooks/{webhook_id}/',
    ...options
});

/**
 * Update a webhook
 *
 *
 * Required roles:
 * - can_write_webhooks
 *
 */
export const putWebhooksByWebhookId = <ThrowOnError extends boolean = false>(options: Options<PutWebhooksByWebhookIdData, ThrowOnError>): RequestResult<PutWebhooksByWebhookIdResponses, PutWebhooksByWebhookIdErrors, ThrowOnError> => (options.client ?? client).put<PutWebhooksByWebhookIdResponses, PutWebhooksByWebhookIdErrors, ThrowOnError>({
    security: [{ name: 'App-ID', type: 'apiKey' }, { name: 'Auth-Token', type: 'apiKey' }],
    url: '/v1/webhooks/{webhook_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
