// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/API/jobs/` | (string & {});
};

export type ActionContextSchema = {
    ABORT?: ActionContextValue;
    CHANGE_PRIORITY?: ActionContextValue;
    PAUSE?: ActionContextValue;
    RESTART?: ActionContextValue;
    RESUME?: ActionContextValue;
};

export type ActionContextValue = {
    bulk?: boolean;
    url?: string;
};

export type ActionContextValueSchema = {
    bulk?: boolean;
    url?: string;
};

export type BaseQueryParamsSchema = {
    /**
     * Which page number to fetch
     */
    page?: number | null;
    /**
     * The number of items for each page
     */
    per_page?: number | null;
    /**
     * A comma separated list of fieldnames with order (asc/desc)
     */
    sort?: string;
};

export type BulkJobCreatedSchema = {
    job_id?: string;
};

export type JobBaseSchema = {
    action_context?: ActionContextSchema;
    readonly children_progress?: {
        [key: string]: JobChildProgressSchema;
    };
    completed_at?: string;
    custom_type?: string | null;
    readonly date_created?: string;
    readonly date_modified?: string;
    error_message?: string;
    has_children?: boolean;
    readonly id?: string;
    message?: string;
    object_id?: string | null;
    object_type?: string | null;
    parent_id?: string | null;
    readonly priority?: number;
    readonly progress?: number;
    progress_processed?: number;
    progress_total?: number;
    related_objects?: Array<RelatedObject>;
    started_at?: string;
    status: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
    title: string;
    type: 'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER';
};

export type JobChildProgressSchema = {
    progress_processed?: number;
    progress_total?: number;
    status?: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
};

export type JobCreateSchema = {
    action_context?: ActionContextSchema;
    readonly children_progress?: {
        [key: string]: JobChildProgressSchema;
    };
    completed_at?: string;
    created_by?: string;
    custom_type?: string | null;
    readonly date_created?: string;
    readonly date_modified?: string;
    error_message?: string;
    has_children?: boolean;
    id?: string | null;
    message?: string;
    object_id?: string | null;
    object_type?: string | null;
    parent_id?: string | null;
    readonly priority?: number;
    readonly progress?: number;
    progress_processed?: number;
    progress_total?: number;
    related_objects?: Array<RelatedObject>;
    started_at?: string;
    status: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
    steps?: Array<JobStep>;
    title: string;
    type: 'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER';
};

export type JobElasticSchema = {
    action_context?: ActionContextSchema;
    readonly children_progress?: {
        [key: string]: JobChildProgressSchema;
    };
    completed_at?: string;
    readonly created_by?: string;
    custom_type?: string | null;
    readonly date_created?: string;
    readonly date_modified?: string;
    error_message?: string;
    has_children?: boolean;
    readonly id?: string;
    message?: string;
    object_id?: string | null;
    object_type?: string | null;
    parent_id?: string | null;
    readonly priority?: number;
    readonly progress?: number;
    progress_processed?: number;
    progress_total?: number;
    related_objects?: Array<RelatedObject>;
    started_at?: string;
    status: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
    readonly steps?: Array<JobStepElastic>;
    readonly storage_id?: string;
    title: string;
    type: 'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER';
};

export type JobSchema = {
    action_context?: ActionContextSchema;
    readonly children_progress?: {
        [key: string]: JobChildProgressSchema;
    };
    completed_at?: string;
    readonly created_by?: string;
    custom_type?: string | null;
    readonly date_created?: string;
    readonly date_modified?: string;
    error_message?: string;
    has_children?: boolean;
    readonly id?: string;
    message?: string;
    object_id?: string | null;
    object_type?: string | null;
    parent_id?: string | null;
    readonly priority?: number;
    readonly progress?: number;
    progress_processed?: number;
    progress_total?: number;
    related_objects?: Array<RelatedObject>;
    started_at?: string;
    status: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
    steps?: Array<JobStep>;
    title: string;
    type: 'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER';
};

export type JobStep = {
    readonly date_updated?: string;
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status: 'DONE' | 'FAILED' | 'IN_PROGRESS' | 'SKIPPED' | 'WAITING';
};

export type JobStepElastic = {
    readonly date_updated?: string;
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status?: string;
};

export type JobStepElasticSchema = {
    readonly date_updated?: string;
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status?: string;
};

export type JobStepSchema = {
    readonly date_updated?: string;
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status: 'DONE' | 'FAILED' | 'IN_PROGRESS' | 'SKIPPED' | 'WAITING';
};

export type JobStepUpdateBulkSchema = {
    readonly date_updated?: string;
    error_message?: string | null;
    id: string;
    label: string;
    message?: string | null;
    status: 'DONE' | 'FAILED' | 'IN_PROGRESS' | 'SKIPPED' | 'WAITING';
};

export type JobStepUpdateSchema = {
    readonly date_updated?: string;
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status: 'DONE' | 'FAILED' | 'IN_PROGRESS' | 'SKIPPED' | 'WAITING';
};

export type JobStepsSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<JobStepSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly scroll_id?: string;
    readonly total?: number;
};

export type JobStepsUpdateSchema = {
    steps: Array<JobStepUpdateBulkSchema>;
};

export type JobsBulkActionSchema = {
    job_ids: Array<string>;
};

export type JobsBulkDeleteParamsSchema = {
    _exists_?: Array<string>;
    _missing_?: Array<string>;
    created_by?: Array<string>;
    date_created?: string;
    date_modified?: string;
    ids?: Array<string>;
    'metadata.automation_id'?: string;
    object_id?: string;
    parent_id?: string;
    query?: string;
    status?: Array<'ABORTED' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'SKIPPED'>;
    type?: Array<'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER'>;
};

export type JobsBulkDeleteSchema = {
    job_ids?: Array<string>;
};

export type JobsBulkEditParamsSchema = {
    _exists_?: Array<string>;
    _missing_?: Array<string>;
    created_by?: Array<string>;
    date_created?: string;
    date_modified?: string;
    ids?: Array<string>;
    merge_metadata?: boolean;
    'metadata.automation_id'?: string;
    object_id?: string;
    parent_id?: string;
    query?: string;
    status?: Array<'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING'>;
    type?: Array<'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER'>;
};

export type JobsBulkEditSchema = {
    error_message?: string;
    job_context?: {
        [key: string]: unknown;
    };
    message?: string;
    metadata?: {
        [key: string]: unknown;
    };
    status?: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
};

export type JobsBulkParamsSchema = {
    _exists_?: Array<string>;
    _missing_?: Array<string>;
    created_by?: Array<string>;
    date_created?: string;
    date_modified?: string;
    ids?: Array<string>;
    'metadata.automation_id'?: string;
    object_id?: string;
    parent_id?: string;
    query?: string;
    type?: Array<'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER'>;
};

export type JobsPrioritySchema = {
    job_ids: Array<string>;
    priority: number;
};

export type JobsQueryParamsSchema = {
    /**
     * Which page number to fetch
     */
    page?: number | null;
    /**
     * The number of items for each page
     */
    per_page?: number | null;
    scroll?: boolean;
    scroll_id?: string;
    /**
     * A comma separated list of fieldnames with order (asc/desc)
     */
    sort?: string;
};

export type JobsSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<JobElasticSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly scroll_id?: string;
    readonly total?: number;
};

export type JobsStateSchema = {
    action: 'ABORT' | 'PAUSE' | 'RESTART' | 'RESUME';
    job_ids: Array<string>;
};

export type ListObjectsSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly scroll_id?: string;
    readonly total?: number;
};

export type ReindexJobSchema = {
    sync_to_another_dc?: boolean;
};

export type RelatedObject = {
    object_id: string;
    object_type: string;
};

export type RelatedObjectSchema = {
    object_id: string;
    object_type: string;
};

export type JobBaseSchemaWritable = {
    action_context?: ActionContextSchema;
    completed_at?: string;
    custom_type?: string | null;
    error_message?: string;
    has_children?: boolean;
    message?: string;
    object_id?: string | null;
    object_type?: string | null;
    parent_id?: string | null;
    progress_processed?: number;
    progress_total?: number;
    related_objects?: Array<RelatedObject>;
    started_at?: string;
    status: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
    title: string;
    type: 'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER';
};

export type JobCreateSchemaWritable = {
    action_context?: ActionContextSchema;
    completed_at?: string;
    created_by?: string;
    custom_type?: string | null;
    error_message?: string;
    has_children?: boolean;
    id?: string | null;
    message?: string;
    object_id?: string | null;
    object_type?: string | null;
    parent_id?: string | null;
    progress_processed?: number;
    progress_total?: number;
    related_objects?: Array<RelatedObject>;
    started_at?: string;
    status: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
    steps?: Array<JobStepWritable>;
    title: string;
    type: 'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER';
};

export type JobElasticSchemaWritable = {
    action_context?: ActionContextSchema;
    completed_at?: string;
    custom_type?: string | null;
    error_message?: string;
    has_children?: boolean;
    message?: string;
    object_id?: string | null;
    object_type?: string | null;
    parent_id?: string | null;
    progress_processed?: number;
    progress_total?: number;
    related_objects?: Array<RelatedObject>;
    started_at?: string;
    status: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
    title: string;
    type: 'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER';
};

export type JobSchemaWritable = {
    action_context?: ActionContextSchema;
    completed_at?: string;
    custom_type?: string | null;
    error_message?: string;
    has_children?: boolean;
    message?: string;
    object_id?: string | null;
    object_type?: string | null;
    parent_id?: string | null;
    progress_processed?: number;
    progress_total?: number;
    related_objects?: Array<RelatedObject>;
    started_at?: string;
    status: 'ABORTED' | 'ABORT_PENDING' | 'DISCARDED' | 'FAILED' | 'FINISHED' | 'FINISHED_WITH_WARNING' | 'PAUSED' | 'PENDING_USER' | 'READY' | 'SKIPPED' | 'STARTED' | 'WAITING';
    steps?: Array<JobStepWritable>;
    title: string;
    type: 'ACL' | 'ANALYZE' | 'ARCHIVE' | 'AUTOMATION' | 'CHANGE_PERSON' | 'COLLECTION_CUSTOM_ORDER' | 'CONFIRM_PERSON' | 'CONVERT_SAVED_SEARCH_TO_COLLECTION' | 'COPY' | 'CUSTOM' | 'DELETE' | 'DELETE_JOBS' | 'DELETE_PERSON' | 'EDIT_JOBS' | 'EXPORT' | 'FACE_RECOGNITION' | 'KEYFRAMES' | 'MARK_MISSING' | 'MEDIAINFO' | 'METADATA' | 'METADATA_FILLING' | 'MOVE' | 'PUBLISH' | 'REINDEX' | 'REQUEST_APPROVAL' | 'REQUEST_COLLECTION_MAP' | 'RESTORE' | 'RESTORE_FROM_GLACIER' | 'REVIEW_REQUEST' | 'SCAN' | 'SET_APPROVAL' | 'STORAGE_GATEWAY_FILE_INGEST' | 'TRANSCODE' | 'TRANSCRIPTION' | 'TRANSFER';
};

export type JobStepWritable = {
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status: 'DONE' | 'FAILED' | 'IN_PROGRESS' | 'SKIPPED' | 'WAITING';
};

export type JobStepElasticWritable = {
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status?: string;
};

export type JobStepElasticSchemaWritable = {
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status?: string;
};

export type JobStepSchemaWritable = {
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status: 'DONE' | 'FAILED' | 'IN_PROGRESS' | 'SKIPPED' | 'WAITING';
};

export type JobStepUpdateBulkSchemaWritable = {
    error_message?: string | null;
    id: string;
    label: string;
    message?: string | null;
    status: 'DONE' | 'FAILED' | 'IN_PROGRESS' | 'SKIPPED' | 'WAITING';
};

export type JobStepUpdateSchemaWritable = {
    error_message?: string | null;
    id?: string;
    label: string;
    message?: string | null;
    status: 'DONE' | 'FAILED' | 'IN_PROGRESS' | 'SKIPPED' | 'WAITING';
};

export type JobStepsSchemaWritable = {
    [key: string]: unknown;
};

export type JobStepsUpdateSchemaWritable = {
    steps: Array<JobStepUpdateBulkSchemaWritable>;
};

export type JobsSchemaWritable = {
    [key: string]: unknown;
};

export type DeleteJobsData = {
    /**
     * body
     */
    body?: JobsBulkDeleteSchema;
    path?: never;
    query?: {
        /**
         * Filter by parent_id
         */
        parent_id?: string;
        /**
         * Filter by object_id
         */
        object_id?: string;
        /**
         * Filter by created_by
         */
        created_by?: string;
        /**
         * Filter by job status
         */
        status?: string;
        /**
         * Filter by job types
         */
        type?: string;
        /**
         * Filter by date_created. Can either be a single ISO8601 timestamp or two timestamps separated by a semicolon `;`. The timestamp can also be expressed as number of milliseconds since Jan 1 1970 (epoch). Begin timestamp can also be replaced with an asterisk `*` to make the query open ended.
         * For example: 2018-01-01T10:00:00Z;2018-01-01T15:00:00Z
         */
        date_created?: string;
        /**
         * Filter by date_modified Can either be a single ISO8601 timestamp or two timestamps separated by a semicolon `;`. The timestamp can also be expressed as number of milliseconds since Jan 1 1970 (epoch). Begin timestamp can also be replaced with an asterisk `*` to make the query open ended.
         * For example: *;1544450400
         */
        date_modified?: string;
        /**
         * Filter by any of the above with wildcard support
         */
        query?: string;
        /**
         * Filter list of id:s
         */
        ids?: string;
        /**
         * Gives an ability to retrieve jobs created by a specific automation
         */
        'metadata.automation_id'?: string;
        /**
         * Filter jobs that have no fields specified in _missing_ (comma separated)
         */
        _missing_?: string;
        /**
         * Filter jobs that have all fields specified in _exists_ (comma separated)
         */
        _exists_?: string;
    };
    url: '/v1/jobs/';
};

export type DeleteJobsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteJobsError = DeleteJobsErrors[keyof DeleteJobsErrors];

export type DeleteJobsResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteJobsResponse = DeleteJobsResponses[keyof DeleteJobsResponses];

export type GetJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If facets should be returned
         */
        facets?: boolean;
        /**
         * List of aggregation keys if facets is true
         */
        aggregations?: string;
        /**
         * Which page number to fetch
         */
        page?: number;
        /**
         * The number of items for each page
         */
        per_page?: number;
        /**
         * If true passed then uses scroll pagination instead of default one
         */
        scroll?: boolean;
        /**
         * In order to get next batch of results using scroll pagination the scroll_id is required
         */
        scroll_id?: string;
        /**
         * A comma separated list of fieldnames with order. For example - first_name,asc;last_name,desc
         */
        sort?: string;
        /**
         * Filter by type
         */
        type?: string;
        /**
         * Filter by object_type
         */
        object_type?: string;
        /**
         * Filter by parent_id
         */
        parent_id?: string;
        /**
         * Filter by object_id
         */
        object_id?: string;
        /**
         * Filter by status
         */
        status?: string;
        /**
         * Filter by created_by
         */
        created_by?: string;
        /**
         * Filter by date_created. Can either be a single ISO8601 timestamp or two timestamps separated by a semicolon `;`. The timestamp can also be expressed as number of milliseconds since Jan 1 1970 (epoch). Either timestamp can also be replaced with an asterisk `*` to make the query open ended.
         * For example: 2018-01-01T10:00:00Z;2018-01-01T15:00:00Z
         */
        date_created?: string;
        /**
         * Filter by date_modified Can either be a single ISO8601 timestamp or two timestamps separated by a semicolon `;`. The timestamp can also be expressed as number of milliseconds since Jan 1 1970 (epoch). Either timestamp can also be replaced with an asterisk `*` to make the query open ended.
         * For example: *;1544450400
         */
        date_modified?: string;
        /**
         * Filter by any of the above with wildcard support
         */
        query?: string;
        /**
         * Filter list of id:s (comma separated)
         */
        ids?: string;
        /**
         * Gives an ability to retrieve jobs created by a specific automation
         */
        'metadata.automation_id'?: string;
        /**
         * Filter jobs by any field inside the metadata object. Any metadata field can be filtered this way by using the pattern metadata.<field>=value.
         * For example: metadata.transcoder_id=xyz
         */
        'metadata.<field>'?: string;
        /**
         * Filter jobs that have no fields specified in _missing_ (comma separated)
         */
        _missing_?: string;
        /**
         * Filter jobs that have all fields specified in _exists_ (comma separated)
         */
        _exists_?: string;
    };
    url: '/v1/jobs/';
};

export type GetJobsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetJobsError = GetJobsErrors[keyof GetJobsErrors];

export type GetJobsResponses = {
    /**
     * Returns a list of jobs
     */
    200: JobsSchema;
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type PatchJobsData = {
    /**
     * body
     */
    body: JobsBulkEditSchema;
    path?: never;
    query?: {
        /**
         * Filter by parent_id
         */
        parent_id?: string;
        /**
         * Filter by object_id
         */
        object_id?: string;
        /**
         * Filter by created_by
         */
        created_by?: string;
        /**
         * Filter by job status
         */
        status?: string;
        /**
         * Filter by job types
         */
        type?: string;
        /**
         * Filter by date_created. Can either be a single ISO8601 timestamp or two timestamps separated by a semicolon `;`. The timestamp can also be expressed as number of milliseconds since Jan 1 1970 (epoch). Begin timestamp can also be replaced with an asterisk `*` to make the query open ended.
         * For example: 2018-01-01T10:00:00Z;2018-01-01T15:00:00Z
         */
        date_created?: string;
        /**
         * Filter by date_modified Can either be a single ISO8601 timestamp or two timestamps separated by a semicolon `;`. The timestamp can also be expressed as number of milliseconds since Jan 1 1970 (epoch). Begin timestamp can also be replaced with an asterisk `*` to make the query open ended.
         * For example: *;1544450400
         */
        date_modified?: string;
        /**
         * Filter by any of the above with wildcard support
         */
        query?: string;
        /**
         * Filter list of id:s
         */
        ids?: string;
        /**
         * Merge metadata in body with existing job metadata
         */
        merge_metadata?: string;
        /**
         * Gives an ability to retrieve jobs created by a specific automation
         */
        'metadata.automation_id'?: string;
        /**
         * Filter jobs that have no fields specified in _missing_ (comma separated)
         */
        _missing_?: string;
        /**
         * Filter jobs that have all fields specified in _exists_ (comma separated)
         */
        _exists_?: string;
    };
    url: '/v1/jobs/';
};

export type PatchJobsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchJobsError = PatchJobsErrors[keyof PatchJobsErrors];

export type PatchJobsResponses = {
    /**
     * edit jobs scheduled
     */
    202: BulkJobCreatedSchema;
};

export type PatchJobsResponse = PatchJobsResponses[keyof PatchJobsResponses];

export type PostJobsData = {
    /**
     * body
     */
    body: JobSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/jobs/';
};

export type PostJobsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostJobsError = PostJobsErrors[keyof PostJobsErrors];

export type PostJobsResponses = {
    /**
     * Returns a created job
     */
    201: JobSchema;
};

export type PostJobsResponse = PostJobsResponses[keyof PostJobsResponses];

export type PutJobsPriorityData = {
    /**
     * body
     */
    body: JobsPrioritySchema;
    path?: never;
    query?: never;
    url: '/v1/jobs/priority/';
};

export type PutJobsPriorityErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutJobsPriorityError = PutJobsPriorityErrors[keyof PutJobsPriorityErrors];

export type PutJobsPriorityResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type PutJobsStateData = {
    /**
     * body
     */
    body: JobsStateSchema;
    path?: never;
    query?: never;
    url: '/v1/jobs/state/';
};

export type PutJobsStateErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutJobsStateError = PutJobsStateErrors[keyof PutJobsStateErrors];

export type PutJobsStateResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type DeleteJobsByJobIdData = {
    body?: never;
    path: {
        job_id: string;
    };
    query?: {
        /**
         * If true, schedule recursive deletion of all child jobs and the job itself asynchronously; the job may remain until background processing completes.
         */
        recursive?: boolean;
    };
    url: '/v1/jobs/{job_id}/';
};

export type DeleteJobsByJobIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Job does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteJobsByJobIdError = DeleteJobsByJobIdErrors[keyof DeleteJobsByJobIdErrors];

export type DeleteJobsByJobIdResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteJobsByJobIdResponse = DeleteJobsByJobIdResponses[keyof DeleteJobsByJobIdResponses];

export type GetJobsByJobIdData = {
    body?: never;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/v1/jobs/{job_id}/';
};

export type GetJobsByJobIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Job does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetJobsByJobIdError = GetJobsByJobIdErrors[keyof GetJobsByJobIdErrors];

export type GetJobsByJobIdResponses = {
    /**
     * Returns a job
     */
    200: JobSchema;
};

export type GetJobsByJobIdResponse = GetJobsByJobIdResponses[keyof GetJobsByJobIdResponses];

export type PatchJobsByJobIdData = {
    /**
     * body
     */
    body: JobSchemaWritable;
    path: {
        job_id: string;
    };
    query?: {
        merge_metadata?: string;
    };
    url: '/v1/jobs/{job_id}/';
};

export type PatchJobsByJobIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchJobsByJobIdError = PatchJobsByJobIdErrors[keyof PatchJobsByJobIdErrors];

export type PatchJobsByJobIdResponses = {
    /**
     * Returns an updated job
     */
    200: JobSchema;
};

export type PatchJobsByJobIdResponse = PatchJobsByJobIdResponses[keyof PatchJobsByJobIdResponses];

export type PutJobsByJobIdData = {
    /**
     * body
     */
    body: JobSchemaWritable;
    path: {
        job_id: string;
    };
    query?: {
        merge_metadata?: string;
    };
    url: '/v1/jobs/{job_id}/';
};

export type PutJobsByJobIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutJobsByJobIdError = PutJobsByJobIdErrors[keyof PutJobsByJobIdErrors];

export type PutJobsByJobIdResponses = {
    /**
     * Returns an updated job
     */
    200: JobSchema;
};

export type PutJobsByJobIdResponse = PutJobsByJobIdResponses[keyof PutJobsByJobIdResponses];

export type PostJobsByJobIdReindexData = {
    /**
     * body
     */
    body: ReindexJobSchema;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/v1/jobs/{job_id}/reindex/';
};

export type PostJobsByJobIdReindexErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostJobsByJobIdReindexError = PostJobsByJobIdReindexErrors[keyof PostJobsByJobIdReindexErrors];

export type PostJobsByJobIdReindexResponses = {
    /**
     * OK
     */
    202: unknown;
};

export type PatchJobsByJobIdStepsData = {
    /**
     * body
     */
    body: JobStepsUpdateSchemaWritable;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/v1/jobs/{job_id}/steps/';
};

export type PatchJobsByJobIdStepsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchJobsByJobIdStepsError = PatchJobsByJobIdStepsErrors[keyof PatchJobsByJobIdStepsErrors];

export type PatchJobsByJobIdStepsResponses = {
    /**
     * Returns an updated job
     */
    200: JobSchema;
};

export type PatchJobsByJobIdStepsResponse = PatchJobsByJobIdStepsResponses[keyof PatchJobsByJobIdStepsResponses];

export type PutJobsByJobIdStepsData = {
    /**
     * body
     */
    body: JobStepsUpdateSchemaWritable;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/v1/jobs/{job_id}/steps/';
};

export type PutJobsByJobIdStepsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutJobsByJobIdStepsError = PutJobsByJobIdStepsErrors[keyof PutJobsByJobIdStepsErrors];

export type PutJobsByJobIdStepsResponses = {
    /**
     * Returns an updated job
     */
    200: JobSchema;
};

export type PutJobsByJobIdStepsResponse = PutJobsByJobIdStepsResponses[keyof PutJobsByJobIdStepsResponses];

export type PatchJobsByJobIdStepsByJobStepIdData = {
    /**
     * body
     */
    body: JobStepSchemaWritable;
    path: {
        job_id: string;
        job_step_id: string;
    };
    query?: never;
    url: '/v1/jobs/{job_id}/steps/{job_step_id}/';
};

export type PatchJobsByJobIdStepsByJobStepIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchJobsByJobIdStepsByJobStepIdError = PatchJobsByJobIdStepsByJobStepIdErrors[keyof PatchJobsByJobIdStepsByJobStepIdErrors];

export type PatchJobsByJobIdStepsByJobStepIdResponses = {
    /**
     * Returns an updated job
     */
    200: JobSchema;
};

export type PatchJobsByJobIdStepsByJobStepIdResponse = PatchJobsByJobIdStepsByJobStepIdResponses[keyof PatchJobsByJobIdStepsByJobStepIdResponses];

export type PutJobsByJobIdStepsByJobStepIdData = {
    /**
     * body
     */
    body: JobStepSchemaWritable;
    path: {
        job_id: string;
        job_step_id: string;
    };
    query?: never;
    url: '/v1/jobs/{job_id}/steps/{job_step_id}/';
};

export type PutJobsByJobIdStepsByJobStepIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutJobsByJobIdStepsByJobStepIdError = PutJobsByJobIdStepsByJobStepIdErrors[keyof PutJobsByJobIdStepsByJobStepIdErrors];

export type PutJobsByJobIdStepsByJobStepIdResponses = {
    /**
     * Returns an updated job
     */
    200: JobSchema;
};

export type PutJobsByJobIdStepsByJobStepIdResponse = PutJobsByJobIdStepsByJobStepIdResponses[keyof PutJobsByJobIdStepsByJobStepIdResponses];
