// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/API/settings/` | (string & {});
};

export type AllowedIpSchema = {
    app_id?: string | null;
    ip?: string | null;
};

export type CorsHostSchema = {
    host: string;
    readonly id?: string | null;
};

export type CorsHostsSchema = {
    readonly objects?: Array<CorsHostSchema> | null;
};

export type DashboardCollectionsTreeSchema = {
    visible?: boolean | null;
};

export type DashboardCommentsFeedSchema = {
    visible?: boolean | null;
};

export type DashboardHeaderSchema = {
    expanded?: boolean | null;
};

export type DashboardSchema = {
    collections_tree?: DashboardCollectionsTreeSchema | null;
    comments_feed?: DashboardCommentsFeedSchema | null;
    header?: DashboardHeaderSchema | null;
    view_type?: DashboardSchemaViewType | null;
    widgets?: Array<DashboardWidget> | null;
};

export type DashboardSchemaViewType = 'card' | 'list';

export type DashboardWidget = {
    expanded?: boolean | null;
    id?: string | null;
    visible?: boolean | null;
};

export type DashboardWidgetSchema = {
    expanded?: boolean | null;
    id?: string | null;
    visible?: boolean | null;
};

export type DefaultShareOptionsTypeSchema = {
    allow_approving_comments?: boolean | null;
    allow_comments?: boolean | null;
    allow_custom_actions?: boolean | null;
    allow_download?: boolean | null;
    allow_download_proxy?: boolean | null;
    allow_setting_approve_status?: boolean | null;
    allow_upload?: boolean | null;
    allow_view_transcriptions?: boolean | null;
    allow_view_versions?: boolean | null;
    can_change_allow_approving_comments?: boolean | null;
    can_change_allow_comments?: boolean | null;
    can_change_allow_custom_actions?: boolean | null;
    can_change_allow_download?: boolean | null;
    can_change_allow_download_proxy?: boolean | null;
    can_change_allow_setting_approve_status?: boolean | null;
    can_change_allow_upload?: boolean | null;
    can_change_allow_view_transcriptions?: boolean | null;
    can_change_allow_view_versions?: boolean | null;
    can_change_search_users_from_share?: boolean | null;
    can_change_share_expiration_time?: boolean | null;
    can_change_show_existing_comments?: boolean | null;
    can_change_show_watermark?: boolean | null;
    require_password?: boolean | null;
    show_existing_comments?: boolean | null;
    show_watermark?: boolean | null;
};

export type FacetFieldSchema = {
    name: string;
};

export type GlobalSettingsSchema = {
    debug?: boolean | null;
    log_level?: GlobalSettingsSchemaLogLevel | null;
};

export type GlobalSettingsSchemaLogLevel = 'CRITICAL' | 'DEBUG' | 'ERROR' | 'INFO' | 'NOTSET' | 'WARNING';

export type GroupSettingPublicSchema = {
    acl_template_id?: string | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    readonly client_ip?: string | null;
    collections_get_parent_acls?: boolean | null;
    date_format?: string | null;
    datetime_format?: string | null;
    default_upload_storage_id?: string | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    filters_default_metadata_view_id?: string | null;
    readonly group_id?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    jobs_dashboard?: JobsDashboard | null;
    logo_storage_id?: string | null;
    readonly logo_url?: string | null;
    required_metadata_views?: Array<string> | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayField> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_view_id?: string | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    readonly system_domain_id?: string | null;
    use_asset_name_on_download?: boolean | null;
};

export type GroupSettingSchema = {
    readonly group_id?: string | null;
    logo_storage_id?: string | null;
    logo_url?: string | null;
    readonly system_domain_id?: string | null;
};

export type GroupSettingsIdSchema = {
    object_ids: Array<string>;
};

export type JobsDashboard = {
    widgets?: Array<JobsDashboardWidget> | null;
};

export type JobsDashboardSchema = {
    widgets?: Array<JobsDashboardWidget> | null;
};

export type JobsDashboardWidget = {
    id?: string | null;
    options?: JobsWidgetOption | null;
    title?: string | null;
    type?: JobsDashboardWidgetType | null;
};

export type JobsDashboardWidgetSchema = {
    id?: string | null;
    options?: JobsWidgetOption | null;
    title?: string | null;
    type?: JobsDashboardWidgetSchemaType | null;
};

export type JobsDashboardWidgetSchemaType = 'JOBS_LIST' | 'JOBS_STATS_LIST';

export type JobsDashboardWidgetType = 'JOBS_LIST' | 'JOBS_STATS_LIST';

export type JobsWidgetOption = {
    columns?: Array<string> | null;
    filters?: {
        [key: string]: unknown;
    } | null;
    limit?: number | null;
    sort?: Array<Sort> | null;
};

export type JobsWidgetOptionFilterSchema = {
    name?: string | null;
    value?: Array<string> | null;
};

export type JobsWidgetOptionSchema = {
    columns?: Array<string> | null;
    filters?: {
        [key: string]: unknown;
    } | null;
    limit?: number | null;
    sort?: Array<Sort> | null;
};

export type MergedSettingsSchema = {
    acl_template_id?: string | null;
    allow_invites_by_link?: boolean | null;
    /**
     * Allow playing the original file while transcoding is in progress.
     */
    allow_play_original_during_transcoding?: boolean | null;
    allow_share_magic_link_creation?: boolean | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    readonly billing_tier?: string | null;
    readonly client_ip?: string | null;
    collections_get_parent_acls?: boolean | null;
    cors_hosts?: Array<string> | null;
    readonly custom_terms?: boolean | null;
    dashboard?: DashboardSchema | null;
    date_format?: string | null;
    datetime_format?: string | null;
    /**
     * Default time to live for app tokens in seconds.
     */
    default_app_token_ttl?: number | null;
    /**
     * Default time to live for refresh tokens in seconds.
     */
    default_refresh_token_ttl?: number | null;
    default_share_options?: DefaultShareOptionsTypeSchema | null;
    default_upload_storage_id?: string | null;
    /**
     * Default time to live for user tokens in seconds.
     */
    default_user_token_ttl?: number | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    readonly disable_billing_page?: boolean | null;
    readonly domain_has_preloaded_assets?: boolean | null;
    drm?: MergedSettingsSchemaDrm | null;
    /**
     * Whether to require hardware DRM for playback when DRM is enabled
     */
    drm_enforce?: boolean | null;
    enable_ai_metadata_filling?: boolean | null;
    enable_face_recognition?: boolean | null;
    enable_nltf?: boolean | null;
    enable_shield?: boolean | null;
    /**
     * When enabled, magic links can only be sent to allowlisted emails/domains
     */
    enforce_magic_link_allowlist?: boolean | null;
    external_share?: boolean | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    readonly features?: Array<string> | null;
    filters_default_metadata_view_id?: string | null;
    genesis?: string | null;
    readonly group_id?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    image_properties_metadata_field?: string | null;
    readonly is_plg_domain?: boolean | null;
    jobs_dashboard?: JobsDashboardSchema | null;
    locations_metadata_field?: string | null;
    /**
     * Forbid regular users to edit or delete mapped collections.
     */
    lock_mapped_collections?: boolean | null;
    logo_storage_id?: string | null;
    readonly logo_url?: string | null;
    logos_metadata_field?: string | null;
    max_browse_users?: number | null;
    max_power_users?: number | null;
    max_standard_users?: number | null;
    max_storage_bytes?: number | null;
    max_traffic_bytes?: number | null;
    mfa_methods?: Array<'MAIL_2SV' | 'TOTP'> | null;
    mfa_required?: boolean | null;
    password_checks?: PasswordChecksType | null;
    require_limit_download_groups?: boolean | null;
    required_metadata_views?: Array<string> | null;
    review_experience_disabled?: boolean | null;
    review_experience_disabled_per_share?: boolean | null;
    safe_searches_metadata_field?: string | null;
    saml_require_groups?: boolean | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayField> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_users_from_share?: boolean | null;
    search_view_id?: string | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    show_persons_confirmation_modal?: boolean | null;
    support_access?: boolean | null;
    readonly system_domain_id?: string | null;
    readonly system_domain_name?: string | null;
    tags_metadata_field?: string | null;
    texts_metadata_field?: string | null;
    update_saml_primary_group_on_login?: boolean | null;
    usage_history?: UsageHistory | null;
    use_asset_name_on_download?: boolean | null;
    watermark?: MergedSettingsSchemaWatermark | null;
    watermark_options?: WatermarkOptionsType | null;
};

/**
 * DRM setting
 */
export type MergedSettingsSchemaDrm = 'none' | 'standard';

/**
 * Watermark setting
 */
export type MergedSettingsSchemaWatermark = 'none' | 'standard';

export type PasswordChecksType = {
    digits?: number | null;
    lowercase?: number | null;
    max_length?: number | null;
    min_length?: number | null;
    special_symbols?: number | null;
    uppercase?: number | null;
};

export type PasswordChecksTypeSchema = {
    digits?: number | null;
    lowercase?: number | null;
    max_length?: number | null;
    min_length?: number | null;
    special_symbols?: number | null;
    uppercase?: number | null;
};

export type SearchDisplayField = {
    name: string;
};

export type SearchDisplayFieldSchema = {
    name: string;
};

export type Sort = {
    name: string;
    order?: SortOrder | null;
};

export type SortOrder = 'asc' | 'desc';

export type SortSchema = {
    name: string;
    order?: SortSchemaOrder | null;
};

export type SortSchemaOrder = 'asc' | 'desc';

export type SystemSettingPublicSchema = {
    acl_template_id?: string | null;
    allow_invites_by_link?: boolean | null;
    /**
     * Allow playing the original file while transcoding is in progress.
     */
    allow_play_original_during_transcoding?: boolean | null;
    allow_share_magic_link_creation?: boolean | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    readonly billing_tier?: string | null;
    readonly client_ip?: string | null;
    collections_get_parent_acls?: boolean | null;
    cors_hosts?: Array<string> | null;
    readonly custom_terms?: boolean | null;
    date_format?: string | null;
    datetime_format?: string | null;
    /**
     * Default time to live for app tokens in seconds.
     */
    default_app_token_ttl?: number | null;
    /**
     * Default time to live for refresh tokens in seconds.
     */
    default_refresh_token_ttl?: number | null;
    default_share_options?: DefaultShareOptionsTypeSchema | null;
    default_upload_storage_id?: string | null;
    /**
     * Default time to live for user tokens in seconds.
     */
    default_user_token_ttl?: number | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    readonly disable_billing_page?: boolean | null;
    readonly domain_has_preloaded_assets?: boolean | null;
    drm?: SystemSettingPublicSchemaDrm | null;
    /**
     * Whether to require hardware DRM for playback when DRM is enabled
     */
    drm_enforce?: boolean | null;
    enable_ai_metadata_filling?: boolean | null;
    enable_face_recognition?: boolean | null;
    enable_nltf?: boolean | null;
    enable_shield?: boolean | null;
    /**
     * When enabled, magic links can only be sent to allowlisted emails/domains
     */
    enforce_magic_link_allowlist?: boolean | null;
    external_share?: boolean | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    readonly features?: Array<string> | null;
    filters_default_metadata_view_id?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    image_properties_metadata_field?: string | null;
    readonly is_plg_domain?: boolean | null;
    jobs_dashboard?: JobsDashboardSchema | null;
    locations_metadata_field?: string | null;
    /**
     * Forbid regular users to edit or delete mapped collections.
     */
    lock_mapped_collections?: boolean | null;
    logo_storage_id?: string | null;
    readonly logo_url?: string | null;
    logos_metadata_field?: string | null;
    max_browse_users?: number | null;
    max_power_users?: number | null;
    max_standard_users?: number | null;
    max_storage_bytes?: number | null;
    max_traffic_bytes?: number | null;
    mfa_methods?: Array<'MAIL_2SV' | 'TOTP'> | null;
    mfa_required?: boolean | null;
    password_checks?: PasswordChecksTypeSchema | null;
    require_limit_download_groups?: boolean | null;
    required_metadata_views?: Array<string> | null;
    review_experience_disabled?: boolean | null;
    review_experience_disabled_per_share?: boolean | null;
    safe_searches_metadata_field?: string | null;
    saml_require_groups?: boolean | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayFieldSchema> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_users_from_share?: boolean | null;
    search_view_id?: string | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    support_access?: boolean | null;
    readonly system_domain_id?: string | null;
    readonly system_domain_name?: string | null;
    tags_metadata_field?: string | null;
    texts_metadata_field?: string | null;
    update_saml_primary_group_on_login?: boolean | null;
    use_asset_name_on_download?: boolean | null;
    watermark?: SystemSettingPublicSchemaWatermark | null;
    watermark_options?: WatermarkOptionsType | null;
};

/**
 * DRM setting
 */
export type SystemSettingPublicSchemaDrm = 'none' | 'standard';

/**
 * Watermark setting
 */
export type SystemSettingPublicSchemaWatermark = 'none' | 'standard';

export type SystemSettingSchema = {
    acl_template_id?: string | null;
    allow_invites_by_link?: boolean | null;
    /**
     * Allow playing the original file while transcoding is in progress.
     */
    allow_play_original_during_transcoding?: boolean | null;
    allow_share_magic_link_creation?: boolean | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    readonly client_ip?: string | null;
    collections_get_parent_acls?: boolean | null;
    cors_hosts?: Array<string> | null;
    date_format?: string | null;
    datetime_format?: string | null;
    /**
     * Default time to live for app tokens in seconds.
     */
    default_app_token_ttl?: number | null;
    /**
     * Default time to live for refresh tokens in seconds.
     */
    default_refresh_token_ttl?: number | null;
    default_share_options?: DefaultShareOptionsTypeSchema | null;
    default_upload_storage_id?: string | null;
    /**
     * Default time to live for user tokens in seconds.
     */
    default_user_token_ttl?: number | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    drm?: SystemSettingSchemaDrm | null;
    /**
     * Whether to require hardware DRM for playback when DRM is enabled
     */
    drm_enforce?: boolean | null;
    enable_ai_metadata_filling?: boolean | null;
    enable_face_recognition?: boolean | null;
    enable_nltf?: boolean | null;
    enable_shield?: boolean | null;
    /**
     * When enabled, magic links can only be sent to allowlisted emails/domains
     */
    enforce_magic_link_allowlist?: boolean | null;
    external_share?: boolean | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    filters_default_metadata_view_id?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    image_properties_metadata_field?: string | null;
    jobs_dashboard?: JobsDashboardSchema | null;
    locations_metadata_field?: string | null;
    /**
     * Forbid regular users to edit or delete mapped collections.
     */
    lock_mapped_collections?: boolean | null;
    logo_storage_id?: string | null;
    logo_url?: string | null;
    logos_metadata_field?: string | null;
    max_browse_users?: number | null;
    max_power_users?: number | null;
    max_standard_users?: number | null;
    max_storage_bytes?: number | null;
    max_traffic_bytes?: number | null;
    mfa_methods?: Array<'MAIL_2SV' | 'TOTP'> | null;
    mfa_required?: boolean | null;
    password_checks?: PasswordChecksTypeSchema | null;
    require_limit_download_groups?: boolean | null;
    required_metadata_views?: Array<string> | null;
    review_experience_disabled?: boolean | null;
    review_experience_disabled_per_share?: boolean | null;
    safe_searches_metadata_field?: string | null;
    saml_require_groups?: boolean | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayFieldSchema> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_users_from_share?: boolean | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    support_access?: boolean | null;
    readonly system_domain_id?: string | null;
    readonly system_domain_name?: string | null;
    tags_metadata_field?: string | null;
    texts_metadata_field?: string | null;
    update_saml_primary_group_on_login?: boolean | null;
    use_asset_name_on_download?: boolean | null;
    watermark?: SystemSettingSchemaWatermark | null;
    watermark_options?: WatermarkOptionsType | null;
};

/**
 * DRM setting
 */
export type SystemSettingSchemaDrm = 'none' | 'standard';

/**
 * Watermark setting
 */
export type SystemSettingSchemaWatermark = 'none' | 'standard';

export type UsageHistory = {
    widgets?: Array<UsageHistoryWidget> | null;
};

export type UsageHistorySchema = {
    widgets?: Array<UsageHistoryWidget> | null;
};

export type UsageHistoryWidget = {
    expanded?: boolean | null;
    id?: string | null;
};

export type UsageHistoryWidgetSchema = {
    expanded?: boolean | null;
    id?: string | null;
};

export type UserSettingRemoveAttributesSchema = {
    allowed_ips?: Array<AllowedIpSchema> | null;
    asset_default_sections?: Array<string> | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    jobs_dashboard?: JobsDashboardSchema | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayFieldSchema> | null;
    user_ids: Array<string>;
};

export type UserSettingSchema = {
    acl_template_id?: string | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    readonly client_ip?: string | null;
    collections_get_parent_acls?: boolean | null;
    dashboard?: DashboardSchema | null;
    date_format?: string | null;
    datetime_format?: string | null;
    default_upload_storage_id?: string | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    filters_default_metadata_view_id?: string | null;
    genesis?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    jobs_dashboard?: JobsDashboardSchema | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayFieldSchema> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_view_id?: string | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    show_persons_confirmation_modal?: boolean | null;
    usage_history?: UsageHistorySchema | null;
    use_asset_name_on_download?: boolean | null;
};

export type WatermarkOptionsType = {
    custom_text?: string | null;
    groups?: Array<string> | null;
    include_custom_text?: boolean | null;
    include_date_time?: boolean | null;
    include_email?: boolean | null;
    include_ip_address?: boolean | null;
    shadow_opacity?: number | null;
    show_for_groups?: WatermarkOptionsTypeShowForGroups | null;
    show_in_context?: WatermarkOptionsTypeShowInContext | null;
    show_watermark?: boolean | null;
    text_appearance?: WatermarkOptionsTypeTextAppearance | null;
    text_opacity?: number | null;
};

export type WatermarkOptionsTypeSchema = {
    custom_text?: string | null;
    groups?: Array<string> | null;
    include_custom_text?: boolean | null;
    include_date_time?: boolean | null;
    include_email?: boolean | null;
    include_ip_address?: boolean | null;
    shadow_opacity?: number | null;
    show_for_groups?: WatermarkOptionsTypeSchemaShowForGroups | null;
    show_in_context?: WatermarkOptionsTypeSchemaShowInContext | null;
    show_watermark?: boolean | null;
    text_appearance?: WatermarkOptionsTypeSchemaTextAppearance | null;
    text_opacity?: number | null;
};

export type WatermarkOptionsTypeSchemaShowForGroups = 'all' | 'except' | 'selected_only';

export type WatermarkOptionsTypeSchemaShowInContext = 'proxies' | 'shares';

export type WatermarkOptionsTypeSchemaTextAppearance = 'bottom' | 'center' | 'top';

export type WatermarkOptionsTypeShowForGroups = 'all' | 'except' | 'selected_only';

export type WatermarkOptionsTypeShowInContext = 'proxies' | 'shares';

export type WatermarkOptionsTypeTextAppearance = 'bottom' | 'center' | 'top';

export type CorsHostSchemaWritable = {
    host: string;
};

export type CorsHostsSchemaWritable = {
    [key: string]: unknown;
};

export type GroupSettingPublicSchemaWritable = {
    acl_template_id?: string | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    collections_get_parent_acls?: boolean | null;
    date_format?: string | null;
    datetime_format?: string | null;
    default_upload_storage_id?: string | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    filters_default_metadata_view_id?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    jobs_dashboard?: JobsDashboard | null;
    logo_storage_id?: string | null;
    required_metadata_views?: Array<string> | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayField> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_view_id?: string | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    use_asset_name_on_download?: boolean | null;
};

export type GroupSettingSchemaWritable = {
    logo_storage_id?: string | null;
    logo_url?: string | null;
};

export type MergedSettingsSchemaWritable = {
    acl_template_id?: string | null;
    allow_invites_by_link?: boolean | null;
    /**
     * Allow playing the original file while transcoding is in progress.
     */
    allow_play_original_during_transcoding?: boolean | null;
    allow_share_magic_link_creation?: boolean | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    collections_get_parent_acls?: boolean | null;
    cors_hosts?: Array<string> | null;
    dashboard?: DashboardSchema | null;
    date_format?: string | null;
    datetime_format?: string | null;
    /**
     * Default time to live for app tokens in seconds.
     */
    default_app_token_ttl?: number | null;
    /**
     * Default time to live for refresh tokens in seconds.
     */
    default_refresh_token_ttl?: number | null;
    default_share_options?: DefaultShareOptionsTypeSchema | null;
    default_upload_storage_id?: string | null;
    /**
     * Default time to live for user tokens in seconds.
     */
    default_user_token_ttl?: number | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    drm?: MergedSettingsSchemaDrm | null;
    /**
     * Whether to require hardware DRM for playback when DRM is enabled
     */
    drm_enforce?: boolean | null;
    enable_ai_metadata_filling?: boolean | null;
    enable_face_recognition?: boolean | null;
    enable_nltf?: boolean | null;
    enable_shield?: boolean | null;
    /**
     * When enabled, magic links can only be sent to allowlisted emails/domains
     */
    enforce_magic_link_allowlist?: boolean | null;
    external_share?: boolean | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    filters_default_metadata_view_id?: string | null;
    genesis?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    image_properties_metadata_field?: string | null;
    jobs_dashboard?: JobsDashboardSchema | null;
    locations_metadata_field?: string | null;
    /**
     * Forbid regular users to edit or delete mapped collections.
     */
    lock_mapped_collections?: boolean | null;
    logo_storage_id?: string | null;
    logos_metadata_field?: string | null;
    max_browse_users?: number | null;
    max_power_users?: number | null;
    max_standard_users?: number | null;
    max_storage_bytes?: number | null;
    max_traffic_bytes?: number | null;
    mfa_methods?: Array<'MAIL_2SV' | 'TOTP'> | null;
    mfa_required?: boolean | null;
    password_checks?: PasswordChecksType | null;
    require_limit_download_groups?: boolean | null;
    required_metadata_views?: Array<string> | null;
    review_experience_disabled?: boolean | null;
    review_experience_disabled_per_share?: boolean | null;
    safe_searches_metadata_field?: string | null;
    saml_require_groups?: boolean | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayField> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_users_from_share?: boolean | null;
    search_view_id?: string | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    show_persons_confirmation_modal?: boolean | null;
    support_access?: boolean | null;
    tags_metadata_field?: string | null;
    texts_metadata_field?: string | null;
    update_saml_primary_group_on_login?: boolean | null;
    usage_history?: UsageHistory | null;
    use_asset_name_on_download?: boolean | null;
    watermark?: MergedSettingsSchemaWatermark | null;
    watermark_options?: WatermarkOptionsType | null;
};

export type SystemSettingPublicSchemaWritable = {
    acl_template_id?: string | null;
    allow_invites_by_link?: boolean | null;
    /**
     * Allow playing the original file while transcoding is in progress.
     */
    allow_play_original_during_transcoding?: boolean | null;
    allow_share_magic_link_creation?: boolean | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    collections_get_parent_acls?: boolean | null;
    cors_hosts?: Array<string> | null;
    date_format?: string | null;
    datetime_format?: string | null;
    /**
     * Default time to live for app tokens in seconds.
     */
    default_app_token_ttl?: number | null;
    /**
     * Default time to live for refresh tokens in seconds.
     */
    default_refresh_token_ttl?: number | null;
    default_share_options?: DefaultShareOptionsTypeSchema | null;
    default_upload_storage_id?: string | null;
    /**
     * Default time to live for user tokens in seconds.
     */
    default_user_token_ttl?: number | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    drm?: SystemSettingPublicSchemaDrm | null;
    /**
     * Whether to require hardware DRM for playback when DRM is enabled
     */
    drm_enforce?: boolean | null;
    enable_ai_metadata_filling?: boolean | null;
    enable_face_recognition?: boolean | null;
    enable_nltf?: boolean | null;
    enable_shield?: boolean | null;
    /**
     * When enabled, magic links can only be sent to allowlisted emails/domains
     */
    enforce_magic_link_allowlist?: boolean | null;
    external_share?: boolean | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    filters_default_metadata_view_id?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    image_properties_metadata_field?: string | null;
    jobs_dashboard?: JobsDashboardSchema | null;
    locations_metadata_field?: string | null;
    /**
     * Forbid regular users to edit or delete mapped collections.
     */
    lock_mapped_collections?: boolean | null;
    logo_storage_id?: string | null;
    logos_metadata_field?: string | null;
    max_browse_users?: number | null;
    max_power_users?: number | null;
    max_standard_users?: number | null;
    max_storage_bytes?: number | null;
    max_traffic_bytes?: number | null;
    mfa_methods?: Array<'MAIL_2SV' | 'TOTP'> | null;
    mfa_required?: boolean | null;
    password_checks?: PasswordChecksTypeSchema | null;
    require_limit_download_groups?: boolean | null;
    required_metadata_views?: Array<string> | null;
    review_experience_disabled?: boolean | null;
    review_experience_disabled_per_share?: boolean | null;
    safe_searches_metadata_field?: string | null;
    saml_require_groups?: boolean | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayFieldSchema> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_users_from_share?: boolean | null;
    search_view_id?: string | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    support_access?: boolean | null;
    tags_metadata_field?: string | null;
    texts_metadata_field?: string | null;
    update_saml_primary_group_on_login?: boolean | null;
    use_asset_name_on_download?: boolean | null;
    watermark?: SystemSettingPublicSchemaWatermark | null;
    watermark_options?: WatermarkOptionsType | null;
};

export type SystemSettingSchemaWritable = {
    acl_template_id?: string | null;
    allow_invites_by_link?: boolean | null;
    /**
     * Allow playing the original file while transcoding is in progress.
     */
    allow_play_original_during_transcoding?: boolean | null;
    allow_share_magic_link_creation?: boolean | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    collections_get_parent_acls?: boolean | null;
    cors_hosts?: Array<string> | null;
    date_format?: string | null;
    datetime_format?: string | null;
    /**
     * Default time to live for app tokens in seconds.
     */
    default_app_token_ttl?: number | null;
    /**
     * Default time to live for refresh tokens in seconds.
     */
    default_refresh_token_ttl?: number | null;
    default_share_options?: DefaultShareOptionsTypeSchema | null;
    default_upload_storage_id?: string | null;
    /**
     * Default time to live for user tokens in seconds.
     */
    default_user_token_ttl?: number | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    drm?: SystemSettingSchemaDrm | null;
    /**
     * Whether to require hardware DRM for playback when DRM is enabled
     */
    drm_enforce?: boolean | null;
    enable_ai_metadata_filling?: boolean | null;
    enable_face_recognition?: boolean | null;
    enable_nltf?: boolean | null;
    enable_shield?: boolean | null;
    /**
     * When enabled, magic links can only be sent to allowlisted emails/domains
     */
    enforce_magic_link_allowlist?: boolean | null;
    external_share?: boolean | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    filters_default_metadata_view_id?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    image_properties_metadata_field?: string | null;
    jobs_dashboard?: JobsDashboardSchema | null;
    locations_metadata_field?: string | null;
    /**
     * Forbid regular users to edit or delete mapped collections.
     */
    lock_mapped_collections?: boolean | null;
    logo_storage_id?: string | null;
    logo_url?: string | null;
    logos_metadata_field?: string | null;
    max_browse_users?: number | null;
    max_power_users?: number | null;
    max_standard_users?: number | null;
    max_storage_bytes?: number | null;
    max_traffic_bytes?: number | null;
    mfa_methods?: Array<'MAIL_2SV' | 'TOTP'> | null;
    mfa_required?: boolean | null;
    password_checks?: PasswordChecksTypeSchema | null;
    require_limit_download_groups?: boolean | null;
    required_metadata_views?: Array<string> | null;
    review_experience_disabled?: boolean | null;
    review_experience_disabled_per_share?: boolean | null;
    safe_searches_metadata_field?: string | null;
    saml_require_groups?: boolean | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayFieldSchema> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_users_from_share?: boolean | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    support_access?: boolean | null;
    tags_metadata_field?: string | null;
    texts_metadata_field?: string | null;
    update_saml_primary_group_on_login?: boolean | null;
    use_asset_name_on_download?: boolean | null;
    watermark?: SystemSettingSchemaWatermark | null;
    watermark_options?: WatermarkOptionsType | null;
};

export type UserSettingSchemaWritable = {
    acl_template_id?: string | null;
    allowed_ips?: Array<AllowedIpSchema> | null;
    append_asset_uuid_to_downloads?: boolean | null;
    asset_default_sections?: Array<string> | null;
    collections_get_parent_acls?: boolean | null;
    dashboard?: DashboardSchema | null;
    date_format?: string | null;
    datetime_format?: string | null;
    default_upload_storage_id?: string | null;
    /**
     * Grace period that indicate how long objects will live in recycle bin. Unit: hours
     */
    delete_grace_period?: number | null;
    facet_fields?: Array<FacetFieldSchema> | null;
    filters_default_metadata_view_id?: string | null;
    genesis?: string | null;
    hide_favourites?: boolean | null;
    home_page?: string | null;
    jobs_dashboard?: JobsDashboardSchema | null;
    search_auto_resize_title_column?: boolean | null;
    search_default_sections?: Array<string> | null;
    search_display_fields?: Array<SearchDisplayFieldSchema> | null;
    search_in_transcriptions?: boolean | null;
    search_results_asset_metadata_view_id?: string | null;
    search_results_collection_metadata_view_id?: string | null;
    search_view_id?: string | null;
    /**
     * Default share expiration time that indicate how long share will be valid. Unit: days
     */
    share_expiration_time?: number | null;
    show_persons_confirmation_modal?: boolean | null;
    usage_history?: UsageHistorySchema | null;
    use_asset_name_on_download?: boolean | null;
};

export type GetCorsHostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/cors_hosts/';
};

export type GetCorsHostsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Realm does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetCorsHostsError = GetCorsHostsErrors[keyof GetCorsHostsErrors];

export type GetCorsHostsResponses = {
    /**
     * Returns a system settings
     */
    200: CorsHostsSchema;
};

export type GetCorsHostsResponse = GetCorsHostsResponses[keyof GetCorsHostsResponses];

export type PostCorsHostsData = {
    /**
     * body
     */
    body: CorsHostSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/cors_hosts/';
};

export type PostCorsHostsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostCorsHostsError = PostCorsHostsErrors[keyof PostCorsHostsErrors];

export type PostCorsHostsResponses = {
    /**
     * Returns a created CORS host
     */
    201: CorsHostSchema;
};

export type PostCorsHostsResponse = PostCorsHostsResponses[keyof PostCorsHostsResponses];

export type DeleteCorsHostsByCorsHostIdData = {
    body?: never;
    path: {
        cors_host_id: string;
    };
    query?: never;
    url: '/v1/cors_hosts/{cors_host_id}/';
};

export type DeleteCorsHostsByCorsHostIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteCorsHostsByCorsHostIdError = DeleteCorsHostsByCorsHostIdErrors[keyof DeleteCorsHostsByCorsHostIdErrors];

export type DeleteCorsHostsByCorsHostIdResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteCorsHostsByCorsHostIdResponse = DeleteCorsHostsByCorsHostIdResponses[keyof DeleteCorsHostsByCorsHostIdResponses];

export type GetCorsHostsByCorsHostIdData = {
    body?: never;
    path: {
        cors_host_id: string;
    };
    query?: never;
    url: '/v1/cors_hosts/{cors_host_id}/';
};

export type GetCorsHostsByCorsHostIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * CORS host does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetCorsHostsByCorsHostIdError = GetCorsHostsByCorsHostIdErrors[keyof GetCorsHostsByCorsHostIdErrors];

export type GetCorsHostsByCorsHostIdResponses = {
    /**
     * Returns a CORS host
     */
    200: CorsHostSchema;
};

export type GetCorsHostsByCorsHostIdResponse = GetCorsHostsByCorsHostIdResponses[keyof GetCorsHostsByCorsHostIdResponses];

export type DeleteGroupByGroupIdData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/v1/group/{group_id}/';
};

export type DeleteGroupByGroupIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteGroupByGroupIdError = DeleteGroupByGroupIdErrors[keyof DeleteGroupByGroupIdErrors];

export type DeleteGroupByGroupIdResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteGroupByGroupIdResponse = DeleteGroupByGroupIdResponses[keyof DeleteGroupByGroupIdResponses];

export type GetGroupByGroupIdData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/v1/group/{group_id}/';
};

export type GetGroupByGroupIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Realm does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetGroupByGroupIdError = GetGroupByGroupIdErrors[keyof GetGroupByGroupIdErrors];

export type GetGroupByGroupIdResponses = {
    /**
     * Returns group settings
     */
    200: GroupSettingPublicSchema;
};

export type GetGroupByGroupIdResponse = GetGroupByGroupIdResponses[keyof GetGroupByGroupIdResponses];

export type PatchGroupByGroupIdData = {
    /**
     * body
     */
    body: GroupSettingPublicSchemaWritable;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/v1/group/{group_id}/';
};

export type PatchGroupByGroupIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchGroupByGroupIdError = PatchGroupByGroupIdErrors[keyof PatchGroupByGroupIdErrors];

export type PatchGroupByGroupIdResponses = {
    /**
     * Returns changed group settings
     */
    200: GroupSettingPublicSchema;
};

export type PatchGroupByGroupIdResponse = PatchGroupByGroupIdResponses[keyof PatchGroupByGroupIdResponses];

export type PutGroupByGroupIdData = {
    /**
     * body
     */
    body: GroupSettingPublicSchemaWritable;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/v1/group/{group_id}/';
};

export type PutGroupByGroupIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutGroupByGroupIdError = PutGroupByGroupIdErrors[keyof PutGroupByGroupIdErrors];

export type PutGroupByGroupIdResponses = {
    /**
     * Returns changed group settings
     */
    200: GroupSettingPublicSchema;
};

export type PutGroupByGroupIdResponse = PutGroupByGroupIdResponses[keyof PutGroupByGroupIdResponses];

export type GetMergedCurrentData = {
    body?: never;
    path?: never;
    query?: {
        ignore_logo_url?: boolean;
    };
    url: '/v1/merged/current/';
};

export type GetMergedCurrentErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Realm does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetMergedCurrentError = GetMergedCurrentErrors[keyof GetMergedCurrentErrors];

export type GetMergedCurrentResponses = {
    /**
     * Returns a merged settings
     */
    200: MergedSettingsSchema;
};

export type GetMergedCurrentResponse = GetMergedCurrentResponses[keyof GetMergedCurrentResponses];

export type GetMergedByUserIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: {
        ignore_logo_url?: boolean;
    };
    url: '/v1/merged/{user_id}/';
};

export type GetMergedByUserIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Realm does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetMergedByUserIdError = GetMergedByUserIdErrors[keyof GetMergedByUserIdErrors];

export type GetMergedByUserIdResponses = {
    /**
     * Returns a merged settings
     */
    200: MergedSettingsSchema;
};

export type GetMergedByUserIdResponse = GetMergedByUserIdResponses[keyof GetMergedByUserIdResponses];

export type DeleteSearchViewByViewIdGroupIdsData = {
    /**
     * body
     */
    body: GroupSettingsIdSchema;
    path: {
        view_id: string;
    };
    query?: never;
    url: '/v1/search_view/{view_id}/group_ids/';
};

export type DeleteSearchViewByViewIdGroupIdsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteSearchViewByViewIdGroupIdsError = DeleteSearchViewByViewIdGroupIdsErrors[keyof DeleteSearchViewByViewIdGroupIdsErrors];

export type DeleteSearchViewByViewIdGroupIdsResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteSearchViewByViewIdGroupIdsResponse = DeleteSearchViewByViewIdGroupIdsResponses[keyof DeleteSearchViewByViewIdGroupIdsResponses];

export type GetSearchViewByViewIdGroupIdsData = {
    body?: never;
    path: {
        view_id: string;
    };
    query?: never;
    url: '/v1/search_view/{view_id}/group_ids/';
};

export type GetSearchViewByViewIdGroupIdsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetSearchViewByViewIdGroupIdsError = GetSearchViewByViewIdGroupIdsErrors[keyof GetSearchViewByViewIdGroupIdsErrors];

export type GetSearchViewByViewIdGroupIdsResponses = {
    /**
     * Returns group IDs
     */
    200: GroupSettingsIdSchema;
};

export type GetSearchViewByViewIdGroupIdsResponse = GetSearchViewByViewIdGroupIdsResponses[keyof GetSearchViewByViewIdGroupIdsResponses];

export type PatchSearchViewByViewIdGroupIdsData = {
    /**
     * body
     */
    body: GroupSettingsIdSchema;
    path: {
        view_id: string;
    };
    query?: never;
    url: '/v1/search_view/{view_id}/group_ids/';
};

export type PatchSearchViewByViewIdGroupIdsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchSearchViewByViewIdGroupIdsError = PatchSearchViewByViewIdGroupIdsErrors[keyof PatchSearchViewByViewIdGroupIdsErrors];

export type PatchSearchViewByViewIdGroupIdsResponses = {
    /**
     * Without body
     */
    204: void;
};

export type PatchSearchViewByViewIdGroupIdsResponse = PatchSearchViewByViewIdGroupIdsResponses[keyof PatchSearchViewByViewIdGroupIdsResponses];

export type PutSearchViewByViewIdGroupIdsData = {
    /**
     * body
     */
    body: GroupSettingsIdSchema;
    path: {
        view_id: string;
    };
    query?: never;
    url: '/v1/search_view/{view_id}/group_ids/';
};

export type PutSearchViewByViewIdGroupIdsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutSearchViewByViewIdGroupIdsError = PutSearchViewByViewIdGroupIdsErrors[keyof PutSearchViewByViewIdGroupIdsErrors];

export type PutSearchViewByViewIdGroupIdsResponses = {
    /**
     * Without body
     */
    204: void;
};

export type PutSearchViewByViewIdGroupIdsResponse = PutSearchViewByViewIdGroupIdsResponses[keyof PutSearchViewByViewIdGroupIdsResponses];

export type GetSystemCurrentData = {
    body?: never;
    path?: never;
    query?: {
        ignore_logo_url?: boolean;
    };
    url: '/v1/system/current/';
};

export type GetSystemCurrentErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Realm does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetSystemCurrentError = GetSystemCurrentErrors[keyof GetSystemCurrentErrors];

export type GetSystemCurrentResponses = {
    /**
     * Returns a system settings
     */
    200: SystemSettingPublicSchema;
};

export type GetSystemCurrentResponse = GetSystemCurrentResponses[keyof GetSystemCurrentResponses];

export type PatchSystemCurrentData = {
    /**
     * body
     */
    body: SystemSettingPublicSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/system/current/';
};

export type PatchSystemCurrentErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchSystemCurrentError = PatchSystemCurrentErrors[keyof PatchSystemCurrentErrors];

export type PatchSystemCurrentResponses = {
    /**
     * Returns changed system settings
     */
    200: SystemSettingPublicSchema;
};

export type PatchSystemCurrentResponse = PatchSystemCurrentResponses[keyof PatchSystemCurrentResponses];

export type PutSystemCurrentData = {
    /**
     * body
     */
    body: SystemSettingPublicSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/system/current/';
};

export type PutSystemCurrentErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutSystemCurrentError = PutSystemCurrentErrors[keyof PutSystemCurrentErrors];

export type PutSystemCurrentResponses = {
    /**
     * Returns changed system settings
     */
    200: SystemSettingPublicSchema;
};

export type PutSystemCurrentResponse = PutSystemCurrentResponses[keyof PutSystemCurrentResponses];

export type GetSystemBySystemDomainIdData = {
    body?: never;
    path: {
        system_domain_id: string;
    };
    query?: {
        ignore_logo_url?: boolean;
    };
    url: '/v1/system/{system_domain_id}/';
};

export type GetSystemBySystemDomainIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Realm does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetSystemBySystemDomainIdError = GetSystemBySystemDomainIdErrors[keyof GetSystemBySystemDomainIdErrors];

export type GetSystemBySystemDomainIdResponses = {
    /**
     * Returns a system settings
     */
    200: SystemSettingPublicSchema;
};

export type GetSystemBySystemDomainIdResponse = GetSystemBySystemDomainIdResponses[keyof GetSystemBySystemDomainIdResponses];

export type PatchSystemBySystemDomainIdData = {
    /**
     * body
     */
    body: SystemSettingPublicSchemaWritable;
    path: {
        system_domain_id: string;
    };
    query?: never;
    url: '/v1/system/{system_domain_id}/';
};

export type PatchSystemBySystemDomainIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchSystemBySystemDomainIdError = PatchSystemBySystemDomainIdErrors[keyof PatchSystemBySystemDomainIdErrors];

export type PatchSystemBySystemDomainIdResponses = {
    /**
     * Returns changed system settings
     */
    200: SystemSettingPublicSchema;
};

export type PatchSystemBySystemDomainIdResponse = PatchSystemBySystemDomainIdResponses[keyof PatchSystemBySystemDomainIdResponses];

export type PutSystemBySystemDomainIdData = {
    /**
     * body
     */
    body: SystemSettingPublicSchemaWritable;
    path: {
        system_domain_id: string;
    };
    query?: never;
    url: '/v1/system/{system_domain_id}/';
};

export type PutSystemBySystemDomainIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutSystemBySystemDomainIdError = PutSystemBySystemDomainIdErrors[keyof PutSystemBySystemDomainIdErrors];

export type PutSystemBySystemDomainIdResponses = {
    /**
     * Returns changed system settings
     */
    200: SystemSettingPublicSchema;
};

export type PutSystemBySystemDomainIdResponse = PutSystemBySystemDomainIdResponses[keyof PutSystemBySystemDomainIdResponses];

export type DeleteTeamByTeamIdData = {
    body?: never;
    path: {
        team_id: string;
    };
    query?: never;
    url: '/v1/team/{team_id}/';
};

export type DeleteTeamByTeamIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteTeamByTeamIdError = DeleteTeamByTeamIdErrors[keyof DeleteTeamByTeamIdErrors];

export type DeleteTeamByTeamIdResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteTeamByTeamIdResponse = DeleteTeamByTeamIdResponses[keyof DeleteTeamByTeamIdResponses];

export type GetTeamByTeamIdData = {
    body?: never;
    path: {
        team_id: string;
    };
    query?: never;
    url: '/v1/team/{team_id}/';
};

export type GetTeamByTeamIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Realm does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetTeamByTeamIdError = GetTeamByTeamIdErrors[keyof GetTeamByTeamIdErrors];

export type GetTeamByTeamIdResponses = {
    /**
     * Returns team settings
     */
    200: GroupSettingPublicSchema;
};

export type GetTeamByTeamIdResponse = GetTeamByTeamIdResponses[keyof GetTeamByTeamIdResponses];

export type PatchTeamByTeamIdData = {
    /**
     * body
     */
    body: GroupSettingPublicSchemaWritable;
    path: {
        team_id: string;
    };
    query?: never;
    url: '/v1/team/{team_id}/';
};

export type PatchTeamByTeamIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchTeamByTeamIdError = PatchTeamByTeamIdErrors[keyof PatchTeamByTeamIdErrors];

export type PatchTeamByTeamIdResponses = {
    /**
     * Returns changed team settings
     */
    200: GroupSettingPublicSchema;
};

export type PatchTeamByTeamIdResponse = PatchTeamByTeamIdResponses[keyof PatchTeamByTeamIdResponses];

export type PutTeamByTeamIdData = {
    /**
     * body
     */
    body: GroupSettingPublicSchemaWritable;
    path: {
        team_id: string;
    };
    query?: never;
    url: '/v1/team/{team_id}/';
};

export type PutTeamByTeamIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutTeamByTeamIdError = PutTeamByTeamIdErrors[keyof PutTeamByTeamIdErrors];

export type PutTeamByTeamIdResponses = {
    /**
     * Returns changed team settings
     */
    200: GroupSettingPublicSchema;
};

export type PutTeamByTeamIdResponse = PutTeamByTeamIdResponses[keyof PutTeamByTeamIdResponses];

export type DeleteUserAttributesData = {
    /**
     * body
     */
    body: UserSettingRemoveAttributesSchema;
    path?: never;
    query?: never;
    url: '/v1/user/attributes/';
};

export type DeleteUserAttributesErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteUserAttributesError = DeleteUserAttributesErrors[keyof DeleteUserAttributesErrors];

export type DeleteUserAttributesResponses = {
    /**
     * Returns changed user settings
     */
    200: unknown;
};

export type DeleteUserByUserIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/user/{user_id}/';
};

export type DeleteUserByUserIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteUserByUserIdError = DeleteUserByUserIdErrors[keyof DeleteUserByUserIdErrors];

export type DeleteUserByUserIdResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteUserByUserIdResponse = DeleteUserByUserIdResponses[keyof DeleteUserByUserIdResponses];

export type GetUserByUserIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/user/{user_id}/';
};

export type GetUserByUserIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Realm does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetUserByUserIdError = GetUserByUserIdErrors[keyof GetUserByUserIdErrors];

export type GetUserByUserIdResponses = {
    /**
     * Returns a user settings
     */
    200: UserSettingSchema;
};

export type GetUserByUserIdResponse = GetUserByUserIdResponses[keyof GetUserByUserIdResponses];

export type PatchUserByUserIdData = {
    /**
     * body
     */
    body: UserSettingSchemaWritable;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/user/{user_id}/';
};

export type PatchUserByUserIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchUserByUserIdError = PatchUserByUserIdErrors[keyof PatchUserByUserIdErrors];

export type PatchUserByUserIdResponses = {
    /**
     * Returns changed user settings
     */
    200: UserSettingSchema;
};

export type PatchUserByUserIdResponse = PatchUserByUserIdResponses[keyof PatchUserByUserIdResponses];

export type PutUserByUserIdData = {
    /**
     * body
     */
    body: UserSettingSchemaWritable;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/user/{user_id}/';
};

export type PutUserByUserIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutUserByUserIdError = PutUserByUserIdErrors[keyof PutUserByUserIdErrors];

export type PutUserByUserIdResponses = {
    /**
     * Returns changed user settings
     */
    200: UserSettingSchema;
};

export type PutUserByUserIdResponse = PutUserByUserIdResponses[keyof PutUserByUserIdResponses];
