// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/API/stats/` | (string & {});
};

export type AssetUsageSchema = {
    asset_id: string;
    asset_type?: 'ASSET' | 'NLE_PROJECT' | 'PLACEHOLDER' | 'SEQUENCE';
    date?: string;
    readonly id?: string;
    metadata?: string;
    operation_source?: '' | 'COLLECTION' | 'DISCOVERY' | 'EXTERNAL_SHARE' | 'NOTIFICATION' | 'SEARCH' | 'SHARE';
    operation_type: 'APPROVE' | 'COMMENT' | 'CREATE' | 'DELETE' | 'EXIT' | 'PAUSE' | 'PLAY' | 'REFOCUS' | 'REJECT' | 'RENAME' | 'SEEK' | 'UNFOCUS' | 'VIEW';
    readonly system_domain_id?: string;
    system_name: string;
    time?: string;
    user_id: string;
};

export type AssetUsagesElasticSchema = {
    count?: number;
    date?: string;
    readonly id?: string;
    system_domain_id?: string;
};

export type AssetUsagesSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<AssetUsagesElasticSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type AutomationRunSchema = {
    readonly count?: number;
    readonly date?: string;
    readonly system_domain_id?: string;
};

export type AutomationRunsSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<AutomationRunSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type BillingCreditsSchema = {
    auto_pay?: boolean;
    readonly country?: string;
    credits: number;
    readonly currency?: string;
    custom_message?: string;
    readonly system_domain_id?: string;
    readonly total?: string;
    readonly vat?: number;
};

export type BillingCreditsVerifySchema = {
    readonly charge?: string;
    invoice_id: string;
    readonly system_domain_id?: string;
};

export type BillingCustomerCardSchema = {
    source: string;
};

export type BillingCustomerSchema = {
    business_vat_id?: string;
    email?: string;
    enable_subscription?: boolean;
    shipping: BillingCustomerShipping;
};

export type BillingCustomerShipping = {
    address: BillingCustomerShippingAddress;
    name: string;
    phone?: string | null;
};

export type BillingCustomerShippingAddress = {
    city: string;
    country: string;
    line1: string;
    line2?: string | null;
    postal_code: string;
    state?: string | null;
};

export type BillingCustomerShippingAddressSchema = {
    city: string;
    country: string;
    line1: string;
    line2?: string | null;
    postal_code: string;
    state?: string | null;
};

export type BillingCustomerShippingSchema = {
    address: BillingCustomerShippingAddressSchema;
    name: string;
    phone?: string | null;
};

export type BillingExpirationUpdateSchema = {
    expiration_date: string;
};

export type BillingReceiptSchema = {
    receipt_url?: string;
};

export type BillingRecipientsSchema = {
    emails?: Array<string>;
};

export type BillingSchema = {
    balance?: number;
    consumption_subtype?: string;
    consumption_type?: string;
    currency?: 'EUR' | 'USD';
    date?: string;
    expiration_date?: string | null;
    readonly id?: string;
    label: string;
    price_list?: string | null;
    system_domain_id: string;
    value: number;
};

export type BillingSettingsSchema = {
    auto_refill_amount?: number | null;
    enable_auto_top_up?: boolean;
    low_balance_trigger?: number | null;
};

export type BillingStatsSchema = {
    current_balance?: number;
    invoice_end_of_month?: boolean;
    new_billing_enabled?: boolean;
    stripe_id?: boolean;
    system_domain_status?: 'EUR' | 'USD';
    system_domain_type: string;
    system_domain_warning_message: string;
};

export type BillingsSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<BillingSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type CollectionUsageSchema = {
    collection_id: string;
    date?: string;
    readonly id?: string;
    metadata?: string;
    operation_source?: 'COLLECTION' | 'NOTIFICATION' | 'SEARCH';
    operation_type: 'CREATE' | 'DELETE' | 'RENAME' | 'VIEW';
    system_domain_id?: string;
    system_name: string;
    time?: string;
    user_id: string;
};

export type CollectionUsagesElasticSchema = {
    count?: number;
    date?: string;
    readonly id?: string;
    system_domain_id?: string;
};

export type CollectionUsagesSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<CollectionUsagesElasticSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type CreditsSchema = {
    readonly country?: string;
    credits: number;
    readonly currency?: string;
    readonly total?: number;
    readonly vat?: number;
};

export type CurrentUsageSchema = {
    readonly automation_runs?: number;
    readonly edge_transcoders?: number;
    readonly external_storage?: number;
    readonly images_analyzed?: number;
    readonly images_face_recognition?: number;
    readonly shield_enabled?: boolean;
    readonly storage?: {
        [key: string]: unknown;
    };
    readonly storage_gateway_clusters?: number;
    readonly storage_gateway_nodes?: number;
    readonly transcription_hours?: number;
    readonly users?: {
        [key: string]: unknown;
    };
    readonly video_analyzed_hours?: number;
    readonly video_face_recognition_hours?: number;
};

export type DateFilterSchema = {
    from_date?: string | null;
    to_date?: string | null;
};

export type ListObjectsSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type LogsRecipientReadSchema = {
    readonly id?: string;
    method: 'AMAZON' | 'GOOGLE';
    name: string;
};

export type LogsRecipientSchema = {
    readonly id?: string;
    method: 'AMAZON' | 'GOOGLE';
    name: string;
};

export type LogsRecipientsSchema = {
    readonly objects?: Array<LogsRecipientSchema>;
};

export type PaygoCostsSchema = {
    readonly analysis_cost?: number;
    readonly automation_cost?: number;
    readonly edge_transcoder_cost?: number;
    readonly external_storage_cost?: number;
    readonly face_recognition_cost?: number;
    readonly shield_cost?: number;
    readonly storage_costs?: {
        [key: string]: unknown;
    };
    readonly total_spend?: number;
    readonly transcription_cost?: number;
    readonly user_costs?: {
        [key: string]: unknown;
    };
};

export type PriceSchema = {
    currency: 'EUR' | 'USD';
    name: string;
    prices: {
        [key: string]: unknown;
    };
};

export type PricesSchema = {
    readonly objects?: Array<PriceSchema>;
};

export type StorageAccessElasticSchema = {
    bucket_name?: string;
    bytes_received?: number;
    bytes_sent?: number;
    date?: string;
    readonly id?: string;
    operations?: number;
    system_domain_id?: string;
};

export type StorageAccessSchema = {
    bucket_name: string;
    bytes_received?: number;
    bytes_sent?: number;
    date?: string;
    readonly id?: string;
    operation_type: string;
    operations?: number;
    storage_type: 'AZURE' | 'B2' | 'FILE' | 'FTP' | 'GCS' | 'HTTP' | 'OMMS' | 'S3' | 'SFTP' | 'TRANSFER';
    system_domain_id?: string;
    system_name: string;
};

export type StorageAccessesSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<StorageAccessElasticSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type StorageUsageSchema = {
    bucket_name: string;
    bytes_stored?: number;
    date?: string;
    readonly id?: string;
    storage_type: 'AZURE' | 'B2' | 'FILE' | 'FTP' | 'GCS' | 'HTTP' | 'OMMS' | 'S3' | 'SFTP' | 'TRANSFER';
    system_domain_id?: string;
    system_name: string;
};

export type StorageUsagesElasticSchema = {
    bucket_name?: string;
    bytes_stored?: number;
    date?: string;
    readonly id?: string;
    system_domain_id?: string;
};

export type StorageUsagesSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<StorageUsagesElasticSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type TranscoderUsageSchema = {
    adjusted_duration_seconds?: number | null;
    date?: string;
    destination_bytes?: number | null;
    duration_seconds?: number | null;
    readonly id?: string;
    is_user_transcoder?: boolean;
    job_id?: string | null;
    object_id?: string | null;
    object_type?: string | null;
    operation_type?: 'ANALYZE' | 'CONFORM' | 'EXTRACT_AUDIO' | 'EXTRACT_IMAGE' | 'FACE_RECOGNITION_IMAGE' | 'FACE_RECOGNITION_VIDEO' | 'MEDIAINFO' | 'TRANSCODE' | 'TRANSCODE_AUDIO' | 'TRANSCODE_IMAGE' | 'TRANSCODE_KEYFRAMES' | 'TRANSCODE_VIDEO' | 'TRANSCRIBE' | 'TRANSCRIBE_HUMAN';
    percent_done?: number | null;
    source_bytes?: number | null;
    status: 'ABORTED' | 'FAILED' | 'FINISHED';
    readonly system_domain_id?: string;
    system_name: string;
    time?: string;
    transcoder_type: 'AMAZON_REKOGNITION_IMAGE' | 'AMAZON_REKOGNITION_VIDEO' | 'AMAZON_TRANSCRIBE' | 'COLLECTION_KEYFRAMES' | 'ELEMENTAL_MEDIACONVERT' | 'ELEMENTAL_SERVER' | 'ENCODING_COM' | 'FACE_RECOGNITION' | 'FFMPEG' | 'FFMPEG_FIRST_FRAME' | 'FLICS' | 'GCVI_TRANSCRIPTION' | 'GOOGLE_VIDEO_INTELLIGENCE' | 'GOOGLE_VISION' | 'ICONIK_EDGE_TRANSCODER' | 'IMAGEMAGICK' | 'LIBREOFFICE' | 'MEDIAINFO' | 'NONE' | 'OPEN_GRAPH' | 'REV_AI_TRANSCRIPTION' | 'SUBTITLES' | 'TELESTREAM_CLOUD' | 'VANTAGE' | 'WILDMOKA' | 'ZENCODER';
};

export type TranscoderUsagesElasticSchema = {
    count?: number;
    date?: string;
    destination_bytes?: number;
    duration_seconds?: number;
    readonly id?: string;
    is_user_transcoder?: boolean;
    operation_type?: 'ANALYZE' | 'CONFORM' | 'EXTRACT_AUDIO' | 'EXTRACT_IMAGE' | 'FACE_RECOGNITION_IMAGE' | 'FACE_RECOGNITION_VIDEO' | 'MEDIAINFO' | 'TRANSCODE' | 'TRANSCODE_AUDIO' | 'TRANSCODE_IMAGE' | 'TRANSCODE_KEYFRAMES' | 'TRANSCODE_VIDEO' | 'TRANSCRIBE' | 'TRANSCRIBE_HUMAN';
    source_bytes?: number;
    system_domain_id?: string;
    transcoder_type: 'AMAZON_REKOGNITION_IMAGE' | 'AMAZON_REKOGNITION_VIDEO' | 'AMAZON_TRANSCRIBE' | 'COLLECTION_KEYFRAMES' | 'ELEMENTAL_MEDIACONVERT' | 'ELEMENTAL_SERVER' | 'ENCODING_COM' | 'FACE_RECOGNITION' | 'FFMPEG' | 'FFMPEG_FIRST_FRAME' | 'FLICS' | 'GCVI_TRANSCRIPTION' | 'GOOGLE_VIDEO_INTELLIGENCE' | 'GOOGLE_VISION' | 'ICONIK_EDGE_TRANSCODER' | 'IMAGEMAGICK' | 'LIBREOFFICE' | 'MEDIAINFO' | 'NONE' | 'OPEN_GRAPH' | 'REV_AI_TRANSCRIPTION' | 'SUBTITLES' | 'TELESTREAM_CLOUD' | 'VANTAGE' | 'WILDMOKA' | 'ZENCODER';
};

export type TranscoderUsagesSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<TranscoderUsagesElasticSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type TransferStatsSchema = {
    bytes_sent: number;
    ip?: string;
    object_info?: string;
    object_name?: string;
    time_taken_us?: number;
};

export type UnpublishedUserAuditSchema = {
    app_id?: string;
    client_ip?: string;
    date?: string;
    readonly id?: string;
    is_acting_as_user?: boolean;
    log_recipient_id: string;
    metadata?: string;
    operation_result?: number;
    operation_type: 'DELETE' | 'GET' | 'OPTIONS' | 'PATCH' | 'POST' | 'PUT';
    original_user_id?: string;
    payload?: string;
    request_id?: string;
    resource?: string;
    share_id?: string;
    share_user_id?: string;
    sudo?: boolean;
    system_domain_id?: string;
    system_name: string;
    time?: string;
    user_agent?: string;
    user_id?: string;
};

export type UserAuditSchema = {
    app_id?: string;
    client_ip?: string;
    date?: string;
    readonly id?: string;
    is_acting_as_user?: boolean;
    metadata?: string;
    operation_result?: number;
    operation_type: 'DELETE' | 'GET' | 'OPTIONS' | 'PATCH' | 'POST' | 'PUT';
    original_user_id?: string;
    payload?: string;
    request_id?: string;
    resource?: string;
    share_id?: string;
    share_user_id?: string;
    sudo?: boolean;
    system_domain_id?: string;
    system_name: string;
    time?: string;
    user_agent?: string;
    user_id?: string;
};

export type UserUsagesDetailedSchema = {
    date?: string;
    system_domain_id?: string;
    type?: string;
    user_id?: string;
};

export type UserUsagesElasticSchema = {
    count?: number;
    date?: string;
    readonly id?: string;
    system_domain_id?: string;
    type?: string;
    user_email?: string;
    user_id?: string;
    user_name?: string;
};

export type UserUsagesSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<UserUsagesElasticSchema>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly total?: number;
};

export type AssetUsageSchemaWritable = {
    asset_id: string;
    asset_type?: 'ASSET' | 'NLE_PROJECT' | 'PLACEHOLDER' | 'SEQUENCE';
    date?: string;
    metadata?: string;
    operation_source?: '' | 'COLLECTION' | 'DISCOVERY' | 'EXTERNAL_SHARE' | 'NOTIFICATION' | 'SEARCH' | 'SHARE';
    operation_type: 'APPROVE' | 'COMMENT' | 'CREATE' | 'DELETE' | 'EXIT' | 'PAUSE' | 'PLAY' | 'REFOCUS' | 'REJECT' | 'RENAME' | 'SEEK' | 'UNFOCUS' | 'VIEW';
    system_name: string;
    time?: string;
    user_id: string;
};

export type AssetUsagesElasticSchemaWritable = {
    count?: number;
    date?: string;
    system_domain_id?: string;
};

export type AssetUsagesSchemaWritable = {
    [key: string]: unknown;
};

export type BillingCreditsSchemaWritable = {
    auto_pay?: boolean;
    credits: number;
    custom_message?: string;
};

export type BillingCreditsVerifySchemaWritable = {
    invoice_id: string;
};

export type BillingSchemaWritable = {
    balance?: number;
    consumption_subtype?: string;
    consumption_type?: string;
    currency?: 'EUR' | 'USD';
    date?: string;
    expiration_date?: string | null;
    label: string;
    price_list?: string | null;
    system_domain_id: string;
    value: number;
};

export type BillingsSchemaWritable = {
    [key: string]: unknown;
};

export type CollectionUsageSchemaWritable = {
    collection_id: string;
    date?: string;
    metadata?: string;
    operation_source?: 'COLLECTION' | 'NOTIFICATION' | 'SEARCH';
    operation_type: 'CREATE' | 'DELETE' | 'RENAME' | 'VIEW';
    system_domain_id?: string;
    system_name: string;
    time?: string;
    user_id: string;
};

export type CollectionUsagesElasticSchemaWritable = {
    count?: number;
    date?: string;
    system_domain_id?: string;
};

export type CollectionUsagesSchemaWritable = {
    [key: string]: unknown;
};

export type CreditsSchemaWritable = {
    credits: number;
};

export type LogsRecipientReadSchemaWritable = {
    method: 'AMAZON' | 'GOOGLE';
    name: string;
};

export type LogsRecipientSchemaWritable = {
    method: 'AMAZON' | 'GOOGLE';
    name: string;
};

export type LogsRecipientsSchemaWritable = {
    [key: string]: unknown;
};

export type PricesSchemaWritable = {
    [key: string]: unknown;
};

export type StorageAccessElasticSchemaWritable = {
    bucket_name?: string;
    bytes_received?: number;
    bytes_sent?: number;
    date?: string;
    operations?: number;
    system_domain_id?: string;
};

export type StorageAccessSchemaWritable = {
    bucket_name: string;
    bytes_received?: number;
    bytes_sent?: number;
    date?: string;
    operation_type: string;
    operations?: number;
    storage_type: 'AZURE' | 'B2' | 'FILE' | 'FTP' | 'GCS' | 'HTTP' | 'OMMS' | 'S3' | 'SFTP' | 'TRANSFER';
    system_domain_id?: string;
    system_name: string;
};

export type StorageAccessesSchemaWritable = {
    [key: string]: unknown;
};

export type StorageUsageSchemaWritable = {
    bucket_name: string;
    bytes_stored?: number;
    date?: string;
    storage_type: 'AZURE' | 'B2' | 'FILE' | 'FTP' | 'GCS' | 'HTTP' | 'OMMS' | 'S3' | 'SFTP' | 'TRANSFER';
    system_domain_id?: string;
    system_name: string;
};

export type StorageUsagesElasticSchemaWritable = {
    bucket_name?: string;
    bytes_stored?: number;
    date?: string;
    system_domain_id?: string;
};

export type StorageUsagesSchemaWritable = {
    [key: string]: unknown;
};

export type TranscoderUsageSchemaWritable = {
    adjusted_duration_seconds?: number | null;
    date?: string;
    destination_bytes?: number | null;
    duration_seconds?: number | null;
    is_user_transcoder?: boolean;
    job_id?: string | null;
    object_id?: string | null;
    object_type?: string | null;
    operation_type?: 'ANALYZE' | 'CONFORM' | 'EXTRACT_AUDIO' | 'EXTRACT_IMAGE' | 'FACE_RECOGNITION_IMAGE' | 'FACE_RECOGNITION_VIDEO' | 'MEDIAINFO' | 'TRANSCODE' | 'TRANSCODE_AUDIO' | 'TRANSCODE_IMAGE' | 'TRANSCODE_KEYFRAMES' | 'TRANSCODE_VIDEO' | 'TRANSCRIBE' | 'TRANSCRIBE_HUMAN';
    percent_done?: number | null;
    source_bytes?: number | null;
    status: 'ABORTED' | 'FAILED' | 'FINISHED';
    system_name: string;
    time?: string;
    transcoder_type: 'AMAZON_REKOGNITION_IMAGE' | 'AMAZON_REKOGNITION_VIDEO' | 'AMAZON_TRANSCRIBE' | 'COLLECTION_KEYFRAMES' | 'ELEMENTAL_MEDIACONVERT' | 'ELEMENTAL_SERVER' | 'ENCODING_COM' | 'FACE_RECOGNITION' | 'FFMPEG' | 'FFMPEG_FIRST_FRAME' | 'FLICS' | 'GCVI_TRANSCRIPTION' | 'GOOGLE_VIDEO_INTELLIGENCE' | 'GOOGLE_VISION' | 'ICONIK_EDGE_TRANSCODER' | 'IMAGEMAGICK' | 'LIBREOFFICE' | 'MEDIAINFO' | 'NONE' | 'OPEN_GRAPH' | 'REV_AI_TRANSCRIPTION' | 'SUBTITLES' | 'TELESTREAM_CLOUD' | 'VANTAGE' | 'WILDMOKA' | 'ZENCODER';
};

export type TranscoderUsagesElasticSchemaWritable = {
    count?: number;
    date?: string;
    destination_bytes?: number;
    duration_seconds?: number;
    is_user_transcoder?: boolean;
    operation_type?: 'ANALYZE' | 'CONFORM' | 'EXTRACT_AUDIO' | 'EXTRACT_IMAGE' | 'FACE_RECOGNITION_IMAGE' | 'FACE_RECOGNITION_VIDEO' | 'MEDIAINFO' | 'TRANSCODE' | 'TRANSCODE_AUDIO' | 'TRANSCODE_IMAGE' | 'TRANSCODE_KEYFRAMES' | 'TRANSCODE_VIDEO' | 'TRANSCRIBE' | 'TRANSCRIBE_HUMAN';
    source_bytes?: number;
    system_domain_id?: string;
    transcoder_type: 'AMAZON_REKOGNITION_IMAGE' | 'AMAZON_REKOGNITION_VIDEO' | 'AMAZON_TRANSCRIBE' | 'COLLECTION_KEYFRAMES' | 'ELEMENTAL_MEDIACONVERT' | 'ELEMENTAL_SERVER' | 'ENCODING_COM' | 'FACE_RECOGNITION' | 'FFMPEG' | 'FFMPEG_FIRST_FRAME' | 'FLICS' | 'GCVI_TRANSCRIPTION' | 'GOOGLE_VIDEO_INTELLIGENCE' | 'GOOGLE_VISION' | 'ICONIK_EDGE_TRANSCODER' | 'IMAGEMAGICK' | 'LIBREOFFICE' | 'MEDIAINFO' | 'NONE' | 'OPEN_GRAPH' | 'REV_AI_TRANSCRIPTION' | 'SUBTITLES' | 'TELESTREAM_CLOUD' | 'VANTAGE' | 'WILDMOKA' | 'ZENCODER';
};

export type TranscoderUsagesSchemaWritable = {
    [key: string]: unknown;
};

export type UnpublishedUserAuditSchemaWritable = {
    app_id?: string;
    client_ip?: string;
    date?: string;
    is_acting_as_user?: boolean;
    log_recipient_id: string;
    metadata?: string;
    operation_result?: number;
    operation_type: 'DELETE' | 'GET' | 'OPTIONS' | 'PATCH' | 'POST' | 'PUT';
    original_user_id?: string;
    payload?: string;
    request_id?: string;
    resource?: string;
    share_id?: string;
    share_user_id?: string;
    sudo?: boolean;
    system_domain_id?: string;
    system_name: string;
    time?: string;
    user_agent?: string;
    user_id?: string;
};

export type UserAuditSchemaWritable = {
    app_id?: string;
    client_ip?: string;
    date?: string;
    is_acting_as_user?: boolean;
    metadata?: string;
    operation_result?: number;
    operation_type: 'DELETE' | 'GET' | 'OPTIONS' | 'PATCH' | 'POST' | 'PUT';
    original_user_id?: string;
    payload?: string;
    request_id?: string;
    resource?: string;
    share_id?: string;
    share_user_id?: string;
    sudo?: boolean;
    system_domain_id?: string;
    system_name: string;
    time?: string;
    user_agent?: string;
    user_id?: string;
};

export type UserUsagesElasticSchemaWritable = {
    count?: number;
    date?: string;
    system_domain_id?: string;
    type?: string;
    user_email?: string;
    user_id?: string;
    user_name?: string;
};

export type UserUsagesSchemaWritable = {
    [key: string]: unknown;
};

export type PostAssetsData = {
    /**
     * body
     */
    body: AssetUsageSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/assets/';
};

export type PostAssetsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostAssetsError = PostAssetsErrors[keyof PostAssetsErrors];

export type PostAssetsResponses = {
    /**
     * Usage entered
     */
    201: AssetUsageSchema;
};

export type PostAssetsResponse = PostAssetsResponses[keyof PostAssetsResponses];

export type GetAssetsByByPeriodData = {
    body?: never;
    path: {
        /**
         * Period of stats (month or day)
         */
        period: string;
    };
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by to_date
         */
        to_date?: string;
    };
    url: '/v1/assets/by/{period}/';
};

export type GetAssetsByByPeriodErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetAssetsByByPeriodError = GetAssetsByByPeriodErrors[keyof GetAssetsByByPeriodErrors];

export type GetAssetsByByPeriodResponses = {
    /**
     * Returns asset usage
     */
    200: AssetUsageSchema;
};

export type GetAssetsByByPeriodResponse = GetAssetsByByPeriodResponses[keyof GetAssetsByByPeriodResponses];

export type GetAutomationsUsageByDayData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by to_date
         */
        to_date?: string;
    };
    url: '/v1/automations/usage/by/day/';
};

export type GetAutomationsUsageByDayErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetAutomationsUsageByDayError = GetAutomationsUsageByDayErrors[keyof GetAutomationsUsageByDayErrors];

export type GetAutomationsUsageByDayResponses = {
    /**
     * Returns automation runs by day
     */
    200: AutomationRunsSchema;
};

export type GetAutomationsUsageByDayResponse = GetAutomationsUsageByDayResponses[keyof GetAutomationsUsageByDayResponses];

export type GetBillingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by from_date
         */
        to_date?: string;
        /**
         * The number of items for each page
         */
        per_page?: number;
        /**
         * ID of a last file on previous page
         */
        last_id?: string;
    };
    url: '/v1/billing/';
};

export type GetBillingErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingError = GetBillingErrors[keyof GetBillingErrors];

export type GetBillingResponses = {
    /**
     * Returns billing data
     */
    200: BillingsSchema;
};

export type GetBillingResponse = GetBillingResponses[keyof GetBillingResponses];

export type PostBillingData = {
    /**
     * body
     */
    body: BillingSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/billing/';
};

export type PostBillingErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostBillingError = PostBillingErrors[keyof PostBillingErrors];

export type PostBillingResponses = {
    /**
     * Usage entered
     */
    201: BillingSchema;
};

export type PostBillingResponse = PostBillingResponses[keyof PostBillingResponses];

export type GetBillingChargesByChargeIdReceiptUrlData = {
    body?: never;
    path: {
        charge_id: string;
    };
    query?: never;
    url: '/v1/billing/charges/{charge_id}/receipt_url/';
};

export type GetBillingChargesByChargeIdReceiptUrlErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingChargesByChargeIdReceiptUrlError = GetBillingChargesByChargeIdReceiptUrlErrors[keyof GetBillingChargesByChargeIdReceiptUrlErrors];

export type GetBillingChargesByChargeIdReceiptUrlResponses = {
    /**
     * Billing receipts
     */
    200: BillingReceiptSchema;
};

export type GetBillingChargesByChargeIdReceiptUrlResponse = GetBillingChargesByChargeIdReceiptUrlResponses[keyof GetBillingChargesByChargeIdReceiptUrlResponses];

export type PostBillingCreditsData = {
    /**
     * body
     */
    body: BillingCreditsSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/billing/credits/';
};

export type PostBillingCreditsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostBillingCreditsError = PostBillingCreditsErrors[keyof PostBillingCreditsErrors];

export type PostBillingCreditsResponses = {
    /**
     * Credits entered
     */
    201: BillingCreditsSchema;
};

export type PostBillingCreditsResponse = PostBillingCreditsResponses[keyof PostBillingCreditsResponses];

export type GetBillingCreditsPriceData = {
    body?: never;
    path?: never;
    query: {
        credits: number;
    };
    url: '/v1/billing/credits/price/';
};

export type GetBillingCreditsPriceErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingCreditsPriceError = GetBillingCreditsPriceErrors[keyof GetBillingCreditsPriceErrors];

export type GetBillingCreditsPriceResponses = {
    /**
     * Credits entered
     */
    201: CreditsSchema;
};

export type GetBillingCreditsPriceResponse = GetBillingCreditsPriceResponses[keyof GetBillingCreditsPriceResponses];

export type PostBillingCreditsVerifyData = {
    /**
     * body
     */
    body: BillingCreditsVerifySchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/billing/credits/verify/';
};

export type PostBillingCreditsVerifyErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostBillingCreditsVerifyError = PostBillingCreditsVerifyErrors[keyof PostBillingCreditsVerifyErrors];

export type PostBillingCreditsVerifyResponses = {
    /**
     * Credits entered
     */
    201: BillingCreditsVerifySchema;
};

export type PostBillingCreditsVerifyResponse = PostBillingCreditsVerifyResponses[keyof PostBillingCreditsVerifyResponses];

export type GetBillingCustomerData = {
    /**
     * body
     */
    body: BillingSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/billing/customer/';
};

export type GetBillingCustomerErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingCustomerError = GetBillingCustomerErrors[keyof GetBillingCustomerErrors];

export type GetBillingCustomerResponses = {
    /**
     * Usage entered
     */
    201: BillingSchema;
};

export type GetBillingCustomerResponse = GetBillingCustomerResponses[keyof GetBillingCustomerResponses];

export type PostBillingCustomerData = {
    /**
     * body
     */
    body: BillingCustomerSchema;
    path?: never;
    query?: never;
    url: '/v1/billing/customer/';
};

export type PostBillingCustomerErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostBillingCustomerError = PostBillingCustomerErrors[keyof PostBillingCustomerErrors];

export type PostBillingCustomerResponses = {
    /**
     * Usage entered
     */
    201: BillingCustomerSchema;
};

export type PostBillingCustomerResponse = PostBillingCustomerResponses[keyof PostBillingCustomerResponses];

export type DeleteBillingCustomerCardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/billing/customer/card/';
};

export type DeleteBillingCustomerCardErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteBillingCustomerCardError = DeleteBillingCustomerCardErrors[keyof DeleteBillingCustomerCardErrors];

export type DeleteBillingCustomerCardResponses = {
    /**
     * Card deleted
     */
    200: unknown;
};

export type PostBillingCustomerCardData = {
    /**
     * body
     */
    body: BillingCustomerCardSchema;
    path?: never;
    query?: never;
    url: '/v1/billing/customer/card/';
};

export type PostBillingCustomerCardErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostBillingCustomerCardError = PostBillingCustomerCardErrors[keyof PostBillingCustomerCardErrors];

export type PostBillingCustomerCardResponses = {
    /**
     * Usage entered
     */
    201: BillingCustomerCardSchema;
};

export type PostBillingCustomerCardResponse = PostBillingCustomerCardResponses[keyof PostBillingCustomerCardResponses];

export type GetBillingInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        starting_after?: string;
        limit?: number;
    };
    url: '/v1/billing/invoices/';
};

export type GetBillingInvoicesErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingInvoicesError = GetBillingInvoicesErrors[keyof GetBillingInvoicesErrors];

export type GetBillingInvoicesResponses = {
    /**
     * Billing invoices
     */
    200: unknown;
};

export type GetBillingPriceListsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/billing/price_lists/';
};

export type GetBillingPriceListsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingPriceListsError = GetBillingPriceListsErrors[keyof GetBillingPriceListsErrors];

export type GetBillingPriceListsResponses = {
    /**
     * Prices
     */
    200: PricesSchema;
};

export type GetBillingPriceListsResponse = GetBillingPriceListsResponses[keyof GetBillingPriceListsResponses];

export type PutBillingPriceListsData = {
    /**
     * body
     */
    body: PriceSchema;
    path?: never;
    query?: never;
    url: '/v1/billing/price_lists/';
};

export type PutBillingPriceListsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutBillingPriceListsError = PutBillingPriceListsErrors[keyof PutBillingPriceListsErrors];

export type PutBillingPriceListsResponses = {
    /**
     * Prices
     */
    200: PriceSchema;
};

export type PutBillingPriceListsResponse = PutBillingPriceListsResponses[keyof PutBillingPriceListsResponses];

export type DeleteBillingPriceListsByNameByCurrencyData = {
    body?: never;
    path: {
        name: string;
        currency: string;
    };
    query?: never;
    url: '/v1/billing/price_lists/{name}/{currency}/';
};

export type DeleteBillingPriceListsByNameByCurrencyErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteBillingPriceListsByNameByCurrencyError = DeleteBillingPriceListsByNameByCurrencyErrors[keyof DeleteBillingPriceListsByNameByCurrencyErrors];

export type DeleteBillingPriceListsByNameByCurrencyResponses = {
    /**
     * No body
     */
    204: void;
};

export type DeleteBillingPriceListsByNameByCurrencyResponse = DeleteBillingPriceListsByNameByCurrencyResponses[keyof DeleteBillingPriceListsByNameByCurrencyResponses];

export type GetBillingPriceListsByNameByCurrencyData = {
    body?: never;
    path: {
        name: string;
        currency: string;
    };
    query?: never;
    url: '/v1/billing/price_lists/{name}/{currency}/';
};

export type GetBillingPriceListsByNameByCurrencyErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingPriceListsByNameByCurrencyError = GetBillingPriceListsByNameByCurrencyErrors[keyof GetBillingPriceListsByNameByCurrencyErrors];

export type GetBillingPriceListsByNameByCurrencyResponses = {
    /**
     * Prices
     */
    200: PriceSchema;
};

export type GetBillingPriceListsByNameByCurrencyResponse = GetBillingPriceListsByNameByCurrencyResponses[keyof GetBillingPriceListsByNameByCurrencyResponses];

export type GetBillingRecipientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/billing/recipients/';
};

export type GetBillingRecipientsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingRecipientsError = GetBillingRecipientsErrors[keyof GetBillingRecipientsErrors];

export type GetBillingRecipientsResponses = {
    /**
     * Email recipients
     */
    200: BillingRecipientsSchema;
};

export type GetBillingRecipientsResponse = GetBillingRecipientsResponses[keyof GetBillingRecipientsResponses];

export type PutBillingRecipientsData = {
    /**
     * body
     */
    body: BillingRecipientsSchema;
    path?: never;
    query?: never;
    url: '/v1/billing/recipients/';
};

export type PutBillingRecipientsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutBillingRecipientsError = PutBillingRecipientsErrors[keyof PutBillingRecipientsErrors];

export type PutBillingRecipientsResponses = {
    /**
     * Email recipients
     */
    201: BillingRecipientsSchema;
};

export type PutBillingRecipientsResponse = PutBillingRecipientsResponses[keyof PutBillingRecipientsResponses];

export type GetBillingSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/billing/settings/';
};

export type GetBillingSettingsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingSettingsError = GetBillingSettingsErrors[keyof GetBillingSettingsErrors];

export type GetBillingSettingsResponses = {
    /**
     * Email recipients
     */
    200: BillingSettingsSchema;
};

export type GetBillingSettingsResponse = GetBillingSettingsResponses[keyof GetBillingSettingsResponses];

export type PutBillingSettingsData = {
    /**
     * body
     */
    body: BillingSettingsSchema;
    path?: never;
    query?: never;
    url: '/v1/billing/settings/';
};

export type PutBillingSettingsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutBillingSettingsError = PutBillingSettingsErrors[keyof PutBillingSettingsErrors];

export type PutBillingSettingsResponses = {
    /**
     * Email recipients
     */
    201: BillingSettingsSchema;
};

export type PutBillingSettingsResponse = PutBillingSettingsResponses[keyof PutBillingSettingsResponses];

export type GetBillingStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/billing/status/';
};

export type GetBillingStatusErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingStatusError = GetBillingStatusErrors[keyof GetBillingStatusErrors];

export type GetBillingStatusResponses = {
    /**
     * Billing status
     */
    200: BillingStatsSchema;
};

export type GetBillingStatusResponse = GetBillingStatusResponses[keyof GetBillingStatusResponses];

export type DeleteBillingBySystemDomainIdByBillingIdData = {
    body?: never;
    path: {
        system_domain_id: string;
        billing_id: string;
    };
    query?: never;
    url: '/v1/billing/{system_domain_id}/{billing_id}/';
};

export type DeleteBillingBySystemDomainIdByBillingIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteBillingBySystemDomainIdByBillingIdError = DeleteBillingBySystemDomainIdByBillingIdErrors[keyof DeleteBillingBySystemDomainIdByBillingIdErrors];

export type DeleteBillingBySystemDomainIdByBillingIdResponses = {
    /**
     * Usage deleted
     */
    204: void;
};

export type DeleteBillingBySystemDomainIdByBillingIdResponse = DeleteBillingBySystemDomainIdByBillingIdResponses[keyof DeleteBillingBySystemDomainIdByBillingIdResponses];

export type GetBillingExpirationData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of items for each page
         */
        per_page?: number;
    };
    url: '/v1/billing_expiration/';
};

export type GetBillingExpirationErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetBillingExpirationError = GetBillingExpirationErrors[keyof GetBillingExpirationErrors];

export type GetBillingExpirationResponses = {
    /**
     * Returns billing data
     */
    200: BillingsSchema;
};

export type GetBillingExpirationResponse = GetBillingExpirationResponses[keyof GetBillingExpirationResponses];

export type DeleteBillingExpirationBySystemDomainIdByBillingIdData = {
    body?: never;
    path: {
        system_domain_id: string;
        billing_id: string;
    };
    query?: never;
    url: '/v1/billing_expiration/{system_domain_id}/{billing_id}/';
};

export type DeleteBillingExpirationBySystemDomainIdByBillingIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteBillingExpirationBySystemDomainIdByBillingIdError = DeleteBillingExpirationBySystemDomainIdByBillingIdErrors[keyof DeleteBillingExpirationBySystemDomainIdByBillingIdErrors];

export type DeleteBillingExpirationBySystemDomainIdByBillingIdResponses = {
    /**
     * Billing expiration deleted
     */
    204: void;
};

export type DeleteBillingExpirationBySystemDomainIdByBillingIdResponse = DeleteBillingExpirationBySystemDomainIdByBillingIdResponses[keyof DeleteBillingExpirationBySystemDomainIdByBillingIdResponses];

export type PutBillingExpirationBySystemDomainIdByBillingIdData = {
    /**
     * body
     */
    body: BillingExpirationUpdateSchema;
    path: {
        system_domain_id: string;
        billing_id: string;
    };
    query?: never;
    url: '/v1/billing_expiration/{system_domain_id}/{billing_id}/';
};

export type PutBillingExpirationBySystemDomainIdByBillingIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutBillingExpirationBySystemDomainIdByBillingIdError = PutBillingExpirationBySystemDomainIdByBillingIdErrors[keyof PutBillingExpirationBySystemDomainIdByBillingIdErrors];

export type PutBillingExpirationBySystemDomainIdByBillingIdResponses = {
    /**
     * Billing expiration updated
     */
    200: BillingSchema;
};

export type PutBillingExpirationBySystemDomainIdByBillingIdResponse = PutBillingExpirationBySystemDomainIdByBillingIdResponses[keyof PutBillingExpirationBySystemDomainIdByBillingIdResponses];

export type GetCollectionsByByPeriodData = {
    body?: never;
    path: {
        /**
         * Period of stats (month or day)
         */
        period: string;
    };
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by to_date
         */
        to_date?: string;
    };
    url: '/v1/collections/by/{period}/';
};

export type GetCollectionsByByPeriodErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetCollectionsByByPeriodError = GetCollectionsByByPeriodErrors[keyof GetCollectionsByByPeriodErrors];

export type GetCollectionsByByPeriodResponses = {
    /**
     * Returns Collection usage
     */
    200: CollectionUsageSchema;
};

export type GetCollectionsByByPeriodResponse = GetCollectionsByByPeriodResponses[keyof GetCollectionsByByPeriodResponses];

export type GetCurrentUsageData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of items for each page
         */
        per_page?: number;
    };
    url: '/v1/current_usage/';
};

export type GetCurrentUsageErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetCurrentUsageError = GetCurrentUsageErrors[keyof GetCurrentUsageErrors];

export type GetCurrentUsageResponses = {
    /**
     * Returns current usage
     */
    200: CurrentUsageSchema;
};

export type GetCurrentUsageResponse = GetCurrentUsageResponses[keyof GetCurrentUsageResponses];

export type GetIdByObjectIdInfoData = {
    body?: never;
    path: {
        /**
         * Object ID
         */
        object_id: string;
    };
    query?: never;
    url: '/v1/id/{object_id}/info/';
};

export type GetIdByObjectIdInfoErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetIdByObjectIdInfoError = GetIdByObjectIdInfoErrors[keyof GetIdByObjectIdInfoErrors];

export type GetIdByObjectIdInfoResponses = {
    /**
     * Returns asset usage
     */
    200: unknown;
};

export type GetOrdwayBillingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by from_date
         */
        to_date?: string;
        /**
         * The number of items for each page
         */
        per_page?: number;
        /**
         * Which page number to fetch
         */
        page?: number;
    };
    url: '/v1/ordway/billing/';
};

export type GetOrdwayBillingErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetOrdwayBillingError = GetOrdwayBillingErrors[keyof GetOrdwayBillingErrors];

export type GetOrdwayBillingResponses = {
    /**
     * Returns billing data
     */
    200: BillingsSchema;
};

export type GetOrdwayBillingResponse = GetOrdwayBillingResponses[keyof GetOrdwayBillingResponses];

export type GetOrdwayBillingCustomerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/ordway/billing/customer/';
};

export type GetOrdwayBillingCustomerErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetOrdwayBillingCustomerError = GetOrdwayBillingCustomerErrors[keyof GetOrdwayBillingCustomerErrors];

export type GetOrdwayBillingCustomerResponses = {
    /**
     * Usage entered
     */
    201: BillingSchema;
};

export type GetOrdwayBillingCustomerResponse = GetOrdwayBillingCustomerResponses[keyof GetOrdwayBillingCustomerResponses];

export type GetOrdwayBillingInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of items for each page
         */
        per_page?: number;
        /**
         * Which page number to fetch
         */
        page?: number;
    };
    url: '/v1/ordway/billing/invoices/';
};

export type GetOrdwayBillingInvoicesErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetOrdwayBillingInvoicesError = GetOrdwayBillingInvoicesErrors[keyof GetOrdwayBillingInvoicesErrors];

export type GetOrdwayBillingInvoicesResponses = {
    /**
     * Billing invoices
     */
    200: unknown;
};

export type GetPaygoCostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/paygo_costs/';
};

export type GetPaygoCostsErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetPaygoCostsError = GetPaygoCostsErrors[keyof GetPaygoCostsErrors];

export type GetPaygoCostsResponses = {
    /**
     * Returns billing data
     */
    200: PaygoCostsSchema;
};

export type GetPaygoCostsResponse = GetPaygoCostsResponses[keyof GetPaygoCostsResponses];

export type GetStorageAccessByByPeriodData = {
    body?: never;
    path: {
        /**
         * Period of stats (month or day)
         */
        period: string;
    };
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by to_date
         */
        to_date?: string;
    };
    url: '/v1/storage/access/by/{period}/';
};

export type GetStorageAccessByByPeriodErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetStorageAccessByByPeriodError = GetStorageAccessByByPeriodErrors[keyof GetStorageAccessByByPeriodErrors];

export type GetStorageAccessByByPeriodResponses = {
    /**
     * Returns a object for storage access
     */
    200: StorageAccessesSchema;
};

export type GetStorageAccessByByPeriodResponse = GetStorageAccessByByPeriodResponses[keyof GetStorageAccessByByPeriodResponses];

export type GetStorageUsageByByPeriodData = {
    body?: never;
    path: {
        /**
         * Period of stats (month or day)
         */
        period: string;
    };
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by to_date
         */
        to_date?: string;
    };
    url: '/v1/storage/usage/by/{period}/';
};

export type GetStorageUsageByByPeriodErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetStorageUsageByByPeriodError = GetStorageUsageByByPeriodErrors[keyof GetStorageUsageByByPeriodErrors];

export type GetStorageUsageByByPeriodResponses = {
    /**
     * Returns storage usage
     */
    200: StorageUsagesSchema;
};

export type GetStorageUsageByByPeriodResponse = GetStorageUsageByByPeriodResponses[keyof GetStorageUsageByByPeriodResponses];

export type GetSystemLogsRecipientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of items for each page
         */
        per_page?: number;
        /**
         * ID of a last service account set on previous page
         */
        last_id?: string;
    };
    url: '/v1/system/logs/recipients/';
};

export type GetSystemLogsRecipientsErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Logs recipients settings don't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetSystemLogsRecipientsError = GetSystemLogsRecipientsErrors[keyof GetSystemLogsRecipientsErrors];

export type GetSystemLogsRecipientsResponses = {
    /**
     * Returns logs recipients settings
     */
    200: LogsRecipientsSchema;
};

export type GetSystemLogsRecipientsResponse = GetSystemLogsRecipientsResponses[keyof GetSystemLogsRecipientsResponses];

export type PostSystemLogsRecipientsData = {
    /**
     * body
     */
    body: LogsRecipientSchemaWritable;
    path?: never;
    query?: never;
    url: '/v1/system/logs/recipients/';
};

export type PostSystemLogsRecipientsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostSystemLogsRecipientsError = PostSystemLogsRecipientsErrors[keyof PostSystemLogsRecipientsErrors];

export type PostSystemLogsRecipientsResponses = {
    /**
     * Returns a logs_recipient object
     */
    201: LogsRecipientReadSchema;
};

export type PostSystemLogsRecipientsResponse = PostSystemLogsRecipientsResponses[keyof PostSystemLogsRecipientsResponses];

export type DeleteSystemLogsRecipientsByLogsRecipientIdData = {
    body?: never;
    path: {
        logs_recipient_id: string;
    };
    query?: never;
    url: '/v1/system/logs/recipients/{logs_recipient_id}/';
};

export type DeleteSystemLogsRecipientsByLogsRecipientIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Logs recipient doesn't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteSystemLogsRecipientsByLogsRecipientIdError = DeleteSystemLogsRecipientsByLogsRecipientIdErrors[keyof DeleteSystemLogsRecipientsByLogsRecipientIdErrors];

export type DeleteSystemLogsRecipientsByLogsRecipientIdResponses = {
    /**
     * Without body
     */
    204: void;
};

export type DeleteSystemLogsRecipientsByLogsRecipientIdResponse = DeleteSystemLogsRecipientsByLogsRecipientIdResponses[keyof DeleteSystemLogsRecipientsByLogsRecipientIdResponses];

export type GetSystemLogsRecipientsByLogsRecipientIdData = {
    body?: never;
    path: {
        logs_recipient_id: string;
    };
    query?: never;
    url: '/v1/system/logs/recipients/{logs_recipient_id}/';
};

export type GetSystemLogsRecipientsByLogsRecipientIdErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Logs recipients settings don't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetSystemLogsRecipientsByLogsRecipientIdError = GetSystemLogsRecipientsByLogsRecipientIdErrors[keyof GetSystemLogsRecipientsByLogsRecipientIdErrors];

export type GetSystemLogsRecipientsByLogsRecipientIdResponses = {
    /**
     * Returns settings for a logs recipients
     */
    200: LogsRecipientReadSchema;
};

export type GetSystemLogsRecipientsByLogsRecipientIdResponse = GetSystemLogsRecipientsByLogsRecipientIdResponses[keyof GetSystemLogsRecipientsByLogsRecipientIdResponses];

export type PatchSystemLogsRecipientsByLogsRecipientIdData = {
    /**
     * body
     */
    body: LogsRecipientSchemaWritable;
    path: {
        logs_recipient_id: string;
    };
    query?: never;
    url: '/v1/system/logs/recipients/{logs_recipient_id}/';
};

export type PatchSystemLogsRecipientsByLogsRecipientIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Logs recipient doesn't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchSystemLogsRecipientsByLogsRecipientIdError = PatchSystemLogsRecipientsByLogsRecipientIdErrors[keyof PatchSystemLogsRecipientsByLogsRecipientIdErrors];

export type PatchSystemLogsRecipientsByLogsRecipientIdResponses = {
    /**
     * Returns changed system settings
     */
    200: LogsRecipientReadSchema;
};

export type PatchSystemLogsRecipientsByLogsRecipientIdResponse = PatchSystemLogsRecipientsByLogsRecipientIdResponses[keyof PatchSystemLogsRecipientsByLogsRecipientIdResponses];

export type PostSystemLogsRecipientsByLogsRecipientIdData = {
    body?: never;
    path: {
        logs_recipient_id: string;
    };
    query?: never;
    url: '/v1/system/logs/recipients/{logs_recipient_id}/';
};

export type PostSystemLogsRecipientsByLogsRecipientIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Logs recipient doesn't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostSystemLogsRecipientsByLogsRecipientIdError = PostSystemLogsRecipientsByLogsRecipientIdErrors[keyof PostSystemLogsRecipientsByLogsRecipientIdErrors];

export type PostSystemLogsRecipientsByLogsRecipientIdResponses = {
    /**
     * Returns a document describing storage access
     */
    200: {
        access_check?: boolean;
        error_message?: string;
    };
};

export type PostSystemLogsRecipientsByLogsRecipientIdResponse = PostSystemLogsRecipientsByLogsRecipientIdResponses[keyof PostSystemLogsRecipientsByLogsRecipientIdResponses];

export type PutSystemLogsRecipientsByLogsRecipientIdData = {
    /**
     * body
     */
    body: LogsRecipientSchemaWritable;
    path: {
        logs_recipient_id: string;
    };
    query?: never;
    url: '/v1/system/logs/recipients/{logs_recipient_id}/';
};

export type PutSystemLogsRecipientsByLogsRecipientIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Logs recipient doesn't exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutSystemLogsRecipientsByLogsRecipientIdError = PutSystemLogsRecipientsByLogsRecipientIdErrors[keyof PutSystemLogsRecipientsByLogsRecipientIdErrors];

export type PutSystemLogsRecipientsByLogsRecipientIdResponses = {
    /**
     * Returns changed system settings
     */
    200: LogsRecipientReadSchema;
};

export type PutSystemLogsRecipientsByLogsRecipientIdResponse = PutSystemLogsRecipientsByLogsRecipientIdResponses[keyof PutSystemLogsRecipientsByLogsRecipientIdResponses];

export type GetTranscoderUsageByByPeriodData = {
    body?: never;
    path: {
        period: string;
    };
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by to_date
         */
        to_date?: string;
    };
    url: '/v1/transcoder/usage/by/{period}/';
};

export type GetTranscoderUsageByByPeriodErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetTranscoderUsageByByPeriodError = GetTranscoderUsageByByPeriodErrors[keyof GetTranscoderUsageByByPeriodErrors];

export type GetTranscoderUsageByByPeriodResponses = {
    /**
     * Returns a transcoder usage objects
     */
    200: TranscoderUsagesSchema;
};

export type GetTranscoderUsageByByPeriodResponse = GetTranscoderUsageByByPeriodResponses[keyof GetTranscoderUsageByByPeriodResponses];

export type GetUserAuditByByPeriodData = {
    body?: never;
    path: {
        /**
         * Period of stats (month, day or day_detailed)
         */
        period: string;
    };
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by to_date
         */
        to_date?: string;
        /**
         * Filter by system_domain_id (Only for super admins)
         */
        system_domain_id?: string;
    };
    url: '/v1/user/audit/by/{period}/';
};

export type GetUserAuditByByPeriodErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetUserAuditByByPeriodError = GetUserAuditByByPeriodErrors[keyof GetUserAuditByByPeriodErrors];

export type GetUserAuditByByPeriodResponses = {
    /**
     * Returns user usage
     */
    200: UserUsagesSchema;
};

export type GetUserAuditByByPeriodResponse = GetUserAuditByByPeriodResponses[keyof GetUserAuditByByPeriodResponses];

export type GetUserLicensedByData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by from_date
         */
        from_date?: string;
        /**
         * Filter by to_date
         */
        to_date?: string;
        /**
         * Filter by system_domain_id (Only for super admins)
         */
        system_domain_id?: string;
    };
    url: '/v1/user/licensed/by/';
};

export type GetUserLicensedByErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Requested page does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetUserLicensedByError = GetUserLicensedByErrors[keyof GetUserLicensedByErrors];

export type GetUserLicensedByResponses = {
    /**
     * Returns licensed user usage
     */
    200: UserUsagesSchema;
};

export type GetUserLicensedByResponse = GetUserLicensedByResponses[keyof GetUserLicensedByResponses];
