// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/API/ml/` | (string & {});
};

export type AssetVersionSchema = {
    asset_id?: string;
    face_ids?: Array<string>;
    segment_count?: number;
    version_id?: string;
};

export type BaseQueryParamsSchema = {
    /**
     * Which page number to fetch
     */
    page?: number | null;
    /**
     * The number of items for each page
     */
    per_page?: number | null;
    /**
     * A comma separated list of fieldnames with order (asc/desc)
     */
    sort?: string;
};

export type BulkConfirmPersonSchema = {
    all_instances_except_unconfirmed?: boolean;
    version_ids?: Array<string> | null;
};

export type BulkDeletePersonsByIdsSchema = {
    person_ids: Array<string>;
};

export type BulkDeletePersonsByVersionsSchema = {
    objects: Array<DeletePersonByVersion>;
};

export type BulkDeletePersonsSchema = {
    objects: Array<DeletePerson>;
};

export type BulkFaceExtractSchema = {
    face_image_analysis_profile_id?: string;
    face_video_analysis_profile_id?: string;
    force?: boolean;
    include_assets?: boolean;
    include_collections?: boolean;
    object_ids: Array<string>;
    object_type: 'assets' | 'collections' | 'saved_searches';
};

export type BulkPersonByAssetAndVersion = {
    persons?: Array<PersonByAssetAndVersion>;
    version_id: string;
};

export type BulkPersonByAssetAndVersionListSchema = {
    objects?: Array<BulkPersonByAssetAndVersion>;
};

export type BulkPersonByAssetAndVersionSchema = {
    persons?: Array<PersonByAssetAndVersion>;
    version_id: string;
};

export type BulkReindexPersonsSchema = {
    person_ids: Array<string>;
    sync_to_another_dc?: boolean;
};

export type ChangePersonInstanceSchema = {
    new_person_id?: string | null;
    new_person_name?: string | null;
};

export type CheckPersonsStatusSchema = {
    person_ids: Array<string>;
};

export type CopyPersonsSchema = {
    source_asset_id: string;
    source_version_id: string;
    target_asset_id: string;
    target_version_id: string;
};

export type CreatePersonSchema = {
    main_face_id?: string;
    name?: string | null;
};

export type DeletePerson = {
    asset_id: string;
    version_id: string;
};

export type DeletePersonByVersion = {
    person_id: string;
    version_id: string;
};

export type DeletePersonByVersionSchema = {
    person_id: string;
    version_id: string;
};

export type DeletePersonSchema = {
    asset_id: string;
    version_id: string;
};

export type EmbeddingBaseSchema = {
    readonly date_created?: string;
    embedding_vector?: Array<number>;
    type?: 'AUGMENTED' | 'NORMAL';
};

export type EmbeddingByFaceSchema = {
    readonly date_created?: string;
    embedding_vector?: Array<number>;
    readonly face_id?: string;
    readonly id?: string;
    readonly system_domain_id?: string;
    type?: 'AUGMENTED' | 'NORMAL';
};

export type EmbeddingByPersonSchema = {
    readonly date_created?: string;
    embedding_vector?: Array<number>;
    readonly id?: string;
    readonly person_id?: string;
    readonly system_domain_id?: string;
    type?: 'AUGMENTED' | 'NORMAL';
};

export type EmbeddingByStatusSchema = {
    readonly date_created?: string;
    readonly date_modified?: string;
    embedding_vector?: Array<number>;
    readonly id?: string;
    person_id?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    readonly system_domain_id?: string;
    type?: 'AUGMENTED' | 'NORMAL';
};

export type EmbeddingSchema = {
    readonly date_created?: string;
    readonly date_modified?: string;
    embedding_vector?: Array<number>;
    readonly id?: string;
    person_id?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    readonly system_domain_id?: string;
    type?: 'AUGMENTED' | 'NORMAL';
};

export type Face = {
    asset_id?: string;
    augmented_embedding_ids?: Array<string>;
    bounding_box?: Array<number>;
    readonly created_by_user?: string;
    readonly date_created?: string;
    readonly date_modified?: string;
    detection_probability?: number;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    readonly id?: string;
    readonly image_url?: string;
    landmarks?: Array<FaceLandmarkSchema>;
    readonly person_id?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
    readonly system_domain_id?: string;
    timestamp_ms?: number;
    version_id?: string;
};

export type FaceBaseSchema = {
    augmented_embedding_ids?: Array<string>;
    readonly created_by_user?: string;
    readonly date_created?: string;
    readonly date_modified?: string;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    readonly image_url?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
};

export type FaceByAssetAndVersionSchema = {
    readonly asset_id?: string;
    augmented_embedding_ids?: Array<string>;
    readonly created_by_user?: string;
    readonly date_created?: string;
    readonly date_modified?: string;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    readonly id?: string;
    readonly image_url?: string;
    readonly person_id?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
    readonly system_domain_id?: string;
    readonly version_id?: string;
};

export type FaceByPersonSchema = {
    augmented_embedding_ids?: Array<string>;
    readonly created_by_user?: string;
    readonly date_created?: string;
    readonly date_modified?: string;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    readonly id?: string;
    readonly image_url?: string;
    readonly person_id?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
    readonly system_domain_id?: string;
};

export type FaceLandmarkSchema = {
    x?: number;
    y?: number;
};

export type FaceListSchema = {
    readonly objects?: Array<Face>;
};

export type FaceSchema = {
    asset_id?: string;
    augmented_embedding_ids?: Array<string>;
    bounding_box?: Array<number>;
    readonly created_by_user?: string;
    readonly date_created?: string;
    readonly date_modified?: string;
    detection_probability?: number;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    readonly id?: string;
    readonly image_url?: string;
    landmarks?: Array<FaceLandmarkSchema>;
    readonly person_id?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
    readonly system_domain_id?: string;
    timestamp_ms?: number;
    version_id?: string;
};

export type JobsPrioritySchema = {
    job_ids: Array<string>;
    priority: number;
};

export type JobsStateSchema = {
    action: 'ABORT' | 'RESTART';
    job_ids: Array<string>;
};

export type ListObjectsSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly scroll_id?: string;
    readonly total?: number;
};

export type MlDetectionQueueRecordSchema = {
    bytes_params?: unknown;
    date_created?: string;
    date_updated?: string;
    id?: string;
    job_id: string;
    object_id?: string | null;
    object_type?: string | null;
    params?: string | null;
    parent_job_id?: string | null;
    priority?: number | null;
    retry_count?: number | null;
    spec?: string | null;
    status?: string | null;
    system_domain_id: string;
    system_name?: string;
    type?: string | null;
    user_id: string;
    version_id?: string | null;
};

export type Person = {
    readonly created_by_user: string | null;
    readonly date_created: string;
    readonly date_modified: string;
    readonly has_unconfirmed_instances: boolean;
    readonly id: string;
    readonly image_url: string | null;
    main_face_id: string | null;
    name: string | null;
    readonly person_version_face_image_url: string | null;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    readonly system_domain_id?: string;
};

export type PersonAssetsVersionsListSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<PersonByAssetAndVersionInAdmin>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly scroll_id?: string;
    readonly total?: number;
};

export type PersonByAssetAndVersion = {
    asset_id: string;
    readonly created_by_user: string | null;
    readonly date_created: string;
    readonly date_modified: string;
    readonly has_unconfirmed_instances: boolean;
    readonly id: string;
    readonly image_url: string | null;
    main_face_id: string | null;
    name: string | null;
    person_version_face_id: string;
    readonly person_version_face_image_url: string | null;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    readonly system_domain_id?: string;
    version_id: string;
};

export type PersonByAssetAndVersionInAdmin = {
    asset_id: string;
    asset_title: string;
    readonly created_by_user: string | null;
    readonly date_created: string;
    readonly date_modified: string;
    readonly has_unconfirmed_instances: boolean;
    readonly id: string;
    readonly image_url: string | null;
    main_face_id: string | null;
    name: string | null;
    person_version_face_id: string;
    readonly person_version_face_image_url: string | null;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    readonly system_domain_id?: string;
    version_id: string;
    version_number?: string;
};

export type PersonByAssetAndVersionInAdminSchema = {
    asset_id: string;
    asset_title: string;
    readonly created_by_user: string | null;
    readonly date_created: string;
    readonly date_modified: string;
    readonly has_unconfirmed_instances: boolean;
    readonly id: string;
    readonly image_url: string | null;
    main_face_id: string | null;
    name: string | null;
    person_version_face_id: string;
    readonly person_version_face_image_url: string | null;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    readonly system_domain_id?: string;
    version_id: string;
    version_number?: string;
};

export type PersonByAssetAndVersionListSchema = {
    objects?: Array<PersonByAssetAndVersion>;
};

export type PersonByAssetAndVersionSchema = {
    asset_id: string;
    readonly created_by_user: string | null;
    readonly date_created: string;
    readonly date_modified: string;
    readonly has_unconfirmed_instances: boolean;
    readonly id: string;
    readonly image_url: string | null;
    main_face_id: string | null;
    name: string | null;
    person_version_face_id: string;
    readonly person_version_face_image_url: string | null;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    readonly system_domain_id?: string;
    version_id: string;
};

export type PersonInstancesQueryParamsSchema = {
    include_admin_details?: boolean;
    /**
     * Which page number to fetch
     */
    page?: number | null;
    /**
     * The number of items for each page
     */
    per_page?: number | null;
    scroll?: boolean;
    scroll_id?: string;
    /**
     * A comma separated list of fieldnames with order (asc/desc)
     */
    sort?: string;
    use_instance_as_main_face?: boolean;
};

export type PersonListSchema = {
    readonly first_url?: string;
    readonly last_url?: string;
    readonly next_url?: string;
    readonly objects?: Array<Person>;
    readonly page?: number;
    readonly pages?: number;
    readonly per_page?: number;
    readonly prev_url?: string;
    readonly scroll_id?: string;
    readonly total?: number;
};

export type PersonSchema = {
    readonly created_by_user: string | null;
    readonly date_created: string;
    readonly date_modified: string;
    readonly has_unconfirmed_instances: boolean;
    readonly id: string;
    readonly image_url: string | null;
    main_face_id: string | null;
    name: string | null;
    readonly person_version_face_image_url: string | null;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    readonly system_domain_id?: string;
};

export type PersonsQueryParamsSchema = {
    /**
     * Which page number to fetch
     */
    page?: number | null;
    /**
     * The number of items for each page
     */
    per_page?: number | null;
    scroll?: boolean;
    scroll_id?: string;
    /**
     * A comma separated list of fieldnames with order (asc/desc)
     */
    sort?: string;
};

export type ReindexAllEmbeddingsSchema = {
    embedding_ids?: Array<string> | null;
    sync_to_another_dc?: boolean;
};

export type ReindexEmbeddingSchema = {
    sync_to_another_dc?: boolean;
};

export type ReindexPersonSchema = {
    sync_to_another_dc?: boolean;
};

export type ReindexQueueRecordSchema = {
    sync_to_another_dc?: boolean;
};

export type UrlSchema = {
    url?: string;
};

export type UpdateConfirmPersonSchema = {
    all_instances_except_unconfirmed?: boolean;
    name: string;
    version_ids?: Array<string> | null;
};

export type UpdatePersonSchema = {
    main_face_id?: string;
    name?: string | null;
};

export type VersionsSchema = {
    asset_id: string;
    version_ids?: Array<string>;
};

export type BulkPersonByAssetAndVersionWritable = {
    persons?: Array<PersonByAssetAndVersionWritable>;
    version_id: string;
};

export type BulkPersonByAssetAndVersionListSchemaWritable = {
    objects?: Array<BulkPersonByAssetAndVersionWritable>;
};

export type BulkPersonByAssetAndVersionSchemaWritable = {
    persons?: Array<PersonByAssetAndVersionWritable>;
    version_id: string;
};

export type EmbeddingBaseSchemaWritable = {
    embedding_vector?: Array<number>;
    type?: 'AUGMENTED' | 'NORMAL';
};

export type EmbeddingByFaceSchemaWritable = {
    embedding_vector?: Array<number>;
    type?: 'AUGMENTED' | 'NORMAL';
};

export type EmbeddingByPersonSchemaWritable = {
    embedding_vector?: Array<number>;
    type?: 'AUGMENTED' | 'NORMAL';
};

export type EmbeddingByStatusSchemaWritable = {
    embedding_vector?: Array<number>;
    person_id?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    type?: 'AUGMENTED' | 'NORMAL';
};

export type EmbeddingSchemaWritable = {
    embedding_vector?: Array<number>;
    person_id?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    type?: 'AUGMENTED' | 'NORMAL';
};

export type FaceWritable = {
    asset_id?: string;
    augmented_embedding_ids?: Array<string>;
    bounding_box?: Array<number>;
    detection_probability?: number;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    landmarks?: Array<FaceLandmarkSchema>;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
    timestamp_ms?: number;
    version_id?: string;
};

export type FaceBaseSchemaWritable = {
    augmented_embedding_ids?: Array<string>;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
};

export type FaceByAssetAndVersionSchemaWritable = {
    augmented_embedding_ids?: Array<string>;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
};

export type FaceByPersonSchemaWritable = {
    augmented_embedding_ids?: Array<string>;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
};

export type FaceListSchemaWritable = {
    [key: string]: unknown;
};

export type FaceSchemaWritable = {
    asset_id?: string;
    augmented_embedding_ids?: Array<string>;
    bounding_box?: Array<number>;
    detection_probability?: number;
    directory_path?: string;
    embedding_id?: string;
    filename?: string;
    landmarks?: Array<FaceLandmarkSchema>;
    status?: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    storage_id?: string;
    timestamp_ms?: number;
    version_id?: string;
};

export type PersonWritable = {
    main_face_id: string | null;
    name: string | null;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
};

export type PersonAssetsVersionsListSchemaWritable = {
    [key: string]: unknown;
};

export type PersonByAssetAndVersionWritable = {
    asset_id: string;
    main_face_id: string | null;
    name: string | null;
    person_version_face_id: string;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    version_id: string;
};

export type PersonByAssetAndVersionInAdminWritable = {
    asset_id: string;
    asset_title: string;
    main_face_id: string | null;
    name: string | null;
    person_version_face_id: string;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    version_id: string;
    version_number?: string;
};

export type PersonByAssetAndVersionInAdminSchemaWritable = {
    asset_id: string;
    asset_title: string;
    main_face_id: string | null;
    name: string | null;
    person_version_face_id: string;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    version_id: string;
    version_number?: string;
};

export type PersonByAssetAndVersionListSchemaWritable = {
    objects?: Array<PersonByAssetAndVersionWritable>;
};

export type PersonByAssetAndVersionSchemaWritable = {
    asset_id: string;
    main_face_id: string | null;
    name: string | null;
    person_version_face_id: string;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
    version_id: string;
};

export type PersonListSchemaWritable = {
    [key: string]: unknown;
};

export type PersonSchemaWritable = {
    main_face_id: string | null;
    name: string | null;
    status: 'NEW' | 'SYSTEM_CONFIRMED' | 'UNCONFIRMED' | 'USER_CONFIRMED';
};

export type DeleteFaceRecognitionAssetsByAssetIdPersonsBulkData = {
    /**
     * body
     */
    body: BulkDeletePersonsByVersionsSchema;
    path: {
        asset_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/assets/{asset_id}/persons/bulk/';
};

export type DeleteFaceRecognitionAssetsByAssetIdPersonsBulkErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteFaceRecognitionAssetsByAssetIdPersonsBulkError = DeleteFaceRecognitionAssetsByAssetIdPersonsBulkErrors[keyof DeleteFaceRecognitionAssetsByAssetIdPersonsBulkErrors];

export type DeleteFaceRecognitionAssetsByAssetIdPersonsBulkResponses = {
    /**
     * Returns the definition of the created job of deleting persons
     */
    201: unknown;
};

export type GetFaceRecognitionAssetsByAssetIdVersionsByVersionIdPersonsData = {
    body?: never;
    path: {
        asset_id: string;
        version_id: string;
    };
    query?: {
        fetch_image_url?: boolean;
    };
    url: '/v1/face_recognition/assets/{asset_id}/versions/{version_id}/persons/';
};

export type GetFaceRecognitionAssetsByAssetIdVersionsByVersionIdPersonsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetFaceRecognitionAssetsByAssetIdVersionsByVersionIdPersonsError = GetFaceRecognitionAssetsByAssetIdVersionsByVersionIdPersonsErrors[keyof GetFaceRecognitionAssetsByAssetIdVersionsByVersionIdPersonsErrors];

export type GetFaceRecognitionAssetsByAssetIdVersionsByVersionIdPersonsResponses = {
    /**
     * Returns a list of persons associated with the asset version
     */
    200: PersonByAssetAndVersionListSchema;
};

export type GetFaceRecognitionAssetsByAssetIdVersionsByVersionIdPersonsResponse = GetFaceRecognitionAssetsByAssetIdVersionsByVersionIdPersonsResponses[keyof GetFaceRecognitionAssetsByAssetIdVersionsByVersionIdPersonsResponses];

export type PostFaceRecognitionBulkExtractData = {
    /**
     * body
     */
    body?: BulkFaceExtractSchema;
    path?: never;
    query?: never;
    url: '/v1/face_recognition/bulk/extract/';
};

export type PostFaceRecognitionBulkExtractErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Face recognition is not enabled for this system domain
     */
    403: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionBulkExtractError = PostFaceRecognitionBulkExtractErrors[keyof PostFaceRecognitionBulkExtractErrors];

export type PostFaceRecognitionBulkExtractResponses = {
    /**
     * Process started
     */
    202: unknown;
};

export type PutFaceRecognitionChangePersonJobsStateData = {
    /**
     * body
     */
    body: JobsStateSchema;
    path?: never;
    query?: never;
    url: '/v1/face_recognition/change_person/jobs/state/';
};

export type PutFaceRecognitionChangePersonJobsStateErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutFaceRecognitionChangePersonJobsStateError = PutFaceRecognitionChangePersonJobsStateErrors[keyof PutFaceRecognitionChangePersonJobsStateErrors];

export type PutFaceRecognitionChangePersonJobsStateResponses = {
    /**
     * Job lock removed
     */
    200: unknown;
};

export type PostFaceRecognitionEmbeddingsReindexData = {
    /**
     * body
     */
    body?: ReindexAllEmbeddingsSchema;
    path?: never;
    query?: never;
    url: '/v1/face_recognition/embeddings/reindex/';
};

export type PostFaceRecognitionEmbeddingsReindexErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionEmbeddingsReindexError = PostFaceRecognitionEmbeddingsReindexErrors[keyof PostFaceRecognitionEmbeddingsReindexErrors];

export type PostFaceRecognitionEmbeddingsReindexResponses = {
    /**
     * Embeddings scheduled for reindexing
     */
    202: unknown;
};

export type PostFaceRecognitionEmbeddingsByEmbeddingIdReindexData = {
    /**
     * body
     */
    body: ReindexEmbeddingSchema;
    path: {
        embedding_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/embeddings/{embedding_id}/reindex/';
};

export type PostFaceRecognitionEmbeddingsByEmbeddingIdReindexErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * embedding does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionEmbeddingsByEmbeddingIdReindexError = PostFaceRecognitionEmbeddingsByEmbeddingIdReindexErrors[keyof PostFaceRecognitionEmbeddingsByEmbeddingIdReindexErrors];

export type PostFaceRecognitionEmbeddingsByEmbeddingIdReindexResponses = {
    /**
     * Embedding scheduled for reindexing
     */
    202: unknown;
};

export type PostFaceRecognitionExtractAssetsByAssetIdVersionsByVersionIdData = {
    body?: never;
    path: {
        /**
         * The asset to extract face images and face data from
         */
        asset_id: string;
        /**
         * The version to extract face images and face data from
         */
        version_id: string;
    };
    query?: {
        /**
         * The profile to use for face image analysis (default is used if not specified)
         */
        face_image_analysis_profile_id?: string;
        /**
         * The profile to use for face video analysis (default is used if not specified)
         */
        face_video_analysis_profile_id?: string;
        /**
         * If true, run faces recognition again even if persons already exist on asset
         */
        force?: boolean;
    };
    url: '/v1/face_recognition/extract/assets/{asset_id}/versions/{version_id}/';
};

export type PostFaceRecognitionExtractAssetsByAssetIdVersionsByVersionIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Face recognition is not enabled for this system domain
     */
    403: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionExtractAssetsByAssetIdVersionsByVersionIdError = PostFaceRecognitionExtractAssetsByAssetIdVersionsByVersionIdErrors[keyof PostFaceRecognitionExtractAssetsByAssetIdVersionsByVersionIdErrors];

export type PostFaceRecognitionExtractAssetsByAssetIdVersionsByVersionIdResponses = {
    /**
     * Process started
     */
    202: unknown;
};

export type PutFaceRecognitionJobsPriorityData = {
    /**
     * body
     */
    body: JobsPrioritySchema;
    path?: never;
    query?: never;
    url: '/v1/face_recognition/jobs/priority/';
};

export type PutFaceRecognitionJobsPriorityErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutFaceRecognitionJobsPriorityError = PutFaceRecognitionJobsPriorityErrors[keyof PutFaceRecognitionJobsPriorityErrors];

export type PutFaceRecognitionJobsPriorityResponses = {
    /**
     * task scheduled
     */
    202: unknown;
};

export type PutFaceRecognitionJobsStateData = {
    /**
     * body
     */
    body: JobsStateSchema;
    path?: never;
    query?: never;
    url: '/v1/face_recognition/jobs/state/';
};

export type PutFaceRecognitionJobsStateErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutFaceRecognitionJobsStateError = PutFaceRecognitionJobsStateErrors[keyof PutFaceRecognitionJobsStateErrors];

export type PutFaceRecognitionJobsStateResponses = {
    /**
     * task scheduled
     */
    202: unknown;
};

export type GetFaceRecognitionPersonsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of items for each page
         */
        per_page?: number;
        /**
         * Which page number to fetch
         */
        page?: number;
        /**
         * If true passed then uses scroll pagination instead of default one
         */
        scroll?: boolean;
        /**
         * In order to get next batch of results using scroll pagination the scroll_id is required
         */
        scroll_id?: string;
        /**
         * A comma separated list of fieldnames with order. For example - first_name,asc;last_name,desc
         */
        sort?: string;
        /**
         * Filter by status; NEW, UNCONFIRMED, USER_CONFIRMED or SYSTEM_CONFIRMED
         */
        status?: string;
        /**
         * Filter by name (can use wildcard search e.g. *doe*)
         */
        name?: string;
        /**
         * Filter by multiple statuses. Comma separated list of statuses.
         */
        status_in?: string;
        /**
         * Filter by persons with or without name
         */
        has_name?: boolean;
    };
    url: '/v1/face_recognition/persons/';
};

export type GetFaceRecognitionPersonsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetFaceRecognitionPersonsError = GetFaceRecognitionPersonsErrors[keyof GetFaceRecognitionPersonsErrors];

export type GetFaceRecognitionPersonsResponses = {
    /**
     * Returns the list of persons
     */
    200: PersonListSchema;
};

export type GetFaceRecognitionPersonsResponse = GetFaceRecognitionPersonsResponses[keyof GetFaceRecognitionPersonsResponses];

export type DeleteFaceRecognitionPersonsBulkDeleteData = {
    /**
     * body
     */
    body: BulkDeletePersonsByIdsSchema;
    path?: never;
    query?: never;
    url: '/v1/face_recognition/persons/bulk_delete/';
};

export type DeleteFaceRecognitionPersonsBulkDeleteErrors = {
    /**
     * Bad request or an invalid UUID
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteFaceRecognitionPersonsBulkDeleteError = DeleteFaceRecognitionPersonsBulkDeleteErrors[keyof DeleteFaceRecognitionPersonsBulkDeleteErrors];

export type DeleteFaceRecognitionPersonsBulkDeleteResponses = {
    /**
     * Returns the definition of the created job of deleting multiple persons in bulk
     */
    201: unknown;
};

export type PostFaceRecognitionPersonsReindexData = {
    /**
     * body
     */
    body: BulkReindexPersonsSchema;
    path?: never;
    query?: {
        /**
         * Whether to sync person data to the Assets index. Defaults to false.
         */
        sync_assets?: boolean;
        /**
         * Whether to use low priority indexing. Defaults to false.
         */
        low_priority_indexing?: boolean;
    };
    url: '/v1/face_recognition/persons/reindex/';
};

export type PostFaceRecognitionPersonsReindexErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionPersonsReindexError = PostFaceRecognitionPersonsReindexErrors[keyof PostFaceRecognitionPersonsReindexErrors];

export type PostFaceRecognitionPersonsReindexResponses = {
    /**
     * Persons scheduled for reindexing
     */
    202: unknown;
};

export type DeleteFaceRecognitionPersonsByPersonIdData = {
    body?: never;
    path: {
        person_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/';
};

export type DeleteFaceRecognitionPersonsByPersonIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteFaceRecognitionPersonsByPersonIdError = DeleteFaceRecognitionPersonsByPersonIdErrors[keyof DeleteFaceRecognitionPersonsByPersonIdErrors];

export type DeleteFaceRecognitionPersonsByPersonIdResponses = {
    /**
     * Returns the definition of the created job of deleting a person
     */
    201: unknown;
};

export type GetFaceRecognitionPersonsByPersonIdData = {
    body?: never;
    path: {
        person_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/';
};

export type GetFaceRecognitionPersonsByPersonIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetFaceRecognitionPersonsByPersonIdError = GetFaceRecognitionPersonsByPersonIdErrors[keyof GetFaceRecognitionPersonsByPersonIdErrors];

export type GetFaceRecognitionPersonsByPersonIdResponses = {
    /**
     * Returns a single person
     */
    200: PersonSchema;
};

export type GetFaceRecognitionPersonsByPersonIdResponse = GetFaceRecognitionPersonsByPersonIdResponses[keyof GetFaceRecognitionPersonsByPersonIdResponses];

export type PatchFaceRecognitionPersonsByPersonIdData = {
    /**
     * body
     */
    body: UpdatePersonSchema;
    path: {
        person_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/';
};

export type PatchFaceRecognitionPersonsByPersonIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PatchFaceRecognitionPersonsByPersonIdError = PatchFaceRecognitionPersonsByPersonIdErrors[keyof PatchFaceRecognitionPersonsByPersonIdErrors];

export type PatchFaceRecognitionPersonsByPersonIdResponses = {
    /**
     * Person updated successfully
     */
    200: PersonSchema;
};

export type PatchFaceRecognitionPersonsByPersonIdResponse = PatchFaceRecognitionPersonsByPersonIdResponses[keyof PatchFaceRecognitionPersonsByPersonIdResponses];

export type PutFaceRecognitionPersonsByPersonIdData = {
    /**
     * body
     */
    body: UpdatePersonSchema;
    path: {
        person_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/';
};

export type PutFaceRecognitionPersonsByPersonIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PutFaceRecognitionPersonsByPersonIdError = PutFaceRecognitionPersonsByPersonIdErrors[keyof PutFaceRecognitionPersonsByPersonIdErrors];

export type PutFaceRecognitionPersonsByPersonIdResponses = {
    /**
     * Person updated successfully
     */
    200: PersonSchema;
};

export type PutFaceRecognitionPersonsByPersonIdResponse = PutFaceRecognitionPersonsByPersonIdResponses[keyof PutFaceRecognitionPersonsByPersonIdResponses];

export type DeleteFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdData = {
    body?: never;
    path: {
        person_id: string;
        asset_id: string;
        version_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/assets/{asset_id}/versions/{version_id}/';
};

export type DeleteFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdError = DeleteFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdErrors[keyof DeleteFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdErrors];

export type DeleteFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdResponses = {
    /**
     * Person deleted successfully
     */
    204: void;
};

export type DeleteFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdResponse = DeleteFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdResponses[keyof DeleteFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdResponses];

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdChangePersonData = {
    /**
     * body
     */
    body: ChangePersonInstanceSchema;
    path: {
        person_id: string;
        asset_id: string;
        version_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/assets/{asset_id}/versions/{version_id}/change_person/';
};

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdChangePersonErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdChangePersonError = PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdChangePersonErrors[keyof PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdChangePersonErrors];

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdChangePersonResponses = {
    /**
     * Person change scheduled successfully
     */
    201: PersonByAssetAndVersionSchema;
};

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdChangePersonResponse = PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdChangePersonResponses[keyof PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdChangePersonResponses];

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdConfirmPersonData = {
    body?: never;
    path: {
        person_id: string;
        asset_id: string;
        version_id: string;
    };
    query?: {
        /**
         * Whether to use the instance face as main face or not
         */
        use_instance_as_main_face?: boolean;
    };
    url: '/v1/face_recognition/persons/{person_id}/assets/{asset_id}/versions/{version_id}/confirm_person/';
};

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdConfirmPersonErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdConfirmPersonError = PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdConfirmPersonErrors[keyof PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdConfirmPersonErrors];

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdConfirmPersonResponses = {
    /**
     * Person updated successfully
     */
    200: PersonByAssetAndVersionSchema;
};

export type PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdConfirmPersonResponse = PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdConfirmPersonResponses[keyof PostFaceRecognitionPersonsByPersonIdAssetsByAssetIdVersionsByVersionIdConfirmPersonResponses];

export type DeleteFaceRecognitionPersonsByPersonIdBulkData = {
    /**
     * body
     */
    body: BulkDeletePersonsSchema;
    path: {
        person_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/bulk/';
};

export type DeleteFaceRecognitionPersonsByPersonIdBulkErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type DeleteFaceRecognitionPersonsByPersonIdBulkError = DeleteFaceRecognitionPersonsByPersonIdBulkErrors[keyof DeleteFaceRecognitionPersonsByPersonIdBulkErrors];

export type DeleteFaceRecognitionPersonsByPersonIdBulkResponses = {
    /**
     * Returns the definition of the created job of deleting person instances
     */
    201: unknown;
};

export type PostFaceRecognitionPersonsByPersonIdConfirmPersonData = {
    /**
     * body
     */
    body: BulkConfirmPersonSchema;
    path: {
        person_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/confirm_person/';
};

export type PostFaceRecognitionPersonsByPersonIdConfirmPersonErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionPersonsByPersonIdConfirmPersonError = PostFaceRecognitionPersonsByPersonIdConfirmPersonErrors[keyof PostFaceRecognitionPersonsByPersonIdConfirmPersonErrors];

export type PostFaceRecognitionPersonsByPersonIdConfirmPersonResponses = {
    /**
     * Person instances successfully scheduled for confirmation
     */
    204: void;
};

export type PostFaceRecognitionPersonsByPersonIdConfirmPersonResponse = PostFaceRecognitionPersonsByPersonIdConfirmPersonResponses[keyof PostFaceRecognitionPersonsByPersonIdConfirmPersonResponses];

export type GetFaceRecognitionPersonsByPersonIdFacesByFaceIdImageUrlData = {
    body?: never;
    path: {
        person_id: string;
        face_id: string;
    };
    query?: {
        storage_id?: string;
    };
    url: '/v1/face_recognition/persons/{person_id}/faces/{face_id}/image_url/';
};

export type GetFaceRecognitionPersonsByPersonIdFacesByFaceIdImageUrlErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetFaceRecognitionPersonsByPersonIdFacesByFaceIdImageUrlError = GetFaceRecognitionPersonsByPersonIdFacesByFaceIdImageUrlErrors[keyof GetFaceRecognitionPersonsByPersonIdFacesByFaceIdImageUrlErrors];

export type GetFaceRecognitionPersonsByPersonIdFacesByFaceIdImageUrlResponses = {
    /**
     * Returns the presigned URL
     */
    200: UrlSchema;
};

export type GetFaceRecognitionPersonsByPersonIdFacesByFaceIdImageUrlResponse = GetFaceRecognitionPersonsByPersonIdFacesByFaceIdImageUrlResponses[keyof GetFaceRecognitionPersonsByPersonIdFacesByFaceIdImageUrlResponses];

export type PostFaceRecognitionPersonsByPersonIdMergeByNewPersonIdData = {
    body?: never;
    path: {
        person_id: string;
        new_person_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/merge/{new_person_id}/';
};

export type PostFaceRecognitionPersonsByPersonIdMergeByNewPersonIdErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionPersonsByPersonIdMergeByNewPersonIdError = PostFaceRecognitionPersonsByPersonIdMergeByNewPersonIdErrors[keyof PostFaceRecognitionPersonsByPersonIdMergeByNewPersonIdErrors];

export type PostFaceRecognitionPersonsByPersonIdMergeByNewPersonIdResponses = {
    /**
     * Returns the definition of the created job of changing a person
     */
    201: unknown;
};

export type PostFaceRecognitionPersonsByPersonIdReindexData = {
    /**
     * body
     */
    body?: ReindexPersonSchema;
    path: {
        person_id: string;
    };
    query?: {
        /**
         * Whether to sync person data to the Assets index. Defaults to true.
         */
        sync_assets?: boolean;
        /**
         * Whether to use low priority indexing. Defaults to false.
         */
        low_priority_indexing?: boolean;
    };
    url: '/v1/face_recognition/persons/{person_id}/reindex/';
};

export type PostFaceRecognitionPersonsByPersonIdReindexErrors = {
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * person does not exist
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionPersonsByPersonIdReindexError = PostFaceRecognitionPersonsByPersonIdReindexErrors[keyof PostFaceRecognitionPersonsByPersonIdReindexErrors];

export type PostFaceRecognitionPersonsByPersonIdReindexResponses = {
    /**
     * Person scheduled for reindexing
     */
    202: unknown;
};

export type PostFaceRecognitionPersonsByPersonIdUpdateAndConfirmData = {
    /**
     * body
     */
    body: UpdateConfirmPersonSchema;
    path: {
        person_id: string;
    };
    query?: never;
    url: '/v1/face_recognition/persons/{person_id}/update_and_confirm/';
};

export type PostFaceRecognitionPersonsByPersonIdUpdateAndConfirmErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Person not found
     */
    404: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type PostFaceRecognitionPersonsByPersonIdUpdateAndConfirmError = PostFaceRecognitionPersonsByPersonIdUpdateAndConfirmErrors[keyof PostFaceRecognitionPersonsByPersonIdUpdateAndConfirmErrors];

export type PostFaceRecognitionPersonsByPersonIdUpdateAndConfirmResponses = {
    /**
     * Person updated and instances successfully scheduled for confirmation
     */
    200: PersonSchema;
};

export type PostFaceRecognitionPersonsByPersonIdUpdateAndConfirmResponse = PostFaceRecognitionPersonsByPersonIdUpdateAndConfirmResponses[keyof PostFaceRecognitionPersonsByPersonIdUpdateAndConfirmResponses];

export type GetFaceRecognitionPersonsByPersonIdVersionsData = {
    body?: never;
    path: {
        person_id: string;
    };
    query?: {
        /**
         * The number of items for each page
         */
        per_page?: number;
        /**
         * Which page number to fetch
         */
        page?: number;
        /**
         * Whether to include admin details in the response or not
         */
        include_admin_details?: boolean;
        /**
         * Whether to use the instance face as main face or not
         */
        use_instance_as_main_face?: boolean;
    };
    url: '/v1/face_recognition/persons/{person_id}/versions/';
};

export type GetFaceRecognitionPersonsByPersonIdVersionsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Token is invalid
     */
    401: unknown;
    /**
     * Error response
     */
    default: {
        errors?: Array<string>;
    } | {
        errors?: {
            [key: string]: unknown;
        };
    };
};

export type GetFaceRecognitionPersonsByPersonIdVersionsError = GetFaceRecognitionPersonsByPersonIdVersionsErrors[keyof GetFaceRecognitionPersonsByPersonIdVersionsErrors];

export type GetFaceRecognitionPersonsByPersonIdVersionsResponses = {
    /**
     * Returns a list of persons by asset and version
     */
    200: PersonAssetsVersionsListSchema;
};

export type GetFaceRecognitionPersonsByPersonIdVersionsResponse = GetFaceRecognitionPersonsByPersonIdVersionsResponses[keyof GetFaceRecognitionPersonsByPersonIdVersionsResponses];
